package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Acactgrp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ACACTGRP.ACACTGRP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal acactgrpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ACACTGRP.GROUPNAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String groupname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ACACTGRP.MEMBER_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ACACTGRP.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String field1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ACACTGRP.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ACACTGRP.ACACTGRP_ID
     *
     * @return the value of EMDI.ACACTGRP.ACACTGRP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getAcactgrpId() {
        return acactgrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ACACTGRP.ACACTGRP_ID
     *
     * @param acactgrpId the value for EMDI.ACACTGRP.ACACTGRP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setAcactgrpId(BigDecimal acactgrpId) {
        this.acactgrpId = acactgrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ACACTGRP.GROUPNAME
     *
     * @return the value of EMDI.ACACTGRP.GROUPNAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ACACTGRP.GROUPNAME
     *
     * @param groupname the value for EMDI.ACACTGRP.GROUPNAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ACACTGRP.MEMBER_ID
     *
     * @return the value of EMDI.ACACTGRP.MEMBER_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ACACTGRP.MEMBER_ID
     *
     * @param memberId the value for EMDI.ACACTGRP.MEMBER_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setMemberId(BigDecimal memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ACACTGRP.FIELD1
     *
     * @return the value of EMDI.ACACTGRP.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ACACTGRP.FIELD1
     *
     * @param field1 the value for EMDI.ACACTGRP.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField1(String field1) {
        this.field1 = field1 == null ? null : field1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ACACTGRP.OPTCOUNTER
     *
     * @return the value of EMDI.ACACTGRP.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ACACTGRP.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.ACACTGRP.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}