package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Acresrel extends AcresrelKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ACRESREL.RESRELTABLE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String resreltable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ACRESREL.RESRELMEMCOL
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String resrelmemcol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ACRESREL.RESRELKEYCOL
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String resrelkeycol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ACRESREL.RESRELCOL
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String resrelcol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ACRESREL.RESJOINCOL
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String resjoincol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ACRESREL.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String field1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ACRESREL.RESOURCETYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String resourcetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ACRESREL.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ACRESREL.RESRELTABLE
     *
     * @return the value of EMDI.ACRESREL.RESRELTABLE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getResreltable() {
        return resreltable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ACRESREL.RESRELTABLE
     *
     * @param resreltable the value for EMDI.ACRESREL.RESRELTABLE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setResreltable(String resreltable) {
        this.resreltable = resreltable == null ? null : resreltable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ACRESREL.RESRELMEMCOL
     *
     * @return the value of EMDI.ACRESREL.RESRELMEMCOL
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getResrelmemcol() {
        return resrelmemcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ACRESREL.RESRELMEMCOL
     *
     * @param resrelmemcol the value for EMDI.ACRESREL.RESRELMEMCOL
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setResrelmemcol(String resrelmemcol) {
        this.resrelmemcol = resrelmemcol == null ? null : resrelmemcol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ACRESREL.RESRELKEYCOL
     *
     * @return the value of EMDI.ACRESREL.RESRELKEYCOL
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getResrelkeycol() {
        return resrelkeycol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ACRESREL.RESRELKEYCOL
     *
     * @param resrelkeycol the value for EMDI.ACRESREL.RESRELKEYCOL
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setResrelkeycol(String resrelkeycol) {
        this.resrelkeycol = resrelkeycol == null ? null : resrelkeycol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ACRESREL.RESRELCOL
     *
     * @return the value of EMDI.ACRESREL.RESRELCOL
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getResrelcol() {
        return resrelcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ACRESREL.RESRELCOL
     *
     * @param resrelcol the value for EMDI.ACRESREL.RESRELCOL
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setResrelcol(String resrelcol) {
        this.resrelcol = resrelcol == null ? null : resrelcol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ACRESREL.RESJOINCOL
     *
     * @return the value of EMDI.ACRESREL.RESJOINCOL
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getResjoincol() {
        return resjoincol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ACRESREL.RESJOINCOL
     *
     * @param resjoincol the value for EMDI.ACRESREL.RESJOINCOL
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setResjoincol(String resjoincol) {
        this.resjoincol = resjoincol == null ? null : resjoincol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ACRESREL.FIELD1
     *
     * @return the value of EMDI.ACRESREL.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ACRESREL.FIELD1
     *
     * @param field1 the value for EMDI.ACRESREL.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField1(String field1) {
        this.field1 = field1 == null ? null : field1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ACRESREL.RESOURCETYPE
     *
     * @return the value of EMDI.ACRESREL.RESOURCETYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getResourcetype() {
        return resourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ACRESREL.RESOURCETYPE
     *
     * @param resourcetype the value for EMDI.ACRESREL.RESOURCETYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setResourcetype(String resourcetype) {
        this.resourcetype = resourcetype == null ? null : resourcetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ACRESREL.OPTCOUNTER
     *
     * @return the value of EMDI.ACRESREL.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ACRESREL.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.ACRESREL.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}