package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class AcresgpdesKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ACRESGPDES.ACRESGRP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal acresgrpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ACRESGPDES.LANGUAGE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal languageId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ACRESGPDES.ACRESGRP_ID
     *
     * @return the value of EMDI.ACRESGPDES.ACRESGRP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getAcresgrpId() {
        return acresgrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ACRESGPDES.ACRESGRP_ID
     *
     * @param acresgrpId the value for EMDI.ACRESGPDES.ACRESGRP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setAcresgrpId(BigDecimal acresgrpId) {
        this.acresgrpId = acresgrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ACRESGPDES.LANGUAGE_ID
     *
     * @return the value of EMDI.ACRESGPDES.LANGUAGE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getLanguageId() {
        return languageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ACRESGPDES.LANGUAGE_ID
     *
     * @param languageId the value for EMDI.ACRESGPDES.LANGUAGE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setLanguageId(BigDecimal languageId) {
        this.languageId = languageId;
    }
}