package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Atchtgtdsc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ATCHTGTDSC.ATCHTGTDSC_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal atchtgtdscId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ATCHTGTDSC.ATCHTGT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal atchtgtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ATCHTGTDSC.LANGUAGE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal languageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ATCHTGTDSC.NAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ATCHTGTDSC.SHORTDESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String shortdescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ATCHTGTDSC.LONGDESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String longdescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ATCHTGTDSC.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ATCHTGTDSC.ATCHTGTDSC_ID
     *
     * @return the value of EMDI.ATCHTGTDSC.ATCHTGTDSC_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getAtchtgtdscId() {
        return atchtgtdscId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ATCHTGTDSC.ATCHTGTDSC_ID
     *
     * @param atchtgtdscId the value for EMDI.ATCHTGTDSC.ATCHTGTDSC_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setAtchtgtdscId(BigDecimal atchtgtdscId) {
        this.atchtgtdscId = atchtgtdscId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ATCHTGTDSC.ATCHTGT_ID
     *
     * @return the value of EMDI.ATCHTGTDSC.ATCHTGT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getAtchtgtId() {
        return atchtgtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ATCHTGTDSC.ATCHTGT_ID
     *
     * @param atchtgtId the value for EMDI.ATCHTGTDSC.ATCHTGT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setAtchtgtId(BigDecimal atchtgtId) {
        this.atchtgtId = atchtgtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ATCHTGTDSC.LANGUAGE_ID
     *
     * @return the value of EMDI.ATCHTGTDSC.LANGUAGE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getLanguageId() {
        return languageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ATCHTGTDSC.LANGUAGE_ID
     *
     * @param languageId the value for EMDI.ATCHTGTDSC.LANGUAGE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setLanguageId(BigDecimal languageId) {
        this.languageId = languageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ATCHTGTDSC.NAME
     *
     * @return the value of EMDI.ATCHTGTDSC.NAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ATCHTGTDSC.NAME
     *
     * @param name the value for EMDI.ATCHTGTDSC.NAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ATCHTGTDSC.SHORTDESCRIPTION
     *
     * @return the value of EMDI.ATCHTGTDSC.SHORTDESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getShortdescription() {
        return shortdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ATCHTGTDSC.SHORTDESCRIPTION
     *
     * @param shortdescription the value for EMDI.ATCHTGTDSC.SHORTDESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setShortdescription(String shortdescription) {
        this.shortdescription = shortdescription == null ? null : shortdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ATCHTGTDSC.LONGDESCRIPTION
     *
     * @return the value of EMDI.ATCHTGTDSC.LONGDESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getLongdescription() {
        return longdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ATCHTGTDSC.LONGDESCRIPTION
     *
     * @param longdescription the value for EMDI.ATCHTGTDSC.LONGDESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setLongdescription(String longdescription) {
        this.longdescription = longdescription == null ? null : longdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ATCHTGTDSC.OPTCOUNTER
     *
     * @return the value of EMDI.ATCHTGTDSC.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ATCHTGTDSC.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.ATCHTGTDSC.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}