package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Busprof {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.BUSPROF.USERS_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal usersId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.BUSPROF.EMPLOYEEID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String employeeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.BUSPROF.ORG_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.BUSPROF.ORGUNIT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal orgunitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.BUSPROF.EMPLOYEETYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String employeetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.BUSPROF.DEPARTMENTNUM
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String departmentnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.BUSPROF.ALTERNATEID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String alternateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.BUSPROF.MANAGER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String manager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.BUSPROF.SECRETARY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String secretary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.BUSPROF.REQUISITIONERID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String requisitionerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.BUSPROF.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.BUSPROF.USERS_ID
     *
     * @return the value of EMDI.BUSPROF.USERS_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getUsersId() {
        return usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.BUSPROF.USERS_ID
     *
     * @param usersId the value for EMDI.BUSPROF.USERS_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setUsersId(BigDecimal usersId) {
        this.usersId = usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.BUSPROF.EMPLOYEEID
     *
     * @return the value of EMDI.BUSPROF.EMPLOYEEID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.BUSPROF.EMPLOYEEID
     *
     * @param employeeid the value for EMDI.BUSPROF.EMPLOYEEID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid == null ? null : employeeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.BUSPROF.ORG_ID
     *
     * @return the value of EMDI.BUSPROF.ORG_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.BUSPROF.ORG_ID
     *
     * @param orgId the value for EMDI.BUSPROF.ORG_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOrgId(BigDecimal orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.BUSPROF.ORGUNIT_ID
     *
     * @return the value of EMDI.BUSPROF.ORGUNIT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOrgunitId() {
        return orgunitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.BUSPROF.ORGUNIT_ID
     *
     * @param orgunitId the value for EMDI.BUSPROF.ORGUNIT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOrgunitId(BigDecimal orgunitId) {
        this.orgunitId = orgunitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.BUSPROF.EMPLOYEETYPE
     *
     * @return the value of EMDI.BUSPROF.EMPLOYEETYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getEmployeetype() {
        return employeetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.BUSPROF.EMPLOYEETYPE
     *
     * @param employeetype the value for EMDI.BUSPROF.EMPLOYEETYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setEmployeetype(String employeetype) {
        this.employeetype = employeetype == null ? null : employeetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.BUSPROF.DEPARTMENTNUM
     *
     * @return the value of EMDI.BUSPROF.DEPARTMENTNUM
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getDepartmentnum() {
        return departmentnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.BUSPROF.DEPARTMENTNUM
     *
     * @param departmentnum the value for EMDI.BUSPROF.DEPARTMENTNUM
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setDepartmentnum(String departmentnum) {
        this.departmentnum = departmentnum == null ? null : departmentnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.BUSPROF.ALTERNATEID
     *
     * @return the value of EMDI.BUSPROF.ALTERNATEID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getAlternateid() {
        return alternateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.BUSPROF.ALTERNATEID
     *
     * @param alternateid the value for EMDI.BUSPROF.ALTERNATEID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setAlternateid(String alternateid) {
        this.alternateid = alternateid == null ? null : alternateid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.BUSPROF.MANAGER
     *
     * @return the value of EMDI.BUSPROF.MANAGER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.BUSPROF.MANAGER
     *
     * @param manager the value for EMDI.BUSPROF.MANAGER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setManager(String manager) {
        this.manager = manager == null ? null : manager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.BUSPROF.SECRETARY
     *
     * @return the value of EMDI.BUSPROF.SECRETARY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getSecretary() {
        return secretary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.BUSPROF.SECRETARY
     *
     * @param secretary the value for EMDI.BUSPROF.SECRETARY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSecretary(String secretary) {
        this.secretary = secretary == null ? null : secretary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.BUSPROF.REQUISITIONERID
     *
     * @return the value of EMDI.BUSPROF.REQUISITIONERID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getRequisitionerid() {
        return requisitionerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.BUSPROF.REQUISITIONERID
     *
     * @param requisitionerid the value for EMDI.BUSPROF.REQUISITIONERID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setRequisitionerid(String requisitionerid) {
        this.requisitionerid = requisitionerid == null ? null : requisitionerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.BUSPROF.OPTCOUNTER
     *
     * @return the value of EMDI.BUSPROF.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.BUSPROF.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.BUSPROF.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}