package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Buyerpo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.BUYERPO.BUYERPO_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal buyerpoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.BUYERPO.SETCCURR
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String setccurr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.BUYERPO.ACCOUNT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.BUYERPO.PONUMBER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String ponumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.BUYERPO.BUYERPOTYP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal buyerpotypId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.BUYERPO.STATE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.BUYERPO.AMOUNT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.BUYERPO.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.BUYERPO.BUYERPO_ID
     *
     * @return the value of EMDI.BUYERPO.BUYERPO_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getBuyerpoId() {
        return buyerpoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.BUYERPO.BUYERPO_ID
     *
     * @param buyerpoId the value for EMDI.BUYERPO.BUYERPO_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setBuyerpoId(BigDecimal buyerpoId) {
        this.buyerpoId = buyerpoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.BUYERPO.SETCCURR
     *
     * @return the value of EMDI.BUYERPO.SETCCURR
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getSetccurr() {
        return setccurr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.BUYERPO.SETCCURR
     *
     * @param setccurr the value for EMDI.BUYERPO.SETCCURR
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSetccurr(String setccurr) {
        this.setccurr = setccurr == null ? null : setccurr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.BUYERPO.ACCOUNT_ID
     *
     * @return the value of EMDI.BUYERPO.ACCOUNT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.BUYERPO.ACCOUNT_ID
     *
     * @param accountId the value for EMDI.BUYERPO.ACCOUNT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setAccountId(BigDecimal accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.BUYERPO.PONUMBER
     *
     * @return the value of EMDI.BUYERPO.PONUMBER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getPonumber() {
        return ponumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.BUYERPO.PONUMBER
     *
     * @param ponumber the value for EMDI.BUYERPO.PONUMBER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setPonumber(String ponumber) {
        this.ponumber = ponumber == null ? null : ponumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.BUYERPO.BUYERPOTYP_ID
     *
     * @return the value of EMDI.BUYERPO.BUYERPOTYP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getBuyerpotypId() {
        return buyerpotypId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.BUYERPO.BUYERPOTYP_ID
     *
     * @param buyerpotypId the value for EMDI.BUYERPO.BUYERPOTYP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setBuyerpotypId(BigDecimal buyerpotypId) {
        this.buyerpotypId = buyerpotypId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.BUYERPO.STATE
     *
     * @return the value of EMDI.BUYERPO.STATE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.BUYERPO.STATE
     *
     * @param state the value for EMDI.BUYERPO.STATE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setState(BigDecimal state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.BUYERPO.AMOUNT
     *
     * @return the value of EMDI.BUYERPO.AMOUNT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.BUYERPO.AMOUNT
     *
     * @param amount the value for EMDI.BUYERPO.AMOUNT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.BUYERPO.OPTCOUNTER
     *
     * @return the value of EMDI.BUYERPO.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.BUYERPO.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.BUYERPO.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}