package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class BuysupmapKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.BUYSUPMAP.SUPORG_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal suporgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.BUYSUPMAP.BUYORGUNIT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal buyorgunitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.BUYSUPMAP.PROCPROTCL_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal procprotclId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.BUYSUPMAP.SUPORG_ID
     *
     * @return the value of EMDI.BUYSUPMAP.SUPORG_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getSuporgId() {
        return suporgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.BUYSUPMAP.SUPORG_ID
     *
     * @param suporgId the value for EMDI.BUYSUPMAP.SUPORG_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSuporgId(BigDecimal suporgId) {
        this.suporgId = suporgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.BUYSUPMAP.BUYORGUNIT_ID
     *
     * @return the value of EMDI.BUYSUPMAP.BUYORGUNIT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getBuyorgunitId() {
        return buyorgunitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.BUYSUPMAP.BUYORGUNIT_ID
     *
     * @param buyorgunitId the value for EMDI.BUYSUPMAP.BUYORGUNIT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setBuyorgunitId(BigDecimal buyorgunitId) {
        this.buyorgunitId = buyorgunitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.BUYSUPMAP.PROCPROTCL_ID
     *
     * @return the value of EMDI.BUYSUPMAP.PROCPROTCL_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getProcprotclId() {
        return procprotclId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.BUYSUPMAP.PROCPROTCL_ID
     *
     * @param procprotclId the value for EMDI.BUYSUPMAP.PROCPROTCL_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setProcprotclId(BigDecimal procprotclId) {
        this.procprotclId = procprotclId;
    }
}