package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Calscale {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CALSCALE.CALSCALE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal calscaleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CALSCALE.QTYUNIT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String qtyunitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CALSCALE.CODE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CALSCALE.DESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CALSCALE.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal storeentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CALSCALE.CALUSAGE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal calusageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CALSCALE.SETCCURR
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String setccurr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CALSCALE.CALMETHOD_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal calmethodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CALSCALE.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String field1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CALSCALE.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CALSCALE.CALSCALE_ID
     *
     * @return the value of EMDI.CALSCALE.CALSCALE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getCalscaleId() {
        return calscaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CALSCALE.CALSCALE_ID
     *
     * @param calscaleId the value for EMDI.CALSCALE.CALSCALE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCalscaleId(BigDecimal calscaleId) {
        this.calscaleId = calscaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CALSCALE.QTYUNIT_ID
     *
     * @return the value of EMDI.CALSCALE.QTYUNIT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getQtyunitId() {
        return qtyunitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CALSCALE.QTYUNIT_ID
     *
     * @param qtyunitId the value for EMDI.CALSCALE.QTYUNIT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setQtyunitId(String qtyunitId) {
        this.qtyunitId = qtyunitId == null ? null : qtyunitId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CALSCALE.CODE
     *
     * @return the value of EMDI.CALSCALE.CODE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CALSCALE.CODE
     *
     * @param code the value for EMDI.CALSCALE.CODE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CALSCALE.DESCRIPTION
     *
     * @return the value of EMDI.CALSCALE.DESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CALSCALE.DESCRIPTION
     *
     * @param description the value for EMDI.CALSCALE.DESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CALSCALE.STOREENT_ID
     *
     * @return the value of EMDI.CALSCALE.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getStoreentId() {
        return storeentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CALSCALE.STOREENT_ID
     *
     * @param storeentId the value for EMDI.CALSCALE.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setStoreentId(BigDecimal storeentId) {
        this.storeentId = storeentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CALSCALE.CALUSAGE_ID
     *
     * @return the value of EMDI.CALSCALE.CALUSAGE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getCalusageId() {
        return calusageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CALSCALE.CALUSAGE_ID
     *
     * @param calusageId the value for EMDI.CALSCALE.CALUSAGE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCalusageId(BigDecimal calusageId) {
        this.calusageId = calusageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CALSCALE.SETCCURR
     *
     * @return the value of EMDI.CALSCALE.SETCCURR
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getSetccurr() {
        return setccurr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CALSCALE.SETCCURR
     *
     * @param setccurr the value for EMDI.CALSCALE.SETCCURR
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSetccurr(String setccurr) {
        this.setccurr = setccurr == null ? null : setccurr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CALSCALE.CALMETHOD_ID
     *
     * @return the value of EMDI.CALSCALE.CALMETHOD_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getCalmethodId() {
        return calmethodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CALSCALE.CALMETHOD_ID
     *
     * @param calmethodId the value for EMDI.CALSCALE.CALMETHOD_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCalmethodId(BigDecimal calmethodId) {
        this.calmethodId = calmethodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CALSCALE.FIELD1
     *
     * @return the value of EMDI.CALSCALE.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CALSCALE.FIELD1
     *
     * @param field1 the value for EMDI.CALSCALE.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField1(String field1) {
        this.field1 = field1 == null ? null : field1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CALSCALE.OPTCOUNTER
     *
     * @return the value of EMDI.CALSCALE.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CALSCALE.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.CALSCALE.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}