package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Catentship {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CATENTSHIP.CATENTRY_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal catentryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CATENTSHIP.WEIGHT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CATENTSHIP.WEIGHTMEASURE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String weightmeasure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CATENTSHIP.LENGTH
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CATENTSHIP.WIDTH
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CATENTSHIP.HEIGHT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CATENTSHIP.SIZEMEASURE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String sizemeasure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CATENTSHIP.NOMINALQUANTITY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal nominalquantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CATENTSHIP.QUANTITYMULTIPLE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal quantitymultiple;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CATENTSHIP.QUANTITYMEASURE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String quantitymeasure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CATENTSHIP.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CATENTSHIP.CATENTRY_ID
     *
     * @return the value of EMDI.CATENTSHIP.CATENTRY_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getCatentryId() {
        return catentryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CATENTSHIP.CATENTRY_ID
     *
     * @param catentryId the value for EMDI.CATENTSHIP.CATENTRY_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCatentryId(BigDecimal catentryId) {
        this.catentryId = catentryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CATENTSHIP.WEIGHT
     *
     * @return the value of EMDI.CATENTSHIP.WEIGHT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CATENTSHIP.WEIGHT
     *
     * @param weight the value for EMDI.CATENTSHIP.WEIGHT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CATENTSHIP.WEIGHTMEASURE
     *
     * @return the value of EMDI.CATENTSHIP.WEIGHTMEASURE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getWeightmeasure() {
        return weightmeasure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CATENTSHIP.WEIGHTMEASURE
     *
     * @param weightmeasure the value for EMDI.CATENTSHIP.WEIGHTMEASURE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setWeightmeasure(String weightmeasure) {
        this.weightmeasure = weightmeasure == null ? null : weightmeasure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CATENTSHIP.LENGTH
     *
     * @return the value of EMDI.CATENTSHIP.LENGTH
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CATENTSHIP.LENGTH
     *
     * @param length the value for EMDI.CATENTSHIP.LENGTH
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setLength(BigDecimal length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CATENTSHIP.WIDTH
     *
     * @return the value of EMDI.CATENTSHIP.WIDTH
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CATENTSHIP.WIDTH
     *
     * @param width the value for EMDI.CATENTSHIP.WIDTH
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setWidth(BigDecimal width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CATENTSHIP.HEIGHT
     *
     * @return the value of EMDI.CATENTSHIP.HEIGHT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CATENTSHIP.HEIGHT
     *
     * @param height the value for EMDI.CATENTSHIP.HEIGHT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setHeight(BigDecimal height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CATENTSHIP.SIZEMEASURE
     *
     * @return the value of EMDI.CATENTSHIP.SIZEMEASURE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getSizemeasure() {
        return sizemeasure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CATENTSHIP.SIZEMEASURE
     *
     * @param sizemeasure the value for EMDI.CATENTSHIP.SIZEMEASURE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSizemeasure(String sizemeasure) {
        this.sizemeasure = sizemeasure == null ? null : sizemeasure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CATENTSHIP.NOMINALQUANTITY
     *
     * @return the value of EMDI.CATENTSHIP.NOMINALQUANTITY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getNominalquantity() {
        return nominalquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CATENTSHIP.NOMINALQUANTITY
     *
     * @param nominalquantity the value for EMDI.CATENTSHIP.NOMINALQUANTITY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setNominalquantity(BigDecimal nominalquantity) {
        this.nominalquantity = nominalquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CATENTSHIP.QUANTITYMULTIPLE
     *
     * @return the value of EMDI.CATENTSHIP.QUANTITYMULTIPLE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getQuantitymultiple() {
        return quantitymultiple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CATENTSHIP.QUANTITYMULTIPLE
     *
     * @param quantitymultiple the value for EMDI.CATENTSHIP.QUANTITYMULTIPLE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setQuantitymultiple(BigDecimal quantitymultiple) {
        this.quantitymultiple = quantitymultiple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CATENTSHIP.QUANTITYMEASURE
     *
     * @return the value of EMDI.CATENTSHIP.QUANTITYMEASURE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getQuantitymeasure() {
        return quantitymeasure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CATENTSHIP.QUANTITYMEASURE
     *
     * @param quantitymeasure the value for EMDI.CATENTSHIP.QUANTITYMEASURE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setQuantitymeasure(String quantitymeasure) {
        this.quantitymeasure = quantitymeasure == null ? null : quantitymeasure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CATENTSHIP.OPTCOUNTER
     *
     * @return the value of EMDI.CATENTSHIP.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CATENTSHIP.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.CATENTSHIP.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}