package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Catenttype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CATENTTYPE.CATENTTYPE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String catenttypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CATENTTYPE.DESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CATENTTYPE.OID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CATENTTYPE.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CATENTTYPE.CATENTTYPE_ID
     *
     * @return the value of EMDI.CATENTTYPE.CATENTTYPE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getCatenttypeId() {
        return catenttypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CATENTTYPE.CATENTTYPE_ID
     *
     * @param catenttypeId the value for EMDI.CATENTTYPE.CATENTTYPE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCatenttypeId(String catenttypeId) {
        this.catenttypeId = catenttypeId == null ? null : catenttypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CATENTTYPE.DESCRIPTION
     *
     * @return the value of EMDI.CATENTTYPE.DESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CATENTTYPE.DESCRIPTION
     *
     * @param description the value for EMDI.CATENTTYPE.DESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CATENTTYPE.OID
     *
     * @return the value of EMDI.CATENTTYPE.OID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CATENTTYPE.OID
     *
     * @param oid the value for EMDI.CATENTTYPE.OID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CATENTTYPE.OPTCOUNTER
     *
     * @return the value of EMDI.CATENTTYPE.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CATENTTYPE.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.CATENTTYPE.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}