package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class CattogrpKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CATTOGRP.CATALOG_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal catalogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CATTOGRP.CATGROUP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal catgroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CATTOGRP.CATALOG_ID
     *
     * @return the value of EMDI.CATTOGRP.CATALOG_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getCatalogId() {
        return catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CATTOGRP.CATALOG_ID
     *
     * @param catalogId the value for EMDI.CATTOGRP.CATALOG_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCatalogId(BigDecimal catalogId) {
        this.catalogId = catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CATTOGRP.CATGROUP_ID
     *
     * @return the value of EMDI.CATTOGRP.CATGROUP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getCatgroupId() {
        return catgroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CATTOGRP.CATGROUP_ID
     *
     * @param catgroupId the value for EMDI.CATTOGRP.CATGROUP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCatgroupId(BigDecimal catgroupId) {
        this.catgroupId = catgroupId;
    }
}