package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Cfcondgrp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CFCONDGRP.CFCONDGRP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal cfcondgrpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CFCONDGRP.CFCATGROUP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal cfcatgroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CFCONDGRP.IDENTIFIER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String identifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CFCONDGRP.CONDITIONRELATION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal conditionrelation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CFCONDGRP.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal field1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CFCONDGRP.FIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal field2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CFCONDGRP.FIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String field3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CFCONDGRP.FIELD4
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal field4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CFCONDGRP.FIELD5
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal field5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CFCONDGRP.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CFCONDGRP.CFCONDGRP_ID
     *
     * @return the value of EMDI.CFCONDGRP.CFCONDGRP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getCfcondgrpId() {
        return cfcondgrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CFCONDGRP.CFCONDGRP_ID
     *
     * @param cfcondgrpId the value for EMDI.CFCONDGRP.CFCONDGRP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCfcondgrpId(BigDecimal cfcondgrpId) {
        this.cfcondgrpId = cfcondgrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CFCONDGRP.CFCATGROUP_ID
     *
     * @return the value of EMDI.CFCONDGRP.CFCATGROUP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getCfcatgroupId() {
        return cfcatgroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CFCONDGRP.CFCATGROUP_ID
     *
     * @param cfcatgroupId the value for EMDI.CFCONDGRP.CFCATGROUP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCfcatgroupId(BigDecimal cfcatgroupId) {
        this.cfcatgroupId = cfcatgroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CFCONDGRP.IDENTIFIER
     *
     * @return the value of EMDI.CFCONDGRP.IDENTIFIER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CFCONDGRP.IDENTIFIER
     *
     * @param identifier the value for EMDI.CFCONDGRP.IDENTIFIER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier == null ? null : identifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CFCONDGRP.CONDITIONRELATION
     *
     * @return the value of EMDI.CFCONDGRP.CONDITIONRELATION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getConditionrelation() {
        return conditionrelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CFCONDGRP.CONDITIONRELATION
     *
     * @param conditionrelation the value for EMDI.CFCONDGRP.CONDITIONRELATION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setConditionrelation(BigDecimal conditionrelation) {
        this.conditionrelation = conditionrelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CFCONDGRP.FIELD1
     *
     * @return the value of EMDI.CFCONDGRP.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CFCONDGRP.FIELD1
     *
     * @param field1 the value for EMDI.CFCONDGRP.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField1(BigDecimal field1) {
        this.field1 = field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CFCONDGRP.FIELD2
     *
     * @return the value of EMDI.CFCONDGRP.FIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CFCONDGRP.FIELD2
     *
     * @param field2 the value for EMDI.CFCONDGRP.FIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField2(BigDecimal field2) {
        this.field2 = field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CFCONDGRP.FIELD3
     *
     * @return the value of EMDI.CFCONDGRP.FIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getField3() {
        return field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CFCONDGRP.FIELD3
     *
     * @param field3 the value for EMDI.CFCONDGRP.FIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField3(String field3) {
        this.field3 = field3 == null ? null : field3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CFCONDGRP.FIELD4
     *
     * @return the value of EMDI.CFCONDGRP.FIELD4
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getField4() {
        return field4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CFCONDGRP.FIELD4
     *
     * @param field4 the value for EMDI.CFCONDGRP.FIELD4
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField4(BigDecimal field4) {
        this.field4 = field4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CFCONDGRP.FIELD5
     *
     * @return the value of EMDI.CFCONDGRP.FIELD5
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getField5() {
        return field5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CFCONDGRP.FIELD5
     *
     * @param field5 the value for EMDI.CFCONDGRP.FIELD5
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField5(BigDecimal field5) {
        this.field5 = field5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CFCONDGRP.OPTCOUNTER
     *
     * @return the value of EMDI.CFCONDGRP.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CFCONDGRP.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.CFCONDGRP.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}