package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class CfproductsetTmp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CFPRODUCTSET_TMP.CFPRODUCTSET_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal cfproductsetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CFPRODUCTSET_TMP.CATFILTER_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal catfilterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CFPRODUCTSET_TMP.PRODUCTSET_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal productsetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CFPRODUCTSET_TMP.TYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CFPRODUCTSET_TMP.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CFPRODUCTSET_TMP.CFPRODUCTSET_ID
     *
     * @return the value of EMDI.CFPRODUCTSET_TMP.CFPRODUCTSET_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getCfproductsetId() {
        return cfproductsetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CFPRODUCTSET_TMP.CFPRODUCTSET_ID
     *
     * @param cfproductsetId the value for EMDI.CFPRODUCTSET_TMP.CFPRODUCTSET_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCfproductsetId(BigDecimal cfproductsetId) {
        this.cfproductsetId = cfproductsetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CFPRODUCTSET_TMP.CATFILTER_ID
     *
     * @return the value of EMDI.CFPRODUCTSET_TMP.CATFILTER_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getCatfilterId() {
        return catfilterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CFPRODUCTSET_TMP.CATFILTER_ID
     *
     * @param catfilterId the value for EMDI.CFPRODUCTSET_TMP.CATFILTER_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCatfilterId(BigDecimal catfilterId) {
        this.catfilterId = catfilterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CFPRODUCTSET_TMP.PRODUCTSET_ID
     *
     * @return the value of EMDI.CFPRODUCTSET_TMP.PRODUCTSET_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getProductsetId() {
        return productsetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CFPRODUCTSET_TMP.PRODUCTSET_ID
     *
     * @param productsetId the value for EMDI.CFPRODUCTSET_TMP.PRODUCTSET_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setProductsetId(BigDecimal productsetId) {
        this.productsetId = productsetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CFPRODUCTSET_TMP.TYPE
     *
     * @return the value of EMDI.CFPRODUCTSET_TMP.TYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CFPRODUCTSET_TMP.TYPE
     *
     * @param type the value for EMDI.CFPRODUCTSET_TMP.TYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setType(BigDecimal type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CFPRODUCTSET_TMP.OPTCOUNTER
     *
     * @return the value of EMDI.CFPRODUCTSET_TMP.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CFPRODUCTSET_TMP.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.CFPRODUCTSET_TMP.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}