package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class ClcdpromoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CLCDPROMO.PX_PROMOTION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal pxPromotionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CLCDPROMO.CALCODE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal calcodeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CLCDPROMO.PX_PROMOTION_ID
     *
     * @return the value of EMDI.CLCDPROMO.PX_PROMOTION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getPxPromotionId() {
        return pxPromotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CLCDPROMO.PX_PROMOTION_ID
     *
     * @param pxPromotionId the value for EMDI.CLCDPROMO.PX_PROMOTION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setPxPromotionId(BigDecimal pxPromotionId) {
        this.pxPromotionId = pxPromotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CLCDPROMO.CALCODE_ID
     *
     * @return the value of EMDI.CLCDPROMO.CALCODE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getCalcodeId() {
        return calcodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CLCDPROMO.CALCODE_ID
     *
     * @param calcodeId the value for EMDI.CLCDPROMO.CALCODE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCalcodeId(BigDecimal calcodeId) {
        this.calcodeId = calcodeId;
    }
}