package com.avn.dataload.model.emdi;

import java.math.BigDecimal;
import java.util.Date;

public class Cmdreg extends CmdregKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CMDREG.DESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CMDREG.CLASSNAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String classname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CMDREG.PROPERTIES
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String properties;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CMDREG.LASTUPDATE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private Date lastupdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CMDREG.TARGET
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String target;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CMDREG.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CMDREG.DESCRIPTION
     *
     * @return the value of EMDI.CMDREG.DESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CMDREG.DESCRIPTION
     *
     * @param description the value for EMDI.CMDREG.DESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CMDREG.CLASSNAME
     *
     * @return the value of EMDI.CMDREG.CLASSNAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CMDREG.CLASSNAME
     *
     * @param classname the value for EMDI.CMDREG.CLASSNAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CMDREG.PROPERTIES
     *
     * @return the value of EMDI.CMDREG.PROPERTIES
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getProperties() {
        return properties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CMDREG.PROPERTIES
     *
     * @param properties the value for EMDI.CMDREG.PROPERTIES
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setProperties(String properties) {
        this.properties = properties == null ? null : properties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CMDREG.LASTUPDATE
     *
     * @return the value of EMDI.CMDREG.LASTUPDATE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public Date getLastupdate() {
        return lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CMDREG.LASTUPDATE
     *
     * @param lastupdate the value for EMDI.CMDREG.LASTUPDATE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CMDREG.TARGET
     *
     * @return the value of EMDI.CMDREG.TARGET
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CMDREG.TARGET
     *
     * @param target the value for EMDI.CMDREG.TARGET
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CMDREG.OPTCOUNTER
     *
     * @return the value of EMDI.CMDREG.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CMDREG.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.CMDREG.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}