package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Cmfiledir {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CMFILEDIR.CMFILEDIR_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal cmfiledirId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CMFILEDIR.CMFILEDIR_PARENT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal cmfiledirParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CMFILEDIR.IDENTIFIER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String identifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CMFILEDIR.DISPLAYNAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String displayname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CMFILEDIR.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CMFILEDIR.CMFILEDIR_ID
     *
     * @return the value of EMDI.CMFILEDIR.CMFILEDIR_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getCmfiledirId() {
        return cmfiledirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CMFILEDIR.CMFILEDIR_ID
     *
     * @param cmfiledirId the value for EMDI.CMFILEDIR.CMFILEDIR_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCmfiledirId(BigDecimal cmfiledirId) {
        this.cmfiledirId = cmfiledirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CMFILEDIR.CMFILEDIR_PARENT
     *
     * @return the value of EMDI.CMFILEDIR.CMFILEDIR_PARENT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getCmfiledirParent() {
        return cmfiledirParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CMFILEDIR.CMFILEDIR_PARENT
     *
     * @param cmfiledirParent the value for EMDI.CMFILEDIR.CMFILEDIR_PARENT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCmfiledirParent(BigDecimal cmfiledirParent) {
        this.cmfiledirParent = cmfiledirParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CMFILEDIR.IDENTIFIER
     *
     * @return the value of EMDI.CMFILEDIR.IDENTIFIER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CMFILEDIR.IDENTIFIER
     *
     * @param identifier the value for EMDI.CMFILEDIR.IDENTIFIER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier == null ? null : identifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CMFILEDIR.DISPLAYNAME
     *
     * @return the value of EMDI.CMFILEDIR.DISPLAYNAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getDisplayname() {
        return displayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CMFILEDIR.DISPLAYNAME
     *
     * @param displayname the value for EMDI.CMFILEDIR.DISPLAYNAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setDisplayname(String displayname) {
        this.displayname = displayname == null ? null : displayname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CMFILEDIR.OPTCOUNTER
     *
     * @return the value of EMDI.CMFILEDIR.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CMFILEDIR.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.CMFILEDIR.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}