package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class CurformatKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CURFORMAT.SETCCURR
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String setccurr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CURFORMAT.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal storeentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.CURFORMAT.NUMBRUSG_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal numbrusgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CURFORMAT.SETCCURR
     *
     * @return the value of EMDI.CURFORMAT.SETCCURR
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getSetccurr() {
        return setccurr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CURFORMAT.SETCCURR
     *
     * @param setccurr the value for EMDI.CURFORMAT.SETCCURR
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSetccurr(String setccurr) {
        this.setccurr = setccurr == null ? null : setccurr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CURFORMAT.STOREENT_ID
     *
     * @return the value of EMDI.CURFORMAT.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getStoreentId() {
        return storeentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CURFORMAT.STOREENT_ID
     *
     * @param storeentId the value for EMDI.CURFORMAT.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setStoreentId(BigDecimal storeentId) {
        this.storeentId = storeentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.CURFORMAT.NUMBRUSG_ID
     *
     * @return the value of EMDI.CURFORMAT.NUMBRUSG_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getNumbrusgId() {
        return numbrusgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.CURFORMAT.NUMBRUSG_ID
     *
     * @param numbrusgId the value for EMDI.CURFORMAT.NUMBRUSG_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setNumbrusgId(BigDecimal numbrusgId) {
        this.numbrusgId = numbrusgId;
    }
}