package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Dmemspotcolldef {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.DMEMSPOTCOLLDEF.DMEMSPOTCOLLDEF_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal dmemspotcolldefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.DMEMSPOTCOLLDEF.EMSPOT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal emspotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.DMEMSPOTCOLLDEF.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal storeentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.DMEMSPOTCOLLDEF.COLLATERAL_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal collateralId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.DMEMSPOTCOLLDEF.SEQUENCE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.DMEMSPOTCOLLDEF.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.DMEMSPOTCOLLDEF.DMEMSPOTCOLLDEF_ID
     *
     * @return the value of EMDI.DMEMSPOTCOLLDEF.DMEMSPOTCOLLDEF_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getDmemspotcolldefId() {
        return dmemspotcolldefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.DMEMSPOTCOLLDEF.DMEMSPOTCOLLDEF_ID
     *
     * @param dmemspotcolldefId the value for EMDI.DMEMSPOTCOLLDEF.DMEMSPOTCOLLDEF_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setDmemspotcolldefId(BigDecimal dmemspotcolldefId) {
        this.dmemspotcolldefId = dmemspotcolldefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.DMEMSPOTCOLLDEF.EMSPOT_ID
     *
     * @return the value of EMDI.DMEMSPOTCOLLDEF.EMSPOT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getEmspotId() {
        return emspotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.DMEMSPOTCOLLDEF.EMSPOT_ID
     *
     * @param emspotId the value for EMDI.DMEMSPOTCOLLDEF.EMSPOT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setEmspotId(BigDecimal emspotId) {
        this.emspotId = emspotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.DMEMSPOTCOLLDEF.STOREENT_ID
     *
     * @return the value of EMDI.DMEMSPOTCOLLDEF.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getStoreentId() {
        return storeentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.DMEMSPOTCOLLDEF.STOREENT_ID
     *
     * @param storeentId the value for EMDI.DMEMSPOTCOLLDEF.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setStoreentId(BigDecimal storeentId) {
        this.storeentId = storeentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.DMEMSPOTCOLLDEF.COLLATERAL_ID
     *
     * @return the value of EMDI.DMEMSPOTCOLLDEF.COLLATERAL_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getCollateralId() {
        return collateralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.DMEMSPOTCOLLDEF.COLLATERAL_ID
     *
     * @param collateralId the value for EMDI.DMEMSPOTCOLLDEF.COLLATERAL_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCollateralId(BigDecimal collateralId) {
        this.collateralId = collateralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.DMEMSPOTCOLLDEF.SEQUENCE
     *
     * @return the value of EMDI.DMEMSPOTCOLLDEF.SEQUENCE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.DMEMSPOTCOLLDEF.SEQUENCE
     *
     * @param sequence the value for EMDI.DMEMSPOTCOLLDEF.SEQUENCE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSequence(BigDecimal sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.DMEMSPOTCOLLDEF.OPTCOUNTER
     *
     * @return the value of EMDI.DMEMSPOTCOLLDEF.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.DMEMSPOTCOLLDEF.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.DMEMSPOTCOLLDEF.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}