package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class DmmbrgrppznKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.DMMBRGRPPZN.MBRGRP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal mbrgrpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.DMMBRGRPPZN.PERSONALIZATIONID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String personalizationid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.DMMBRGRPPZN.MBRGRP_ID
     *
     * @return the value of EMDI.DMMBRGRPPZN.MBRGRP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getMbrgrpId() {
        return mbrgrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.DMMBRGRPPZN.MBRGRP_ID
     *
     * @param mbrgrpId the value for EMDI.DMMBRGRPPZN.MBRGRP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setMbrgrpId(BigDecimal mbrgrpId) {
        this.mbrgrpId = mbrgrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.DMMBRGRPPZN.PERSONALIZATIONID
     *
     * @return the value of EMDI.DMMBRGRPPZN.PERSONALIZATIONID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getPersonalizationid() {
        return personalizationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.DMMBRGRPPZN.PERSONALIZATIONID
     *
     * @param personalizationid the value for EMDI.DMMBRGRPPZN.PERSONALIZATIONID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setPersonalizationid(String personalizationid) {
        this.personalizationid = personalizationid == null ? null : personalizationid.trim();
    }
}