package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Dmtemplatetype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.DMTEMPLATETYPE.DMTEMPLATETYPE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal dmtemplatetypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.DMTEMPLATETYPE.TYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.DMTEMPLATETYPE.DESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.DMTEMPLATETYPE.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.DMTEMPLATETYPE.DMTEMPLATETYPE_ID
     *
     * @return the value of EMDI.DMTEMPLATETYPE.DMTEMPLATETYPE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getDmtemplatetypeId() {
        return dmtemplatetypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.DMTEMPLATETYPE.DMTEMPLATETYPE_ID
     *
     * @param dmtemplatetypeId the value for EMDI.DMTEMPLATETYPE.DMTEMPLATETYPE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setDmtemplatetypeId(BigDecimal dmtemplatetypeId) {
        this.dmtemplatetypeId = dmtemplatetypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.DMTEMPLATETYPE.TYPE
     *
     * @return the value of EMDI.DMTEMPLATETYPE.TYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.DMTEMPLATETYPE.TYPE
     *
     * @param type the value for EMDI.DMTEMPLATETYPE.TYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.DMTEMPLATETYPE.DESCRIPTION
     *
     * @return the value of EMDI.DMTEMPLATETYPE.DESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.DMTEMPLATETYPE.DESCRIPTION
     *
     * @param description the value for EMDI.DMTEMPLATETYPE.DESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.DMTEMPLATETYPE.OPTCOUNTER
     *
     * @return the value of EMDI.DMTEMPLATETYPE.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.DMTEMPLATETYPE.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.DMTEMPLATETYPE.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}