package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class DmuserbhvrKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.DMUSERBHVR.PERSONALIZATIONID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String personalizationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.DMUSERBHVR.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal storeentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.DMUSERBHVR.PERSONALIZATIONID
     *
     * @return the value of EMDI.DMUSERBHVR.PERSONALIZATIONID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getPersonalizationid() {
        return personalizationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.DMUSERBHVR.PERSONALIZATIONID
     *
     * @param personalizationid the value for EMDI.DMUSERBHVR.PERSONALIZATIONID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setPersonalizationid(String personalizationid) {
        this.personalizationid = personalizationid == null ? null : personalizationid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.DMUSERBHVR.STOREENT_ID
     *
     * @return the value of EMDI.DMUSERBHVR.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getStoreentId() {
        return storeentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.DMUSERBHVR.STOREENT_ID
     *
     * @param storeentId the value for EMDI.DMUSERBHVR.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setStoreentId(BigDecimal storeentId) {
        this.storeentId = storeentId;
    }
}