package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class FlinstanceKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.FLINSTANCE.FLOWTYPE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal flowtypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.FLINSTANCE.ENTITY_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal entityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.FLINSTANCE.FLOWTYPE_ID
     *
     * @return the value of EMDI.FLINSTANCE.FLOWTYPE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getFlowtypeId() {
        return flowtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.FLINSTANCE.FLOWTYPE_ID
     *
     * @param flowtypeId the value for EMDI.FLINSTANCE.FLOWTYPE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setFlowtypeId(BigDecimal flowtypeId) {
        this.flowtypeId = flowtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.FLINSTANCE.ENTITY_ID
     *
     * @return the value of EMDI.FLINSTANCE.ENTITY_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.FLINSTANCE.ENTITY_ID
     *
     * @param entityId the value for EMDI.FLINSTANCE.ENTITY_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setEntityId(BigDecimal entityId) {
        this.entityId = entityId;
    }
}