package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Flstaterel extends FlstaterelKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.FLSTATEREL.ENTRYACTNINTERFACE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String entryactninterface;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.FLSTATEREL.EXITACTNINTERFACE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String exitactninterface;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.FLSTATEREL.RESPONSEVIEWNAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String responseviewname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.FLSTATEREL.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.FLSTATEREL.ENTRYACTNINTERFACE
     *
     * @return the value of EMDI.FLSTATEREL.ENTRYACTNINTERFACE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getEntryactninterface() {
        return entryactninterface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.FLSTATEREL.ENTRYACTNINTERFACE
     *
     * @param entryactninterface the value for EMDI.FLSTATEREL.ENTRYACTNINTERFACE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setEntryactninterface(String entryactninterface) {
        this.entryactninterface = entryactninterface == null ? null : entryactninterface.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.FLSTATEREL.EXITACTNINTERFACE
     *
     * @return the value of EMDI.FLSTATEREL.EXITACTNINTERFACE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getExitactninterface() {
        return exitactninterface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.FLSTATEREL.EXITACTNINTERFACE
     *
     * @param exitactninterface the value for EMDI.FLSTATEREL.EXITACTNINTERFACE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setExitactninterface(String exitactninterface) {
        this.exitactninterface = exitactninterface == null ? null : exitactninterface.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.FLSTATEREL.RESPONSEVIEWNAME
     *
     * @return the value of EMDI.FLSTATEREL.RESPONSEVIEWNAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getResponseviewname() {
        return responseviewname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.FLSTATEREL.RESPONSEVIEWNAME
     *
     * @param responseviewname the value for EMDI.FLSTATEREL.RESPONSEVIEWNAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setResponseviewname(String responseviewname) {
        this.responseviewname = responseviewname == null ? null : responseviewname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.FLSTATEREL.OPTCOUNTER
     *
     * @return the value of EMDI.FLSTATEREL.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.FLSTATEREL.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.FLSTATEREL.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}