package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Inventory extends InventoryKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.INVENTORY.QUANTITY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.INVENTORY.QUANTITYMEASURE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String quantitymeasure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.INVENTORY.INVENTORYFLAGS
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal inventoryflags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.INVENTORY.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.INVENTORY.QUANTITY
     *
     * @return the value of EMDI.INVENTORY.QUANTITY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.INVENTORY.QUANTITY
     *
     * @param quantity the value for EMDI.INVENTORY.QUANTITY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.INVENTORY.QUANTITYMEASURE
     *
     * @return the value of EMDI.INVENTORY.QUANTITYMEASURE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getQuantitymeasure() {
        return quantitymeasure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.INVENTORY.QUANTITYMEASURE
     *
     * @param quantitymeasure the value for EMDI.INVENTORY.QUANTITYMEASURE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setQuantitymeasure(String quantitymeasure) {
        this.quantitymeasure = quantitymeasure == null ? null : quantitymeasure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.INVENTORY.INVENTORYFLAGS
     *
     * @return the value of EMDI.INVENTORY.INVENTORYFLAGS
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getInventoryflags() {
        return inventoryflags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.INVENTORY.INVENTORYFLAGS
     *
     * @param inventoryflags the value for EMDI.INVENTORY.INVENTORYFLAGS
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setInventoryflags(BigDecimal inventoryflags) {
        this.inventoryflags = inventoryflags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.INVENTORY.OPTCOUNTER
     *
     * @return the value of EMDI.INVENTORY.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.INVENTORY.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.INVENTORY.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}