package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class LangpairKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.LANGPAIR.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal storeentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.LANGPAIR.LANGUAGE_ID_ALT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal languageIdAlt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.LANGPAIR.LANGUAGE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal languageId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.LANGPAIR.STOREENT_ID
     *
     * @return the value of EMDI.LANGPAIR.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getStoreentId() {
        return storeentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.LANGPAIR.STOREENT_ID
     *
     * @param storeentId the value for EMDI.LANGPAIR.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setStoreentId(BigDecimal storeentId) {
        this.storeentId = storeentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.LANGPAIR.LANGUAGE_ID_ALT
     *
     * @return the value of EMDI.LANGPAIR.LANGUAGE_ID_ALT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getLanguageIdAlt() {
        return languageIdAlt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.LANGPAIR.LANGUAGE_ID_ALT
     *
     * @param languageIdAlt the value for EMDI.LANGPAIR.LANGUAGE_ID_ALT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setLanguageIdAlt(BigDecimal languageIdAlt) {
        this.languageIdAlt = languageIdAlt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.LANGPAIR.LANGUAGE_ID
     *
     * @return the value of EMDI.LANGPAIR.LANGUAGE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getLanguageId() {
        return languageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.LANGPAIR.LANGUAGE_ID
     *
     * @param languageId the value for EMDI.LANGPAIR.LANGUAGE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setLanguageId(BigDecimal languageId) {
        this.languageId = languageId;
    }
}