package com.avn.dataload.model.emdi;

import java.math.BigDecimal;
import java.util.Date;

public class Mbrgrp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.MBRGRP.MBRGRP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal mbrgrpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.MBRGRP.OWNER_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.MBRGRP.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String field1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.MBRGRP.DESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.MBRGRP.FIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String field2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.MBRGRP.DN
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String dn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.MBRGRP.MBRGRPNAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String mbrgrpname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.MBRGRP.FIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String field3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.MBRGRP.OID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.MBRGRP.LASTUPDATE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private Date lastupdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.MBRGRP.LASTUPDATEDBY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String lastupdatedby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.MBRGRP.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.MBRGRP.MBRGRP_ID
     *
     * @return the value of EMDI.MBRGRP.MBRGRP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getMbrgrpId() {
        return mbrgrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.MBRGRP.MBRGRP_ID
     *
     * @param mbrgrpId the value for EMDI.MBRGRP.MBRGRP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setMbrgrpId(BigDecimal mbrgrpId) {
        this.mbrgrpId = mbrgrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.MBRGRP.OWNER_ID
     *
     * @return the value of EMDI.MBRGRP.OWNER_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.MBRGRP.OWNER_ID
     *
     * @param ownerId the value for EMDI.MBRGRP.OWNER_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOwnerId(BigDecimal ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.MBRGRP.FIELD1
     *
     * @return the value of EMDI.MBRGRP.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.MBRGRP.FIELD1
     *
     * @param field1 the value for EMDI.MBRGRP.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField1(String field1) {
        this.field1 = field1 == null ? null : field1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.MBRGRP.DESCRIPTION
     *
     * @return the value of EMDI.MBRGRP.DESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.MBRGRP.DESCRIPTION
     *
     * @param description the value for EMDI.MBRGRP.DESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.MBRGRP.FIELD2
     *
     * @return the value of EMDI.MBRGRP.FIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.MBRGRP.FIELD2
     *
     * @param field2 the value for EMDI.MBRGRP.FIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField2(String field2) {
        this.field2 = field2 == null ? null : field2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.MBRGRP.DN
     *
     * @return the value of EMDI.MBRGRP.DN
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getDn() {
        return dn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.MBRGRP.DN
     *
     * @param dn the value for EMDI.MBRGRP.DN
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setDn(String dn) {
        this.dn = dn == null ? null : dn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.MBRGRP.MBRGRPNAME
     *
     * @return the value of EMDI.MBRGRP.MBRGRPNAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getMbrgrpname() {
        return mbrgrpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.MBRGRP.MBRGRPNAME
     *
     * @param mbrgrpname the value for EMDI.MBRGRP.MBRGRPNAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setMbrgrpname(String mbrgrpname) {
        this.mbrgrpname = mbrgrpname == null ? null : mbrgrpname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.MBRGRP.FIELD3
     *
     * @return the value of EMDI.MBRGRP.FIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getField3() {
        return field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.MBRGRP.FIELD3
     *
     * @param field3 the value for EMDI.MBRGRP.FIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField3(String field3) {
        this.field3 = field3 == null ? null : field3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.MBRGRP.OID
     *
     * @return the value of EMDI.MBRGRP.OID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.MBRGRP.OID
     *
     * @param oid the value for EMDI.MBRGRP.OID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.MBRGRP.LASTUPDATE
     *
     * @return the value of EMDI.MBRGRP.LASTUPDATE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public Date getLastupdate() {
        return lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.MBRGRP.LASTUPDATE
     *
     * @param lastupdate the value for EMDI.MBRGRP.LASTUPDATE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.MBRGRP.LASTUPDATEDBY
     *
     * @return the value of EMDI.MBRGRP.LASTUPDATEDBY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getLastupdatedby() {
        return lastupdatedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.MBRGRP.LASTUPDATEDBY
     *
     * @param lastupdatedby the value for EMDI.MBRGRP.LASTUPDATEDBY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setLastupdatedby(String lastupdatedby) {
        this.lastupdatedby = lastupdatedby == null ? null : lastupdatedby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.MBRGRP.OPTCOUNTER
     *
     * @return the value of EMDI.MBRGRP.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.MBRGRP.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.MBRGRP.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}