package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Mbrgrpcond {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.MBRGRPCOND.MBRGRP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal mbrgrpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.MBRGRPCOND.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String field1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.MBRGRPCOND.FIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String field2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.MBRGRPCOND.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.MBRGRPCOND.CONDITIONS
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String conditions;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.MBRGRPCOND.MBRGRP_ID
     *
     * @return the value of EMDI.MBRGRPCOND.MBRGRP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getMbrgrpId() {
        return mbrgrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.MBRGRPCOND.MBRGRP_ID
     *
     * @param mbrgrpId the value for EMDI.MBRGRPCOND.MBRGRP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setMbrgrpId(BigDecimal mbrgrpId) {
        this.mbrgrpId = mbrgrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.MBRGRPCOND.FIELD1
     *
     * @return the value of EMDI.MBRGRPCOND.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.MBRGRPCOND.FIELD1
     *
     * @param field1 the value for EMDI.MBRGRPCOND.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField1(String field1) {
        this.field1 = field1 == null ? null : field1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.MBRGRPCOND.FIELD2
     *
     * @return the value of EMDI.MBRGRPCOND.FIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.MBRGRPCOND.FIELD2
     *
     * @param field2 the value for EMDI.MBRGRPCOND.FIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField2(String field2) {
        this.field2 = field2 == null ? null : field2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.MBRGRPCOND.OPTCOUNTER
     *
     * @return the value of EMDI.MBRGRPCOND.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.MBRGRPCOND.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.MBRGRPCOND.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.MBRGRPCOND.CONDITIONS
     *
     * @return the value of EMDI.MBRGRPCOND.CONDITIONS
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getConditions() {
        return conditions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.MBRGRPCOND.CONDITIONS
     *
     * @param conditions the value for EMDI.MBRGRPCOND.CONDITIONS
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setConditions(String conditions) {
        this.conditions = conditions == null ? null : conditions.trim();
    }
}