package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Ordchgrsn {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ORDCHGRSN.ORDCHGRSN_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal ordchgrsnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ORDCHGRSN.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal storeentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ORDCHGRSN.REASONCODE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String reasoncode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ORDCHGRSN.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String field1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ORDCHGRSN.FIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal field2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ORDCHGRSN.FIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal field3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ORDCHGRSN.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ORDCHGRSN.ORDCHGRSN_ID
     *
     * @return the value of EMDI.ORDCHGRSN.ORDCHGRSN_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOrdchgrsnId() {
        return ordchgrsnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ORDCHGRSN.ORDCHGRSN_ID
     *
     * @param ordchgrsnId the value for EMDI.ORDCHGRSN.ORDCHGRSN_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOrdchgrsnId(BigDecimal ordchgrsnId) {
        this.ordchgrsnId = ordchgrsnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ORDCHGRSN.STOREENT_ID
     *
     * @return the value of EMDI.ORDCHGRSN.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getStoreentId() {
        return storeentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ORDCHGRSN.STOREENT_ID
     *
     * @param storeentId the value for EMDI.ORDCHGRSN.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setStoreentId(BigDecimal storeentId) {
        this.storeentId = storeentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ORDCHGRSN.REASONCODE
     *
     * @return the value of EMDI.ORDCHGRSN.REASONCODE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getReasoncode() {
        return reasoncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ORDCHGRSN.REASONCODE
     *
     * @param reasoncode the value for EMDI.ORDCHGRSN.REASONCODE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setReasoncode(String reasoncode) {
        this.reasoncode = reasoncode == null ? null : reasoncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ORDCHGRSN.FIELD1
     *
     * @return the value of EMDI.ORDCHGRSN.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ORDCHGRSN.FIELD1
     *
     * @param field1 the value for EMDI.ORDCHGRSN.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField1(String field1) {
        this.field1 = field1 == null ? null : field1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ORDCHGRSN.FIELD2
     *
     * @return the value of EMDI.ORDCHGRSN.FIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ORDCHGRSN.FIELD2
     *
     * @param field2 the value for EMDI.ORDCHGRSN.FIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField2(BigDecimal field2) {
        this.field2 = field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ORDCHGRSN.FIELD3
     *
     * @return the value of EMDI.ORDCHGRSN.FIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getField3() {
        return field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ORDCHGRSN.FIELD3
     *
     * @param field3 the value for EMDI.ORDCHGRSN.FIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField3(BigDecimal field3) {
        this.field3 = field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ORDCHGRSN.OPTCOUNTER
     *
     * @return the value of EMDI.ORDCHGRSN.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ORDCHGRSN.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.ORDCHGRSN.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}