package com.avn.dataload.model.emdi;

import java.math.BigDecimal;
import java.util.Date;

public class Ordimeextn {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ORDIMEEXTN.ORDERITEMS_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal orderitemsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ORDIMEEXTN.REQUESTEDSHIPTIME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private Date requestedshiptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ORDIMEEXTN.SHIPASCOMPLETE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String shipascomplete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ORDIMEEXTN.COMMENTS1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String comments1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ORDIMEEXTN.COMMENTS2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String comments2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ORDIMEEXTN.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String field1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ORDIMEEXTN.FIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String field2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ORDIMEEXTN.FIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String field3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ORDIMEEXTN.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ORDIMEEXTN.ORDERITEMS_ID
     *
     * @return the value of EMDI.ORDIMEEXTN.ORDERITEMS_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOrderitemsId() {
        return orderitemsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ORDIMEEXTN.ORDERITEMS_ID
     *
     * @param orderitemsId the value for EMDI.ORDIMEEXTN.ORDERITEMS_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOrderitemsId(BigDecimal orderitemsId) {
        this.orderitemsId = orderitemsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ORDIMEEXTN.REQUESTEDSHIPTIME
     *
     * @return the value of EMDI.ORDIMEEXTN.REQUESTEDSHIPTIME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public Date getRequestedshiptime() {
        return requestedshiptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ORDIMEEXTN.REQUESTEDSHIPTIME
     *
     * @param requestedshiptime the value for EMDI.ORDIMEEXTN.REQUESTEDSHIPTIME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setRequestedshiptime(Date requestedshiptime) {
        this.requestedshiptime = requestedshiptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ORDIMEEXTN.SHIPASCOMPLETE
     *
     * @return the value of EMDI.ORDIMEEXTN.SHIPASCOMPLETE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getShipascomplete() {
        return shipascomplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ORDIMEEXTN.SHIPASCOMPLETE
     *
     * @param shipascomplete the value for EMDI.ORDIMEEXTN.SHIPASCOMPLETE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setShipascomplete(String shipascomplete) {
        this.shipascomplete = shipascomplete == null ? null : shipascomplete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ORDIMEEXTN.COMMENTS1
     *
     * @return the value of EMDI.ORDIMEEXTN.COMMENTS1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getComments1() {
        return comments1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ORDIMEEXTN.COMMENTS1
     *
     * @param comments1 the value for EMDI.ORDIMEEXTN.COMMENTS1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setComments1(String comments1) {
        this.comments1 = comments1 == null ? null : comments1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ORDIMEEXTN.COMMENTS2
     *
     * @return the value of EMDI.ORDIMEEXTN.COMMENTS2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getComments2() {
        return comments2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ORDIMEEXTN.COMMENTS2
     *
     * @param comments2 the value for EMDI.ORDIMEEXTN.COMMENTS2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setComments2(String comments2) {
        this.comments2 = comments2 == null ? null : comments2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ORDIMEEXTN.FIELD1
     *
     * @return the value of EMDI.ORDIMEEXTN.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ORDIMEEXTN.FIELD1
     *
     * @param field1 the value for EMDI.ORDIMEEXTN.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField1(String field1) {
        this.field1 = field1 == null ? null : field1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ORDIMEEXTN.FIELD2
     *
     * @return the value of EMDI.ORDIMEEXTN.FIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ORDIMEEXTN.FIELD2
     *
     * @param field2 the value for EMDI.ORDIMEEXTN.FIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField2(String field2) {
        this.field2 = field2 == null ? null : field2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ORDIMEEXTN.FIELD3
     *
     * @return the value of EMDI.ORDIMEEXTN.FIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getField3() {
        return field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ORDIMEEXTN.FIELD3
     *
     * @param field3 the value for EMDI.ORDIMEEXTN.FIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField3(String field3) {
        this.field3 = field3 == null ? null : field3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ORDIMEEXTN.OPTCOUNTER
     *
     * @return the value of EMDI.ORDIMEEXTN.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ORDIMEEXTN.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.ORDIMEEXTN.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}