package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class PartroledsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PARTROLEDS.PARTROLE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal partroleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PARTROLEDS.LANGUAGE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal languageId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PARTROLEDS.PARTROLE_ID
     *
     * @return the value of EMDI.PARTROLEDS.PARTROLE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getPartroleId() {
        return partroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PARTROLEDS.PARTROLE_ID
     *
     * @param partroleId the value for EMDI.PARTROLEDS.PARTROLE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setPartroleId(BigDecimal partroleId) {
        this.partroleId = partroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PARTROLEDS.LANGUAGE_ID
     *
     * @return the value of EMDI.PARTROLEDS.LANGUAGE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getLanguageId() {
        return languageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PARTROLEDS.LANGUAGE_ID
     *
     * @param languageId the value for EMDI.PARTROLEDS.LANGUAGE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setLanguageId(BigDecimal languageId) {
        this.languageId = languageId;
    }
}