package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Policytype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.POLICYTYPE.POLICYTYPE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String policytypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.POLICYTYPE.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.POLICYTYPE.POLICYTYPE_ID
     *
     * @return the value of EMDI.POLICYTYPE.POLICYTYPE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getPolicytypeId() {
        return policytypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.POLICYTYPE.POLICYTYPE_ID
     *
     * @param policytypeId the value for EMDI.POLICYTYPE.POLICYTYPE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setPolicytypeId(String policytypeId) {
        this.policytypeId = policytypeId == null ? null : policytypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.POLICYTYPE.OPTCOUNTER
     *
     * @return the value of EMDI.POLICYTYPE.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.POLICYTYPE.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.POLICYTYPE.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}