package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Profile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PROFILE.PROFILE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal profileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PROFILE.STORE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PROFILE.DEVICEFMT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal devicefmtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PROFILE.TRANSPORT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal transportId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PROFILE.MSGTYPE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal msgtypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PROFILE.USERSVIEW
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String usersview;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PROFILE.LOWPRIORITY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal lowpriority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PROFILE.HIGHPRIORITY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal highpriority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PROFILE.ARCHIVEMSG
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal archivemsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PROFILE.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PROFILE.PROFILE_ID
     *
     * @return the value of EMDI.PROFILE.PROFILE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PROFILE.PROFILE_ID
     *
     * @param profileId the value for EMDI.PROFILE.PROFILE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setProfileId(BigDecimal profileId) {
        this.profileId = profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PROFILE.STORE_ID
     *
     * @return the value of EMDI.PROFILE.STORE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PROFILE.STORE_ID
     *
     * @param storeId the value for EMDI.PROFILE.STORE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setStoreId(BigDecimal storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PROFILE.DEVICEFMT_ID
     *
     * @return the value of EMDI.PROFILE.DEVICEFMT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getDevicefmtId() {
        return devicefmtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PROFILE.DEVICEFMT_ID
     *
     * @param devicefmtId the value for EMDI.PROFILE.DEVICEFMT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setDevicefmtId(BigDecimal devicefmtId) {
        this.devicefmtId = devicefmtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PROFILE.TRANSPORT_ID
     *
     * @return the value of EMDI.PROFILE.TRANSPORT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getTransportId() {
        return transportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PROFILE.TRANSPORT_ID
     *
     * @param transportId the value for EMDI.PROFILE.TRANSPORT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setTransportId(BigDecimal transportId) {
        this.transportId = transportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PROFILE.MSGTYPE_ID
     *
     * @return the value of EMDI.PROFILE.MSGTYPE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getMsgtypeId() {
        return msgtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PROFILE.MSGTYPE_ID
     *
     * @param msgtypeId the value for EMDI.PROFILE.MSGTYPE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setMsgtypeId(BigDecimal msgtypeId) {
        this.msgtypeId = msgtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PROFILE.USERSVIEW
     *
     * @return the value of EMDI.PROFILE.USERSVIEW
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getUsersview() {
        return usersview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PROFILE.USERSVIEW
     *
     * @param usersview the value for EMDI.PROFILE.USERSVIEW
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setUsersview(String usersview) {
        this.usersview = usersview == null ? null : usersview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PROFILE.LOWPRIORITY
     *
     * @return the value of EMDI.PROFILE.LOWPRIORITY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getLowpriority() {
        return lowpriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PROFILE.LOWPRIORITY
     *
     * @param lowpriority the value for EMDI.PROFILE.LOWPRIORITY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setLowpriority(BigDecimal lowpriority) {
        this.lowpriority = lowpriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PROFILE.HIGHPRIORITY
     *
     * @return the value of EMDI.PROFILE.HIGHPRIORITY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getHighpriority() {
        return highpriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PROFILE.HIGHPRIORITY
     *
     * @param highpriority the value for EMDI.PROFILE.HIGHPRIORITY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setHighpriority(BigDecimal highpriority) {
        this.highpriority = highpriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PROFILE.ARCHIVEMSG
     *
     * @return the value of EMDI.PROFILE.ARCHIVEMSG
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getArchivemsg() {
        return archivemsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PROFILE.ARCHIVEMSG
     *
     * @param archivemsg the value for EMDI.PROFILE.ARCHIVEMSG
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setArchivemsg(BigDecimal archivemsg) {
        this.archivemsg = archivemsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PROFILE.OPTCOUNTER
     *
     * @return the value of EMDI.PROFILE.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PROFILE.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.PROFILE.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}