package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Pvcdevspec {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PVCDEVSPEC.SPEC_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal specId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PVCDEVSPEC.SPECNAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String specname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PVCDEVSPEC.SESSIONTYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String sessiontype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PVCDEVSPEC.MAXCONTENTLENGTH
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal maxcontentlength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PVCDEVSPEC.MAXURLLENGTH
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal maxurllength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PVCDEVSPEC.LCDWIDTH
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal lcdwidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PVCDEVSPEC.LCDHEIGHT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal lcdheight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PVCDEVSPEC.LCDCOLORS
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal lcdcolors;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PVCDEVSPEC.LCDMONOCHROME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String lcdmonochrome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PVCDEVSPEC.IMAGEFORMAT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String imageformat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PVCDEVSPEC.SOUNDFORMAT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String soundformat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PVCDEVSPEC.DOCUMENTFORMAT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String documentformat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PVCDEVSPEC.DOCUMENTVERSION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String documentversion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PVCDEVSPEC.CONTENTDIR
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String contentdir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PVCDEVSPEC.DESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PVCDEVSPEC.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PVCDEVSPEC.SPEC_ID
     *
     * @return the value of EMDI.PVCDEVSPEC.SPEC_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getSpecId() {
        return specId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PVCDEVSPEC.SPEC_ID
     *
     * @param specId the value for EMDI.PVCDEVSPEC.SPEC_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSpecId(BigDecimal specId) {
        this.specId = specId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PVCDEVSPEC.SPECNAME
     *
     * @return the value of EMDI.PVCDEVSPEC.SPECNAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getSpecname() {
        return specname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PVCDEVSPEC.SPECNAME
     *
     * @param specname the value for EMDI.PVCDEVSPEC.SPECNAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSpecname(String specname) {
        this.specname = specname == null ? null : specname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PVCDEVSPEC.SESSIONTYPE
     *
     * @return the value of EMDI.PVCDEVSPEC.SESSIONTYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getSessiontype() {
        return sessiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PVCDEVSPEC.SESSIONTYPE
     *
     * @param sessiontype the value for EMDI.PVCDEVSPEC.SESSIONTYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSessiontype(String sessiontype) {
        this.sessiontype = sessiontype == null ? null : sessiontype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PVCDEVSPEC.MAXCONTENTLENGTH
     *
     * @return the value of EMDI.PVCDEVSPEC.MAXCONTENTLENGTH
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getMaxcontentlength() {
        return maxcontentlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PVCDEVSPEC.MAXCONTENTLENGTH
     *
     * @param maxcontentlength the value for EMDI.PVCDEVSPEC.MAXCONTENTLENGTH
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setMaxcontentlength(BigDecimal maxcontentlength) {
        this.maxcontentlength = maxcontentlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PVCDEVSPEC.MAXURLLENGTH
     *
     * @return the value of EMDI.PVCDEVSPEC.MAXURLLENGTH
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getMaxurllength() {
        return maxurllength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PVCDEVSPEC.MAXURLLENGTH
     *
     * @param maxurllength the value for EMDI.PVCDEVSPEC.MAXURLLENGTH
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setMaxurllength(BigDecimal maxurllength) {
        this.maxurllength = maxurllength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PVCDEVSPEC.LCDWIDTH
     *
     * @return the value of EMDI.PVCDEVSPEC.LCDWIDTH
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getLcdwidth() {
        return lcdwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PVCDEVSPEC.LCDWIDTH
     *
     * @param lcdwidth the value for EMDI.PVCDEVSPEC.LCDWIDTH
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setLcdwidth(BigDecimal lcdwidth) {
        this.lcdwidth = lcdwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PVCDEVSPEC.LCDHEIGHT
     *
     * @return the value of EMDI.PVCDEVSPEC.LCDHEIGHT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getLcdheight() {
        return lcdheight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PVCDEVSPEC.LCDHEIGHT
     *
     * @param lcdheight the value for EMDI.PVCDEVSPEC.LCDHEIGHT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setLcdheight(BigDecimal lcdheight) {
        this.lcdheight = lcdheight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PVCDEVSPEC.LCDCOLORS
     *
     * @return the value of EMDI.PVCDEVSPEC.LCDCOLORS
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getLcdcolors() {
        return lcdcolors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PVCDEVSPEC.LCDCOLORS
     *
     * @param lcdcolors the value for EMDI.PVCDEVSPEC.LCDCOLORS
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setLcdcolors(BigDecimal lcdcolors) {
        this.lcdcolors = lcdcolors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PVCDEVSPEC.LCDMONOCHROME
     *
     * @return the value of EMDI.PVCDEVSPEC.LCDMONOCHROME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getLcdmonochrome() {
        return lcdmonochrome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PVCDEVSPEC.LCDMONOCHROME
     *
     * @param lcdmonochrome the value for EMDI.PVCDEVSPEC.LCDMONOCHROME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setLcdmonochrome(String lcdmonochrome) {
        this.lcdmonochrome = lcdmonochrome == null ? null : lcdmonochrome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PVCDEVSPEC.IMAGEFORMAT
     *
     * @return the value of EMDI.PVCDEVSPEC.IMAGEFORMAT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getImageformat() {
        return imageformat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PVCDEVSPEC.IMAGEFORMAT
     *
     * @param imageformat the value for EMDI.PVCDEVSPEC.IMAGEFORMAT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setImageformat(String imageformat) {
        this.imageformat = imageformat == null ? null : imageformat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PVCDEVSPEC.SOUNDFORMAT
     *
     * @return the value of EMDI.PVCDEVSPEC.SOUNDFORMAT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getSoundformat() {
        return soundformat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PVCDEVSPEC.SOUNDFORMAT
     *
     * @param soundformat the value for EMDI.PVCDEVSPEC.SOUNDFORMAT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSoundformat(String soundformat) {
        this.soundformat = soundformat == null ? null : soundformat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PVCDEVSPEC.DOCUMENTFORMAT
     *
     * @return the value of EMDI.PVCDEVSPEC.DOCUMENTFORMAT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getDocumentformat() {
        return documentformat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PVCDEVSPEC.DOCUMENTFORMAT
     *
     * @param documentformat the value for EMDI.PVCDEVSPEC.DOCUMENTFORMAT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setDocumentformat(String documentformat) {
        this.documentformat = documentformat == null ? null : documentformat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PVCDEVSPEC.DOCUMENTVERSION
     *
     * @return the value of EMDI.PVCDEVSPEC.DOCUMENTVERSION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getDocumentversion() {
        return documentversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PVCDEVSPEC.DOCUMENTVERSION
     *
     * @param documentversion the value for EMDI.PVCDEVSPEC.DOCUMENTVERSION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setDocumentversion(String documentversion) {
        this.documentversion = documentversion == null ? null : documentversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PVCDEVSPEC.CONTENTDIR
     *
     * @return the value of EMDI.PVCDEVSPEC.CONTENTDIR
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getContentdir() {
        return contentdir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PVCDEVSPEC.CONTENTDIR
     *
     * @param contentdir the value for EMDI.PVCDEVSPEC.CONTENTDIR
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setContentdir(String contentdir) {
        this.contentdir = contentdir == null ? null : contentdir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PVCDEVSPEC.DESCRIPTION
     *
     * @return the value of EMDI.PVCDEVSPEC.DESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PVCDEVSPEC.DESCRIPTION
     *
     * @param description the value for EMDI.PVCDEVSPEC.DESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PVCDEVSPEC.OPTCOUNTER
     *
     * @return the value of EMDI.PVCDEVSPEC.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PVCDEVSPEC.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.PVCDEVSPEC.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}