package com.avn.dataload.model.emdi;

import java.math.BigDecimal;
import java.util.Date;

public class PxCdspec {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_CDSPEC.PX_PROMOTION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal pxPromotionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_CDSPEC.CODETYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal codetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_CDSPEC.PATTERN
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String pattern;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_CDSPEC.COUNT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_CDSPEC.CODESTATUS
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal codestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_CDSPEC.TRANSFERABLE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal transferable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_CDSPEC.VALIDFROM
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private Date validfrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_CDSPEC.VALIDUNTIL
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private Date validuntil;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_CDSPEC.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_CDSPEC.PX_PROMOTION_ID
     *
     * @return the value of EMDI.PX_CDSPEC.PX_PROMOTION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getPxPromotionId() {
        return pxPromotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_CDSPEC.PX_PROMOTION_ID
     *
     * @param pxPromotionId the value for EMDI.PX_CDSPEC.PX_PROMOTION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setPxPromotionId(BigDecimal pxPromotionId) {
        this.pxPromotionId = pxPromotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_CDSPEC.CODETYPE
     *
     * @return the value of EMDI.PX_CDSPEC.CODETYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getCodetype() {
        return codetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_CDSPEC.CODETYPE
     *
     * @param codetype the value for EMDI.PX_CDSPEC.CODETYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCodetype(BigDecimal codetype) {
        this.codetype = codetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_CDSPEC.PATTERN
     *
     * @return the value of EMDI.PX_CDSPEC.PATTERN
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getPattern() {
        return pattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_CDSPEC.PATTERN
     *
     * @param pattern the value for EMDI.PX_CDSPEC.PATTERN
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setPattern(String pattern) {
        this.pattern = pattern == null ? null : pattern.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_CDSPEC.COUNT
     *
     * @return the value of EMDI.PX_CDSPEC.COUNT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_CDSPEC.COUNT
     *
     * @param count the value for EMDI.PX_CDSPEC.COUNT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCount(BigDecimal count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_CDSPEC.CODESTATUS
     *
     * @return the value of EMDI.PX_CDSPEC.CODESTATUS
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getCodestatus() {
        return codestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_CDSPEC.CODESTATUS
     *
     * @param codestatus the value for EMDI.PX_CDSPEC.CODESTATUS
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCodestatus(BigDecimal codestatus) {
        this.codestatus = codestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_CDSPEC.TRANSFERABLE
     *
     * @return the value of EMDI.PX_CDSPEC.TRANSFERABLE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getTransferable() {
        return transferable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_CDSPEC.TRANSFERABLE
     *
     * @param transferable the value for EMDI.PX_CDSPEC.TRANSFERABLE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setTransferable(BigDecimal transferable) {
        this.transferable = transferable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_CDSPEC.VALIDFROM
     *
     * @return the value of EMDI.PX_CDSPEC.VALIDFROM
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public Date getValidfrom() {
        return validfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_CDSPEC.VALIDFROM
     *
     * @param validfrom the value for EMDI.PX_CDSPEC.VALIDFROM
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setValidfrom(Date validfrom) {
        this.validfrom = validfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_CDSPEC.VALIDUNTIL
     *
     * @return the value of EMDI.PX_CDSPEC.VALIDUNTIL
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public Date getValiduntil() {
        return validuntil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_CDSPEC.VALIDUNTIL
     *
     * @param validuntil the value for EMDI.PX_CDSPEC.VALIDUNTIL
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setValiduntil(Date validuntil) {
        this.validuntil = validuntil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_CDSPEC.OPTCOUNTER
     *
     * @return the value of EMDI.PX_CDSPEC.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_CDSPEC.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.PX_CDSPEC.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}