package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class PxDescription extends PxDescriptionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_DESCRIPTION.ADMINDESC
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String admindesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_DESCRIPTION.SHORTDESC
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String shortdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_DESCRIPTION.LONGDESC
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String longdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_DESCRIPTION.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String field1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_DESCRIPTION.FIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String field2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_DESCRIPTION.FIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String field3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_DESCRIPTION.FIELD4
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String field4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_DESCRIPTION.FIELD5
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String field5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_DESCRIPTION.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_DESCRIPTION.ADMINDESC
     *
     * @return the value of EMDI.PX_DESCRIPTION.ADMINDESC
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getAdmindesc() {
        return admindesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_DESCRIPTION.ADMINDESC
     *
     * @param admindesc the value for EMDI.PX_DESCRIPTION.ADMINDESC
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setAdmindesc(String admindesc) {
        this.admindesc = admindesc == null ? null : admindesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_DESCRIPTION.SHORTDESC
     *
     * @return the value of EMDI.PX_DESCRIPTION.SHORTDESC
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getShortdesc() {
        return shortdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_DESCRIPTION.SHORTDESC
     *
     * @param shortdesc the value for EMDI.PX_DESCRIPTION.SHORTDESC
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setShortdesc(String shortdesc) {
        this.shortdesc = shortdesc == null ? null : shortdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_DESCRIPTION.LONGDESC
     *
     * @return the value of EMDI.PX_DESCRIPTION.LONGDESC
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getLongdesc() {
        return longdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_DESCRIPTION.LONGDESC
     *
     * @param longdesc the value for EMDI.PX_DESCRIPTION.LONGDESC
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setLongdesc(String longdesc) {
        this.longdesc = longdesc == null ? null : longdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_DESCRIPTION.FIELD1
     *
     * @return the value of EMDI.PX_DESCRIPTION.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_DESCRIPTION.FIELD1
     *
     * @param field1 the value for EMDI.PX_DESCRIPTION.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField1(String field1) {
        this.field1 = field1 == null ? null : field1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_DESCRIPTION.FIELD2
     *
     * @return the value of EMDI.PX_DESCRIPTION.FIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_DESCRIPTION.FIELD2
     *
     * @param field2 the value for EMDI.PX_DESCRIPTION.FIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField2(String field2) {
        this.field2 = field2 == null ? null : field2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_DESCRIPTION.FIELD3
     *
     * @return the value of EMDI.PX_DESCRIPTION.FIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getField3() {
        return field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_DESCRIPTION.FIELD3
     *
     * @param field3 the value for EMDI.PX_DESCRIPTION.FIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField3(String field3) {
        this.field3 = field3 == null ? null : field3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_DESCRIPTION.FIELD4
     *
     * @return the value of EMDI.PX_DESCRIPTION.FIELD4
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getField4() {
        return field4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_DESCRIPTION.FIELD4
     *
     * @param field4 the value for EMDI.PX_DESCRIPTION.FIELD4
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField4(String field4) {
        this.field4 = field4 == null ? null : field4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_DESCRIPTION.FIELD5
     *
     * @return the value of EMDI.PX_DESCRIPTION.FIELD5
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getField5() {
        return field5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_DESCRIPTION.FIELD5
     *
     * @param field5 the value for EMDI.PX_DESCRIPTION.FIELD5
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField5(String field5) {
        this.field5 = field5 == null ? null : field5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_DESCRIPTION.OPTCOUNTER
     *
     * @return the value of EMDI.PX_DESCRIPTION.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_DESCRIPTION.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.PX_DESCRIPTION.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}