package com.avn.dataload.model.emdi;

import java.math.BigDecimal;
import java.util.Date;

public class PxPromotion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.PX_PROMOTION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal pxPromotionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.PRIORITY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.STATUS
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.EXCLSVE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal exclsve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.TYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.PERORDLMT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal perordlmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.PERSHOPPERLMT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal pershopperlmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.TOTALLMT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal totallmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.RSV_INT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal rsvInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.PX_GROUP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal pxGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.CAMPAIGN_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal campaignId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal storeentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.VERSION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.REVISION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal revision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.EFFECTIVE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal effective;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.TRANSFER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal transfer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.CDREQUIRED
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal cdrequired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.EXPIRE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal expire;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.LASTUPDATEBY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal lastupdateby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.LASTUPDATE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private Date lastupdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.STARTDATE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private Date startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.ENDDATE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private Date enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.RSV_TIME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private Date rsvTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.RSV_REAL
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal rsvReal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.TGTSALES
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal tgtsales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.NAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.CODE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.RSV_VCH
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String rsvVch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.PX_PROMOTION.XMLPARAM
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String xmlparam;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.PX_PROMOTION_ID
     *
     * @return the value of EMDI.PX_PROMOTION.PX_PROMOTION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getPxPromotionId() {
        return pxPromotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.PX_PROMOTION_ID
     *
     * @param pxPromotionId the value for EMDI.PX_PROMOTION.PX_PROMOTION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setPxPromotionId(BigDecimal pxPromotionId) {
        this.pxPromotionId = pxPromotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.PRIORITY
     *
     * @return the value of EMDI.PX_PROMOTION.PRIORITY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.PRIORITY
     *
     * @param priority the value for EMDI.PX_PROMOTION.PRIORITY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setPriority(BigDecimal priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.STATUS
     *
     * @return the value of EMDI.PX_PROMOTION.STATUS
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.STATUS
     *
     * @param status the value for EMDI.PX_PROMOTION.STATUS
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setStatus(BigDecimal status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.EXCLSVE
     *
     * @return the value of EMDI.PX_PROMOTION.EXCLSVE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getExclsve() {
        return exclsve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.EXCLSVE
     *
     * @param exclsve the value for EMDI.PX_PROMOTION.EXCLSVE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setExclsve(BigDecimal exclsve) {
        this.exclsve = exclsve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.TYPE
     *
     * @return the value of EMDI.PX_PROMOTION.TYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.TYPE
     *
     * @param type the value for EMDI.PX_PROMOTION.TYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setType(BigDecimal type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.PERORDLMT
     *
     * @return the value of EMDI.PX_PROMOTION.PERORDLMT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getPerordlmt() {
        return perordlmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.PERORDLMT
     *
     * @param perordlmt the value for EMDI.PX_PROMOTION.PERORDLMT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setPerordlmt(BigDecimal perordlmt) {
        this.perordlmt = perordlmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.PERSHOPPERLMT
     *
     * @return the value of EMDI.PX_PROMOTION.PERSHOPPERLMT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getPershopperlmt() {
        return pershopperlmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.PERSHOPPERLMT
     *
     * @param pershopperlmt the value for EMDI.PX_PROMOTION.PERSHOPPERLMT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setPershopperlmt(BigDecimal pershopperlmt) {
        this.pershopperlmt = pershopperlmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.TOTALLMT
     *
     * @return the value of EMDI.PX_PROMOTION.TOTALLMT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getTotallmt() {
        return totallmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.TOTALLMT
     *
     * @param totallmt the value for EMDI.PX_PROMOTION.TOTALLMT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setTotallmt(BigDecimal totallmt) {
        this.totallmt = totallmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.RSV_INT
     *
     * @return the value of EMDI.PX_PROMOTION.RSV_INT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getRsvInt() {
        return rsvInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.RSV_INT
     *
     * @param rsvInt the value for EMDI.PX_PROMOTION.RSV_INT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setRsvInt(BigDecimal rsvInt) {
        this.rsvInt = rsvInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.PX_GROUP_ID
     *
     * @return the value of EMDI.PX_PROMOTION.PX_GROUP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getPxGroupId() {
        return pxGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.PX_GROUP_ID
     *
     * @param pxGroupId the value for EMDI.PX_PROMOTION.PX_GROUP_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setPxGroupId(BigDecimal pxGroupId) {
        this.pxGroupId = pxGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.CAMPAIGN_ID
     *
     * @return the value of EMDI.PX_PROMOTION.CAMPAIGN_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getCampaignId() {
        return campaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.CAMPAIGN_ID
     *
     * @param campaignId the value for EMDI.PX_PROMOTION.CAMPAIGN_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCampaignId(BigDecimal campaignId) {
        this.campaignId = campaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.STOREENT_ID
     *
     * @return the value of EMDI.PX_PROMOTION.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getStoreentId() {
        return storeentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.STOREENT_ID
     *
     * @param storeentId the value for EMDI.PX_PROMOTION.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setStoreentId(BigDecimal storeentId) {
        this.storeentId = storeentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.VERSION
     *
     * @return the value of EMDI.PX_PROMOTION.VERSION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.VERSION
     *
     * @param version the value for EMDI.PX_PROMOTION.VERSION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setVersion(BigDecimal version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.REVISION
     *
     * @return the value of EMDI.PX_PROMOTION.REVISION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getRevision() {
        return revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.REVISION
     *
     * @param revision the value for EMDI.PX_PROMOTION.REVISION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setRevision(BigDecimal revision) {
        this.revision = revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.EFFECTIVE
     *
     * @return the value of EMDI.PX_PROMOTION.EFFECTIVE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getEffective() {
        return effective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.EFFECTIVE
     *
     * @param effective the value for EMDI.PX_PROMOTION.EFFECTIVE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setEffective(BigDecimal effective) {
        this.effective = effective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.TRANSFER
     *
     * @return the value of EMDI.PX_PROMOTION.TRANSFER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getTransfer() {
        return transfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.TRANSFER
     *
     * @param transfer the value for EMDI.PX_PROMOTION.TRANSFER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setTransfer(BigDecimal transfer) {
        this.transfer = transfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.CDREQUIRED
     *
     * @return the value of EMDI.PX_PROMOTION.CDREQUIRED
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getCdrequired() {
        return cdrequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.CDREQUIRED
     *
     * @param cdrequired the value for EMDI.PX_PROMOTION.CDREQUIRED
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCdrequired(BigDecimal cdrequired) {
        this.cdrequired = cdrequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.EXPIRE
     *
     * @return the value of EMDI.PX_PROMOTION.EXPIRE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getExpire() {
        return expire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.EXPIRE
     *
     * @param expire the value for EMDI.PX_PROMOTION.EXPIRE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setExpire(BigDecimal expire) {
        this.expire = expire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.LASTUPDATEBY
     *
     * @return the value of EMDI.PX_PROMOTION.LASTUPDATEBY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getLastupdateby() {
        return lastupdateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.LASTUPDATEBY
     *
     * @param lastupdateby the value for EMDI.PX_PROMOTION.LASTUPDATEBY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setLastupdateby(BigDecimal lastupdateby) {
        this.lastupdateby = lastupdateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.LASTUPDATE
     *
     * @return the value of EMDI.PX_PROMOTION.LASTUPDATE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public Date getLastupdate() {
        return lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.LASTUPDATE
     *
     * @param lastupdate the value for EMDI.PX_PROMOTION.LASTUPDATE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.STARTDATE
     *
     * @return the value of EMDI.PX_PROMOTION.STARTDATE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.STARTDATE
     *
     * @param startdate the value for EMDI.PX_PROMOTION.STARTDATE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.ENDDATE
     *
     * @return the value of EMDI.PX_PROMOTION.ENDDATE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.ENDDATE
     *
     * @param enddate the value for EMDI.PX_PROMOTION.ENDDATE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.RSV_TIME
     *
     * @return the value of EMDI.PX_PROMOTION.RSV_TIME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public Date getRsvTime() {
        return rsvTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.RSV_TIME
     *
     * @param rsvTime the value for EMDI.PX_PROMOTION.RSV_TIME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setRsvTime(Date rsvTime) {
        this.rsvTime = rsvTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.RSV_REAL
     *
     * @return the value of EMDI.PX_PROMOTION.RSV_REAL
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getRsvReal() {
        return rsvReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.RSV_REAL
     *
     * @param rsvReal the value for EMDI.PX_PROMOTION.RSV_REAL
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setRsvReal(BigDecimal rsvReal) {
        this.rsvReal = rsvReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.TGTSALES
     *
     * @return the value of EMDI.PX_PROMOTION.TGTSALES
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getTgtsales() {
        return tgtsales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.TGTSALES
     *
     * @param tgtsales the value for EMDI.PX_PROMOTION.TGTSALES
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setTgtsales(BigDecimal tgtsales) {
        this.tgtsales = tgtsales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.NAME
     *
     * @return the value of EMDI.PX_PROMOTION.NAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.NAME
     *
     * @param name the value for EMDI.PX_PROMOTION.NAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.CODE
     *
     * @return the value of EMDI.PX_PROMOTION.CODE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.CODE
     *
     * @param code the value for EMDI.PX_PROMOTION.CODE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.RSV_VCH
     *
     * @return the value of EMDI.PX_PROMOTION.RSV_VCH
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getRsvVch() {
        return rsvVch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.RSV_VCH
     *
     * @param rsvVch the value for EMDI.PX_PROMOTION.RSV_VCH
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setRsvVch(String rsvVch) {
        this.rsvVch = rsvVch == null ? null : rsvVch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.OPTCOUNTER
     *
     * @return the value of EMDI.PX_PROMOTION.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.PX_PROMOTION.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.PX_PROMOTION.XMLPARAM
     *
     * @return the value of EMDI.PX_PROMOTION.XMLPARAM
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getXmlparam() {
        return xmlparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.PX_PROMOTION.XMLPARAM
     *
     * @param xmlparam the value for EMDI.PX_PROMOTION.XMLPARAM
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setXmlparam(String xmlparam) {
        this.xmlparam = xmlparam == null ? null : xmlparam.trim();
    }
}