package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Refkeys {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.REFKEYS.TABLENAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String tablename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.REFKEYS.FKTABLE_NAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String fktableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.REFKEYS.FKCOLUMN_NAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String fkcolumnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.REFKEYS.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.REFKEYS.TABLENAME
     *
     * @return the value of EMDI.REFKEYS.TABLENAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getTablename() {
        return tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.REFKEYS.TABLENAME
     *
     * @param tablename the value for EMDI.REFKEYS.TABLENAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setTablename(String tablename) {
        this.tablename = tablename == null ? null : tablename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.REFKEYS.FKTABLE_NAME
     *
     * @return the value of EMDI.REFKEYS.FKTABLE_NAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getFktableName() {
        return fktableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.REFKEYS.FKTABLE_NAME
     *
     * @param fktableName the value for EMDI.REFKEYS.FKTABLE_NAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setFktableName(String fktableName) {
        this.fktableName = fktableName == null ? null : fktableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.REFKEYS.FKCOLUMN_NAME
     *
     * @return the value of EMDI.REFKEYS.FKCOLUMN_NAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getFkcolumnName() {
        return fkcolumnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.REFKEYS.FKCOLUMN_NAME
     *
     * @param fkcolumnName the value for EMDI.REFKEYS.FKCOLUMN_NAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setFkcolumnName(String fkcolumnName) {
        this.fkcolumnName = fkcolumnName == null ? null : fkcolumnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.REFKEYS.OPTCOUNTER
     *
     * @return the value of EMDI.REFKEYS.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.REFKEYS.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.REFKEYS.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}