package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Roleasnprm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ROLEASNPRM.ROLEASNPRM_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal roleasnprmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ROLEASNPRM.ASSIGNING_ROLE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal assigningRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ROLEASNPRM.ORGENTITY_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal orgentityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ROLEASNPRM.ASSIGNABLE_ROLE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal assignableRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.ROLEASNPRM.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ROLEASNPRM.ROLEASNPRM_ID
     *
     * @return the value of EMDI.ROLEASNPRM.ROLEASNPRM_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getRoleasnprmId() {
        return roleasnprmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ROLEASNPRM.ROLEASNPRM_ID
     *
     * @param roleasnprmId the value for EMDI.ROLEASNPRM.ROLEASNPRM_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setRoleasnprmId(BigDecimal roleasnprmId) {
        this.roleasnprmId = roleasnprmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ROLEASNPRM.ASSIGNING_ROLE_ID
     *
     * @return the value of EMDI.ROLEASNPRM.ASSIGNING_ROLE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getAssigningRoleId() {
        return assigningRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ROLEASNPRM.ASSIGNING_ROLE_ID
     *
     * @param assigningRoleId the value for EMDI.ROLEASNPRM.ASSIGNING_ROLE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setAssigningRoleId(BigDecimal assigningRoleId) {
        this.assigningRoleId = assigningRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ROLEASNPRM.ORGENTITY_ID
     *
     * @return the value of EMDI.ROLEASNPRM.ORGENTITY_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOrgentityId() {
        return orgentityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ROLEASNPRM.ORGENTITY_ID
     *
     * @param orgentityId the value for EMDI.ROLEASNPRM.ORGENTITY_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOrgentityId(BigDecimal orgentityId) {
        this.orgentityId = orgentityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ROLEASNPRM.ASSIGNABLE_ROLE_ID
     *
     * @return the value of EMDI.ROLEASNPRM.ASSIGNABLE_ROLE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getAssignableRoleId() {
        return assignableRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ROLEASNPRM.ASSIGNABLE_ROLE_ID
     *
     * @param assignableRoleId the value for EMDI.ROLEASNPRM.ASSIGNABLE_ROLE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setAssignableRoleId(BigDecimal assignableRoleId) {
        this.assignableRoleId = assignableRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.ROLEASNPRM.OPTCOUNTER
     *
     * @return the value of EMDI.ROLEASNPRM.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.ROLEASNPRM.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.ROLEASNPRM.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}