package com.avn.dataload.model.emdi;

import java.math.BigDecimal;
import java.util.Date;

public class Schconfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SCHCONFIG.SCCJOBREFNUM
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal sccjobrefnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SCHCONFIG.SCCHOST
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String scchost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SCHCONFIG.MEMBER_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SCHCONFIG.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal storeentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SCHCONFIG.SCCRECDELAY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal sccrecdelay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SCHCONFIG.SCCRECATT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal sccrecatt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SCHCONFIG.SCCPATHINFO
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String sccpathinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SCHCONFIG.SCCQUERY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String sccquery;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SCHCONFIG.SCCSTART
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private Date sccstart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SCHCONFIG.SCCINTERVAL
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal sccinterval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SCHCONFIG.SCCPRIORITY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal sccpriority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SCHCONFIG.SCCSEQUENCE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal sccsequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SCHCONFIG.SCCACTIVE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String sccactive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SCHCONFIG.SCCAPPTYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String sccapptype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SCHCONFIG.INTERFACENAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String interfacename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SCHCONFIG.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SCHCONFIG.SCCJOBREFNUM
     *
     * @return the value of EMDI.SCHCONFIG.SCCJOBREFNUM
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getSccjobrefnum() {
        return sccjobrefnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SCHCONFIG.SCCJOBREFNUM
     *
     * @param sccjobrefnum the value for EMDI.SCHCONFIG.SCCJOBREFNUM
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSccjobrefnum(BigDecimal sccjobrefnum) {
        this.sccjobrefnum = sccjobrefnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SCHCONFIG.SCCHOST
     *
     * @return the value of EMDI.SCHCONFIG.SCCHOST
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getScchost() {
        return scchost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SCHCONFIG.SCCHOST
     *
     * @param scchost the value for EMDI.SCHCONFIG.SCCHOST
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setScchost(String scchost) {
        this.scchost = scchost == null ? null : scchost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SCHCONFIG.MEMBER_ID
     *
     * @return the value of EMDI.SCHCONFIG.MEMBER_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SCHCONFIG.MEMBER_ID
     *
     * @param memberId the value for EMDI.SCHCONFIG.MEMBER_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setMemberId(BigDecimal memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SCHCONFIG.STOREENT_ID
     *
     * @return the value of EMDI.SCHCONFIG.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getStoreentId() {
        return storeentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SCHCONFIG.STOREENT_ID
     *
     * @param storeentId the value for EMDI.SCHCONFIG.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setStoreentId(BigDecimal storeentId) {
        this.storeentId = storeentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SCHCONFIG.SCCRECDELAY
     *
     * @return the value of EMDI.SCHCONFIG.SCCRECDELAY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getSccrecdelay() {
        return sccrecdelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SCHCONFIG.SCCRECDELAY
     *
     * @param sccrecdelay the value for EMDI.SCHCONFIG.SCCRECDELAY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSccrecdelay(BigDecimal sccrecdelay) {
        this.sccrecdelay = sccrecdelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SCHCONFIG.SCCRECATT
     *
     * @return the value of EMDI.SCHCONFIG.SCCRECATT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getSccrecatt() {
        return sccrecatt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SCHCONFIG.SCCRECATT
     *
     * @param sccrecatt the value for EMDI.SCHCONFIG.SCCRECATT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSccrecatt(BigDecimal sccrecatt) {
        this.sccrecatt = sccrecatt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SCHCONFIG.SCCPATHINFO
     *
     * @return the value of EMDI.SCHCONFIG.SCCPATHINFO
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getSccpathinfo() {
        return sccpathinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SCHCONFIG.SCCPATHINFO
     *
     * @param sccpathinfo the value for EMDI.SCHCONFIG.SCCPATHINFO
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSccpathinfo(String sccpathinfo) {
        this.sccpathinfo = sccpathinfo == null ? null : sccpathinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SCHCONFIG.SCCQUERY
     *
     * @return the value of EMDI.SCHCONFIG.SCCQUERY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getSccquery() {
        return sccquery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SCHCONFIG.SCCQUERY
     *
     * @param sccquery the value for EMDI.SCHCONFIG.SCCQUERY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSccquery(String sccquery) {
        this.sccquery = sccquery == null ? null : sccquery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SCHCONFIG.SCCSTART
     *
     * @return the value of EMDI.SCHCONFIG.SCCSTART
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public Date getSccstart() {
        return sccstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SCHCONFIG.SCCSTART
     *
     * @param sccstart the value for EMDI.SCHCONFIG.SCCSTART
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSccstart(Date sccstart) {
        this.sccstart = sccstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SCHCONFIG.SCCINTERVAL
     *
     * @return the value of EMDI.SCHCONFIG.SCCINTERVAL
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getSccinterval() {
        return sccinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SCHCONFIG.SCCINTERVAL
     *
     * @param sccinterval the value for EMDI.SCHCONFIG.SCCINTERVAL
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSccinterval(BigDecimal sccinterval) {
        this.sccinterval = sccinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SCHCONFIG.SCCPRIORITY
     *
     * @return the value of EMDI.SCHCONFIG.SCCPRIORITY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getSccpriority() {
        return sccpriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SCHCONFIG.SCCPRIORITY
     *
     * @param sccpriority the value for EMDI.SCHCONFIG.SCCPRIORITY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSccpriority(BigDecimal sccpriority) {
        this.sccpriority = sccpriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SCHCONFIG.SCCSEQUENCE
     *
     * @return the value of EMDI.SCHCONFIG.SCCSEQUENCE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getSccsequence() {
        return sccsequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SCHCONFIG.SCCSEQUENCE
     *
     * @param sccsequence the value for EMDI.SCHCONFIG.SCCSEQUENCE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSccsequence(BigDecimal sccsequence) {
        this.sccsequence = sccsequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SCHCONFIG.SCCACTIVE
     *
     * @return the value of EMDI.SCHCONFIG.SCCACTIVE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getSccactive() {
        return sccactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SCHCONFIG.SCCACTIVE
     *
     * @param sccactive the value for EMDI.SCHCONFIG.SCCACTIVE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSccactive(String sccactive) {
        this.sccactive = sccactive == null ? null : sccactive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SCHCONFIG.SCCAPPTYPE
     *
     * @return the value of EMDI.SCHCONFIG.SCCAPPTYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getSccapptype() {
        return sccapptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SCHCONFIG.SCCAPPTYPE
     *
     * @param sccapptype the value for EMDI.SCHCONFIG.SCCAPPTYPE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSccapptype(String sccapptype) {
        this.sccapptype = sccapptype == null ? null : sccapptype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SCHCONFIG.INTERFACENAME
     *
     * @return the value of EMDI.SCHCONFIG.INTERFACENAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getInterfacename() {
        return interfacename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SCHCONFIG.INTERFACENAME
     *
     * @param interfacename the value for EMDI.SCHCONFIG.INTERFACENAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setInterfacename(String interfacename) {
        this.interfacename = interfacename == null ? null : interfacename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SCHCONFIG.OPTCOUNTER
     *
     * @return the value of EMDI.SCHCONFIG.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SCHCONFIG.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.SCHCONFIG.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}