package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Seopagedefsubparam extends SeopagedefsubparamKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SEOPAGEDEFSUBPARAM.ADMINDESC
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String admindesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SEOPAGEDEFSUBPARAM.CLASSNAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String classname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SEOPAGEDEFSUBPARAM.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SEOPAGEDEFSUBPARAM.ADMINDESC
     *
     * @return the value of EMDI.SEOPAGEDEFSUBPARAM.ADMINDESC
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getAdmindesc() {
        return admindesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SEOPAGEDEFSUBPARAM.ADMINDESC
     *
     * @param admindesc the value for EMDI.SEOPAGEDEFSUBPARAM.ADMINDESC
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setAdmindesc(String admindesc) {
        this.admindesc = admindesc == null ? null : admindesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SEOPAGEDEFSUBPARAM.CLASSNAME
     *
     * @return the value of EMDI.SEOPAGEDEFSUBPARAM.CLASSNAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SEOPAGEDEFSUBPARAM.CLASSNAME
     *
     * @param classname the value for EMDI.SEOPAGEDEFSUBPARAM.CLASSNAME
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SEOPAGEDEFSUBPARAM.OPTCOUNTER
     *
     * @return the value of EMDI.SEOPAGEDEFSUBPARAM.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SEOPAGEDEFSUBPARAM.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.SEOPAGEDEFSUBPARAM.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}