package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Seoredirect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SEOREDIRECT.SEOREDIRECT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal seoredirectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SEOREDIRECT.SEOURLKWD_ID_NEW
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal seourlkwdIdNew;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SEOREDIRECT.SEOURLKWD_ID_ORIG
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal seourlkwdIdOrig;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SEOREDIRECT.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SEOREDIRECT.SEOREDIRECT_ID
     *
     * @return the value of EMDI.SEOREDIRECT.SEOREDIRECT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getSeoredirectId() {
        return seoredirectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SEOREDIRECT.SEOREDIRECT_ID
     *
     * @param seoredirectId the value for EMDI.SEOREDIRECT.SEOREDIRECT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSeoredirectId(BigDecimal seoredirectId) {
        this.seoredirectId = seoredirectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SEOREDIRECT.SEOURLKWD_ID_NEW
     *
     * @return the value of EMDI.SEOREDIRECT.SEOURLKWD_ID_NEW
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getSeourlkwdIdNew() {
        return seourlkwdIdNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SEOREDIRECT.SEOURLKWD_ID_NEW
     *
     * @param seourlkwdIdNew the value for EMDI.SEOREDIRECT.SEOURLKWD_ID_NEW
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSeourlkwdIdNew(BigDecimal seourlkwdIdNew) {
        this.seourlkwdIdNew = seourlkwdIdNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SEOREDIRECT.SEOURLKWD_ID_ORIG
     *
     * @return the value of EMDI.SEOREDIRECT.SEOURLKWD_ID_ORIG
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getSeourlkwdIdOrig() {
        return seourlkwdIdOrig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SEOREDIRECT.SEOURLKWD_ID_ORIG
     *
     * @param seourlkwdIdOrig the value for EMDI.SEOREDIRECT.SEOURLKWD_ID_ORIG
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSeourlkwdIdOrig(BigDecimal seourlkwdIdOrig) {
        this.seourlkwdIdOrig = seourlkwdIdOrig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SEOREDIRECT.OPTCOUNTER
     *
     * @return the value of EMDI.SEOREDIRECT.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SEOREDIRECT.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.SEOREDIRECT.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}