package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Storeconf extends StoreconfKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.STORECONF.VALUE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.STORECONF.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.STORECONF.VALUE
     *
     * @return the value of EMDI.STORECONF.VALUE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.STORECONF.VALUE
     *
     * @param value the value for EMDI.STORECONF.VALUE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.STORECONF.OPTCOUNTER
     *
     * @return the value of EMDI.STORECONF.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.STORECONF.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.STORECONF.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}