package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class StorecntrKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.STORECNTR.CONTRACT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.STORECNTR.STORE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal storeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.STORECNTR.CONTRACT_ID
     *
     * @return the value of EMDI.STORECNTR.CONTRACT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.STORECNTR.CONTRACT_ID
     *
     * @param contractId the value for EMDI.STORECNTR.CONTRACT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setContractId(BigDecimal contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.STORECNTR.STORE_ID
     *
     * @return the value of EMDI.STORECNTR.STORE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.STORECNTR.STORE_ID
     *
     * @param storeId the value for EMDI.STORECNTR.STORE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setStoreId(BigDecimal storeId) {
        this.storeId = storeId;
    }
}