package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Stqotcfg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.STQOTCFG.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal storeentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.STQOTCFG.RETIREFLAG
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal retireflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.STQOTCFG.CSREXPIREPERIOD
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal csrexpireperiod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.STQOTCFG.CSSEXPIREPERIOD
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal cssexpireperiod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.STQOTCFG.EXPIREPERIOD
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal expireperiod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.STQOTCFG.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.STQOTCFG.STOREENT_ID
     *
     * @return the value of EMDI.STQOTCFG.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getStoreentId() {
        return storeentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.STQOTCFG.STOREENT_ID
     *
     * @param storeentId the value for EMDI.STQOTCFG.STOREENT_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setStoreentId(BigDecimal storeentId) {
        this.storeentId = storeentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.STQOTCFG.RETIREFLAG
     *
     * @return the value of EMDI.STQOTCFG.RETIREFLAG
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getRetireflag() {
        return retireflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.STQOTCFG.RETIREFLAG
     *
     * @param retireflag the value for EMDI.STQOTCFG.RETIREFLAG
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setRetireflag(BigDecimal retireflag) {
        this.retireflag = retireflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.STQOTCFG.CSREXPIREPERIOD
     *
     * @return the value of EMDI.STQOTCFG.CSREXPIREPERIOD
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getCsrexpireperiod() {
        return csrexpireperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.STQOTCFG.CSREXPIREPERIOD
     *
     * @param csrexpireperiod the value for EMDI.STQOTCFG.CSREXPIREPERIOD
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCsrexpireperiod(BigDecimal csrexpireperiod) {
        this.csrexpireperiod = csrexpireperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.STQOTCFG.CSSEXPIREPERIOD
     *
     * @return the value of EMDI.STQOTCFG.CSSEXPIREPERIOD
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getCssexpireperiod() {
        return cssexpireperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.STQOTCFG.CSSEXPIREPERIOD
     *
     * @param cssexpireperiod the value for EMDI.STQOTCFG.CSSEXPIREPERIOD
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCssexpireperiod(BigDecimal cssexpireperiod) {
        this.cssexpireperiod = cssexpireperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.STQOTCFG.EXPIREPERIOD
     *
     * @return the value of EMDI.STQOTCFG.EXPIREPERIOD
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getExpireperiod() {
        return expireperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.STQOTCFG.EXPIREPERIOD
     *
     * @param expireperiod the value for EMDI.STQOTCFG.EXPIREPERIOD
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setExpireperiod(BigDecimal expireperiod) {
        this.expireperiod = expireperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.STQOTCFG.OPTCOUNTER
     *
     * @return the value of EMDI.STQOTCFG.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.STQOTCFG.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.STQOTCFG.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}