package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Subscptype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SUBSCPTYPE.SUBSCPTYPE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String subscptypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SUBSCPTYPE.DESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.SUBSCPTYPE.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SUBSCPTYPE.SUBSCPTYPE_ID
     *
     * @return the value of EMDI.SUBSCPTYPE.SUBSCPTYPE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getSubscptypeId() {
        return subscptypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SUBSCPTYPE.SUBSCPTYPE_ID
     *
     * @param subscptypeId the value for EMDI.SUBSCPTYPE.SUBSCPTYPE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSubscptypeId(String subscptypeId) {
        this.subscptypeId = subscptypeId == null ? null : subscptypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SUBSCPTYPE.DESCRIPTION
     *
     * @return the value of EMDI.SUBSCPTYPE.DESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SUBSCPTYPE.DESCRIPTION
     *
     * @param description the value for EMDI.SUBSCPTYPE.DESCRIPTION
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.SUBSCPTYPE.OPTCOUNTER
     *
     * @return the value of EMDI.SUBSCPTYPE.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.SUBSCPTYPE.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.SUBSCPTYPE.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}