package com.avn.dataload.model.emdi;

import java.math.BigDecimal;
import java.util.Date;

public class Termcond {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.TERMCOND_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal termcondId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.TCSUBTYPE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String tcsubtypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.TRADING_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal tradingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.MANDATORY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal mandatory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.CHANGEABLE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal changeable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.TIMECREATED
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private Date timecreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.TIMEUPDATED
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private Date timeupdated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.STRINGFIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String stringfield1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.STRINGFIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String stringfield2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.STRINGFIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String stringfield3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.INTEGERFIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal integerfield1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.INTEGERFIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal integerfield2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.INTEGERFIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal integerfield3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.BIGINTFIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal bigintfield1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.BIGINTFIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal bigintfield2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.BIGINTFIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal bigintfield3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.FLOATFIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal floatfield1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.FLOATFIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal floatfield2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.FLOATFIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal floatfield3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.TIMEFIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private Date timefield1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.TIMEFIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private Date timefield2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.DECIMALFIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal decimalfield1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.DECIMALFIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal decimalfield2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.TIMEFIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private Date timefield3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.DECIMALFIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal decimalfield3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.SEQUENCE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.TERMCOND.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.TERMCOND_ID
     *
     * @return the value of EMDI.TERMCOND.TERMCOND_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getTermcondId() {
        return termcondId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.TERMCOND_ID
     *
     * @param termcondId the value for EMDI.TERMCOND.TERMCOND_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setTermcondId(BigDecimal termcondId) {
        this.termcondId = termcondId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.TCSUBTYPE_ID
     *
     * @return the value of EMDI.TERMCOND.TCSUBTYPE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getTcsubtypeId() {
        return tcsubtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.TCSUBTYPE_ID
     *
     * @param tcsubtypeId the value for EMDI.TERMCOND.TCSUBTYPE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setTcsubtypeId(String tcsubtypeId) {
        this.tcsubtypeId = tcsubtypeId == null ? null : tcsubtypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.TRADING_ID
     *
     * @return the value of EMDI.TERMCOND.TRADING_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getTradingId() {
        return tradingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.TRADING_ID
     *
     * @param tradingId the value for EMDI.TERMCOND.TRADING_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setTradingId(BigDecimal tradingId) {
        this.tradingId = tradingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.MANDATORY
     *
     * @return the value of EMDI.TERMCOND.MANDATORY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getMandatory() {
        return mandatory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.MANDATORY
     *
     * @param mandatory the value for EMDI.TERMCOND.MANDATORY
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setMandatory(BigDecimal mandatory) {
        this.mandatory = mandatory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.CHANGEABLE
     *
     * @return the value of EMDI.TERMCOND.CHANGEABLE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getChangeable() {
        return changeable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.CHANGEABLE
     *
     * @param changeable the value for EMDI.TERMCOND.CHANGEABLE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setChangeable(BigDecimal changeable) {
        this.changeable = changeable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.TIMECREATED
     *
     * @return the value of EMDI.TERMCOND.TIMECREATED
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public Date getTimecreated() {
        return timecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.TIMECREATED
     *
     * @param timecreated the value for EMDI.TERMCOND.TIMECREATED
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setTimecreated(Date timecreated) {
        this.timecreated = timecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.TIMEUPDATED
     *
     * @return the value of EMDI.TERMCOND.TIMEUPDATED
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public Date getTimeupdated() {
        return timeupdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.TIMEUPDATED
     *
     * @param timeupdated the value for EMDI.TERMCOND.TIMEUPDATED
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setTimeupdated(Date timeupdated) {
        this.timeupdated = timeupdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.STRINGFIELD1
     *
     * @return the value of EMDI.TERMCOND.STRINGFIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getStringfield1() {
        return stringfield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.STRINGFIELD1
     *
     * @param stringfield1 the value for EMDI.TERMCOND.STRINGFIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setStringfield1(String stringfield1) {
        this.stringfield1 = stringfield1 == null ? null : stringfield1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.STRINGFIELD2
     *
     * @return the value of EMDI.TERMCOND.STRINGFIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getStringfield2() {
        return stringfield2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.STRINGFIELD2
     *
     * @param stringfield2 the value for EMDI.TERMCOND.STRINGFIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setStringfield2(String stringfield2) {
        this.stringfield2 = stringfield2 == null ? null : stringfield2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.STRINGFIELD3
     *
     * @return the value of EMDI.TERMCOND.STRINGFIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getStringfield3() {
        return stringfield3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.STRINGFIELD3
     *
     * @param stringfield3 the value for EMDI.TERMCOND.STRINGFIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setStringfield3(String stringfield3) {
        this.stringfield3 = stringfield3 == null ? null : stringfield3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.INTEGERFIELD1
     *
     * @return the value of EMDI.TERMCOND.INTEGERFIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getIntegerfield1() {
        return integerfield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.INTEGERFIELD1
     *
     * @param integerfield1 the value for EMDI.TERMCOND.INTEGERFIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setIntegerfield1(BigDecimal integerfield1) {
        this.integerfield1 = integerfield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.INTEGERFIELD2
     *
     * @return the value of EMDI.TERMCOND.INTEGERFIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getIntegerfield2() {
        return integerfield2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.INTEGERFIELD2
     *
     * @param integerfield2 the value for EMDI.TERMCOND.INTEGERFIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setIntegerfield2(BigDecimal integerfield2) {
        this.integerfield2 = integerfield2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.INTEGERFIELD3
     *
     * @return the value of EMDI.TERMCOND.INTEGERFIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getIntegerfield3() {
        return integerfield3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.INTEGERFIELD3
     *
     * @param integerfield3 the value for EMDI.TERMCOND.INTEGERFIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setIntegerfield3(BigDecimal integerfield3) {
        this.integerfield3 = integerfield3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.BIGINTFIELD1
     *
     * @return the value of EMDI.TERMCOND.BIGINTFIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getBigintfield1() {
        return bigintfield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.BIGINTFIELD1
     *
     * @param bigintfield1 the value for EMDI.TERMCOND.BIGINTFIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setBigintfield1(BigDecimal bigintfield1) {
        this.bigintfield1 = bigintfield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.BIGINTFIELD2
     *
     * @return the value of EMDI.TERMCOND.BIGINTFIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getBigintfield2() {
        return bigintfield2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.BIGINTFIELD2
     *
     * @param bigintfield2 the value for EMDI.TERMCOND.BIGINTFIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setBigintfield2(BigDecimal bigintfield2) {
        this.bigintfield2 = bigintfield2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.BIGINTFIELD3
     *
     * @return the value of EMDI.TERMCOND.BIGINTFIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getBigintfield3() {
        return bigintfield3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.BIGINTFIELD3
     *
     * @param bigintfield3 the value for EMDI.TERMCOND.BIGINTFIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setBigintfield3(BigDecimal bigintfield3) {
        this.bigintfield3 = bigintfield3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.FLOATFIELD1
     *
     * @return the value of EMDI.TERMCOND.FLOATFIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getFloatfield1() {
        return floatfield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.FLOATFIELD1
     *
     * @param floatfield1 the value for EMDI.TERMCOND.FLOATFIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setFloatfield1(BigDecimal floatfield1) {
        this.floatfield1 = floatfield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.FLOATFIELD2
     *
     * @return the value of EMDI.TERMCOND.FLOATFIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getFloatfield2() {
        return floatfield2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.FLOATFIELD2
     *
     * @param floatfield2 the value for EMDI.TERMCOND.FLOATFIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setFloatfield2(BigDecimal floatfield2) {
        this.floatfield2 = floatfield2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.FLOATFIELD3
     *
     * @return the value of EMDI.TERMCOND.FLOATFIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getFloatfield3() {
        return floatfield3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.FLOATFIELD3
     *
     * @param floatfield3 the value for EMDI.TERMCOND.FLOATFIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setFloatfield3(BigDecimal floatfield3) {
        this.floatfield3 = floatfield3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.TIMEFIELD1
     *
     * @return the value of EMDI.TERMCOND.TIMEFIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public Date getTimefield1() {
        return timefield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.TIMEFIELD1
     *
     * @param timefield1 the value for EMDI.TERMCOND.TIMEFIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setTimefield1(Date timefield1) {
        this.timefield1 = timefield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.TIMEFIELD2
     *
     * @return the value of EMDI.TERMCOND.TIMEFIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public Date getTimefield2() {
        return timefield2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.TIMEFIELD2
     *
     * @param timefield2 the value for EMDI.TERMCOND.TIMEFIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setTimefield2(Date timefield2) {
        this.timefield2 = timefield2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.DECIMALFIELD1
     *
     * @return the value of EMDI.TERMCOND.DECIMALFIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getDecimalfield1() {
        return decimalfield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.DECIMALFIELD1
     *
     * @param decimalfield1 the value for EMDI.TERMCOND.DECIMALFIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setDecimalfield1(BigDecimal decimalfield1) {
        this.decimalfield1 = decimalfield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.DECIMALFIELD2
     *
     * @return the value of EMDI.TERMCOND.DECIMALFIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getDecimalfield2() {
        return decimalfield2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.DECIMALFIELD2
     *
     * @param decimalfield2 the value for EMDI.TERMCOND.DECIMALFIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setDecimalfield2(BigDecimal decimalfield2) {
        this.decimalfield2 = decimalfield2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.TIMEFIELD3
     *
     * @return the value of EMDI.TERMCOND.TIMEFIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public Date getTimefield3() {
        return timefield3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.TIMEFIELD3
     *
     * @param timefield3 the value for EMDI.TERMCOND.TIMEFIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setTimefield3(Date timefield3) {
        this.timefield3 = timefield3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.DECIMALFIELD3
     *
     * @return the value of EMDI.TERMCOND.DECIMALFIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getDecimalfield3() {
        return decimalfield3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.DECIMALFIELD3
     *
     * @param decimalfield3 the value for EMDI.TERMCOND.DECIMALFIELD3
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setDecimalfield3(BigDecimal decimalfield3) {
        this.decimalfield3 = decimalfield3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.SEQUENCE
     *
     * @return the value of EMDI.TERMCOND.SEQUENCE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.SEQUENCE
     *
     * @param sequence the value for EMDI.TERMCOND.SEQUENCE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSequence(BigDecimal sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.TERMCOND.OPTCOUNTER
     *
     * @return the value of EMDI.TERMCOND.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.TERMCOND.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.TERMCOND.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}