package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class XformResponseExportComp extends XformResponseExportCompKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XFORM_RESPONSE_EXPORT_COMP.ADDRESS_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XFORM_RESPONSE_EXPORT_COMP.ORDERS_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal ordersId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XFORM_RESPONSE_EXPORT_COMP.ADDRESS_ID
     *
     * @return the value of EMDI.XFORM_RESPONSE_EXPORT_COMP.ADDRESS_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XFORM_RESPONSE_EXPORT_COMP.ADDRESS_ID
     *
     * @param addressId the value for EMDI.XFORM_RESPONSE_EXPORT_COMP.ADDRESS_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setAddressId(BigDecimal addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XFORM_RESPONSE_EXPORT_COMP.ORDERS_ID
     *
     * @return the value of EMDI.XFORM_RESPONSE_EXPORT_COMP.ORDERS_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOrdersId() {
        return ordersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XFORM_RESPONSE_EXPORT_COMP.ORDERS_ID
     *
     * @param ordersId the value for EMDI.XFORM_RESPONSE_EXPORT_COMP.ORDERS_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOrdersId(BigDecimal ordersId) {
        this.ordersId = ordersId;
    }
}