package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class XformQuestionSetRelKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XFORM_QUESTION_SET_REL.FORM_QUESTION_SET_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal formQuestionSetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XFORM_QUESTION_SET_REL.FORM_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal formId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XFORM_QUESTION_SET_REL.FORM_VERSION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal formVersionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XFORM_QUESTION_SET_REL.FORM_QUESTION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal formQuestionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XFORM_QUESTION_SET_REL.FORM_QUESTION_SET_ID
     *
     * @return the value of EMDI.XFORM_QUESTION_SET_REL.FORM_QUESTION_SET_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getFormQuestionSetId() {
        return formQuestionSetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XFORM_QUESTION_SET_REL.FORM_QUESTION_SET_ID
     *
     * @param formQuestionSetId the value for EMDI.XFORM_QUESTION_SET_REL.FORM_QUESTION_SET_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setFormQuestionSetId(BigDecimal formQuestionSetId) {
        this.formQuestionSetId = formQuestionSetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XFORM_QUESTION_SET_REL.FORM_ID
     *
     * @return the value of EMDI.XFORM_QUESTION_SET_REL.FORM_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XFORM_QUESTION_SET_REL.FORM_ID
     *
     * @param formId the value for EMDI.XFORM_QUESTION_SET_REL.FORM_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setFormId(BigDecimal formId) {
        this.formId = formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XFORM_QUESTION_SET_REL.FORM_VERSION_ID
     *
     * @return the value of EMDI.XFORM_QUESTION_SET_REL.FORM_VERSION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getFormVersionId() {
        return formVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XFORM_QUESTION_SET_REL.FORM_VERSION_ID
     *
     * @param formVersionId the value for EMDI.XFORM_QUESTION_SET_REL.FORM_VERSION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setFormVersionId(BigDecimal formVersionId) {
        this.formVersionId = formVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XFORM_QUESTION_SET_REL.FORM_QUESTION_ID
     *
     * @return the value of EMDI.XFORM_QUESTION_SET_REL.FORM_QUESTION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getFormQuestionId() {
        return formQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XFORM_QUESTION_SET_REL.FORM_QUESTION_ID
     *
     * @param formQuestionId the value for EMDI.XFORM_QUESTION_SET_REL.FORM_QUESTION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setFormQuestionId(BigDecimal formQuestionId) {
        this.formQuestionId = formQuestionId;
    }
}