package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class XformQuestionLanguageKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XFORM_QUESTION_LANGUAGE.LANGUAGE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal languageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XFORM_QUESTION_LANGUAGE.FORM_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal formId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XFORM_QUESTION_LANGUAGE.FORM_VERSION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal formVersionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XFORM_QUESTION_LANGUAGE.FORM_QUESTION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal formQuestionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XFORM_QUESTION_LANGUAGE.LANGUAGE_ID
     *
     * @return the value of EMDI.XFORM_QUESTION_LANGUAGE.LANGUAGE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getLanguageId() {
        return languageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XFORM_QUESTION_LANGUAGE.LANGUAGE_ID
     *
     * @param languageId the value for EMDI.XFORM_QUESTION_LANGUAGE.LANGUAGE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setLanguageId(BigDecimal languageId) {
        this.languageId = languageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XFORM_QUESTION_LANGUAGE.FORM_ID
     *
     * @return the value of EMDI.XFORM_QUESTION_LANGUAGE.FORM_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XFORM_QUESTION_LANGUAGE.FORM_ID
     *
     * @param formId the value for EMDI.XFORM_QUESTION_LANGUAGE.FORM_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setFormId(BigDecimal formId) {
        this.formId = formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XFORM_QUESTION_LANGUAGE.FORM_VERSION_ID
     *
     * @return the value of EMDI.XFORM_QUESTION_LANGUAGE.FORM_VERSION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getFormVersionId() {
        return formVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XFORM_QUESTION_LANGUAGE.FORM_VERSION_ID
     *
     * @param formVersionId the value for EMDI.XFORM_QUESTION_LANGUAGE.FORM_VERSION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setFormVersionId(BigDecimal formVersionId) {
        this.formVersionId = formVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XFORM_QUESTION_LANGUAGE.FORM_QUESTION_ID
     *
     * @return the value of EMDI.XFORM_QUESTION_LANGUAGE.FORM_QUESTION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getFormQuestionId() {
        return formQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XFORM_QUESTION_LANGUAGE.FORM_QUESTION_ID
     *
     * @param formQuestionId the value for EMDI.XFORM_QUESTION_LANGUAGE.FORM_QUESTION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setFormQuestionId(BigDecimal formQuestionId) {
        this.formQuestionId = formQuestionId;
    }
}