package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class XformResponseKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XFORM_RESPONSE.FORM_RESPONSE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal formResponseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XFORM_RESPONSE.FORM_VERSION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal formVersionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XFORM_RESPONSE.FORM_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal formId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XFORM_RESPONSE.STORE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal storeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XFORM_RESPONSE.FORM_RESPONSE_ID
     *
     * @return the value of EMDI.XFORM_RESPONSE.FORM_RESPONSE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getFormResponseId() {
        return formResponseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XFORM_RESPONSE.FORM_RESPONSE_ID
     *
     * @param formResponseId the value for EMDI.XFORM_RESPONSE.FORM_RESPONSE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setFormResponseId(BigDecimal formResponseId) {
        this.formResponseId = formResponseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XFORM_RESPONSE.FORM_VERSION_ID
     *
     * @return the value of EMDI.XFORM_RESPONSE.FORM_VERSION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getFormVersionId() {
        return formVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XFORM_RESPONSE.FORM_VERSION_ID
     *
     * @param formVersionId the value for EMDI.XFORM_RESPONSE.FORM_VERSION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setFormVersionId(BigDecimal formVersionId) {
        this.formVersionId = formVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XFORM_RESPONSE.FORM_ID
     *
     * @return the value of EMDI.XFORM_RESPONSE.FORM_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XFORM_RESPONSE.FORM_ID
     *
     * @param formId the value for EMDI.XFORM_RESPONSE.FORM_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setFormId(BigDecimal formId) {
        this.formId = formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XFORM_RESPONSE.STORE_ID
     *
     * @return the value of EMDI.XFORM_RESPONSE.STORE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XFORM_RESPONSE.STORE_ID
     *
     * @param storeId the value for EMDI.XFORM_RESPONSE.STORE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setStoreId(BigDecimal storeId) {
        this.storeId = storeId;
    }
}