package com.avn.dataload.model.emdi;

import java.math.BigDecimal;
import java.util.Date;

public class Xmanfoverride extends XmanfoverrideKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XMANFOVERRIDE.OVERRIDE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String override;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XMANFOVERRIDE.LASTUPDATED
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private Date lastupdated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XMANFOVERRIDE.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String field1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XMANFOVERRIDE.FIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String field2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XMANFOVERRIDE.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XMANFOVERRIDE.OVERRIDE
     *
     * @return the value of EMDI.XMANFOVERRIDE.OVERRIDE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getOverride() {
        return override;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XMANFOVERRIDE.OVERRIDE
     *
     * @param override the value for EMDI.XMANFOVERRIDE.OVERRIDE
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOverride(String override) {
        this.override = override == null ? null : override.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XMANFOVERRIDE.LASTUPDATED
     *
     * @return the value of EMDI.XMANFOVERRIDE.LASTUPDATED
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public Date getLastupdated() {
        return lastupdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XMANFOVERRIDE.LASTUPDATED
     *
     * @param lastupdated the value for EMDI.XMANFOVERRIDE.LASTUPDATED
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setLastupdated(Date lastupdated) {
        this.lastupdated = lastupdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XMANFOVERRIDE.FIELD1
     *
     * @return the value of EMDI.XMANFOVERRIDE.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XMANFOVERRIDE.FIELD1
     *
     * @param field1 the value for EMDI.XMANFOVERRIDE.FIELD1
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField1(String field1) {
        this.field1 = field1 == null ? null : field1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XMANFOVERRIDE.FIELD2
     *
     * @return the value of EMDI.XMANFOVERRIDE.FIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XMANFOVERRIDE.FIELD2
     *
     * @param field2 the value for EMDI.XMANFOVERRIDE.FIELD2
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setField2(String field2) {
        this.field2 = field2 == null ? null : field2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XMANFOVERRIDE.OPTCOUNTER
     *
     * @return the value of EMDI.XMANFOVERRIDE.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XMANFOVERRIDE.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.XMANFOVERRIDE.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}