package com.avn.dataload.model.emdi;

import java.math.BigDecimal;
import java.util.Date;

public class XSapSalesdocItem extends XSapSalesdocItemKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.X_SAP_SALESDOC_ITEM.VBAP_PSTYV
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String vbapPstyv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.X_SAP_SALESDOC_ITEM.VBAP_WERKS
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String vbapWerks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.X_SAP_SALESDOC_ITEM.VBAP_KDMAT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String vbapKdmat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.X_SAP_SALESDOC_ITEM.VBAP_MATNR
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String vbapMatnr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.X_SAP_SALESDOC_ITEM.VBAP_KWMENG
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal vbapKwmeng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.X_SAP_SALESDOC_ITEM.VBSTT_ABSTA_BEZ
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String vbsttAbstaBez;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.X_SAP_SALESDOC_ITEM.MARA_MFRNR
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String maraMfrnr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.X_SAP_SALESDOC_ITEM.ZZ_DATWSTA
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private Date zzDatwsta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.X_SAP_SALESDOC_ITEM.LIPSD_G_LFIMG
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal lipsdGLfimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.X_SAP_SALESDOC_ITEM.VBAP_ZZ_CBLK
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String vbapZzCblk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.X_SAP_SALESDOC_ITEM.UPDATED_FLAG
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private String updatedFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.X_SAP_SALESDOC_ITEM.VBAP_PSTYV
     *
     * @return the value of EMDI.X_SAP_SALESDOC_ITEM.VBAP_PSTYV
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getVbapPstyv() {
        return vbapPstyv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.X_SAP_SALESDOC_ITEM.VBAP_PSTYV
     *
     * @param vbapPstyv the value for EMDI.X_SAP_SALESDOC_ITEM.VBAP_PSTYV
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setVbapPstyv(String vbapPstyv) {
        this.vbapPstyv = vbapPstyv == null ? null : vbapPstyv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.X_SAP_SALESDOC_ITEM.VBAP_WERKS
     *
     * @return the value of EMDI.X_SAP_SALESDOC_ITEM.VBAP_WERKS
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getVbapWerks() {
        return vbapWerks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.X_SAP_SALESDOC_ITEM.VBAP_WERKS
     *
     * @param vbapWerks the value for EMDI.X_SAP_SALESDOC_ITEM.VBAP_WERKS
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setVbapWerks(String vbapWerks) {
        this.vbapWerks = vbapWerks == null ? null : vbapWerks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.X_SAP_SALESDOC_ITEM.VBAP_KDMAT
     *
     * @return the value of EMDI.X_SAP_SALESDOC_ITEM.VBAP_KDMAT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getVbapKdmat() {
        return vbapKdmat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.X_SAP_SALESDOC_ITEM.VBAP_KDMAT
     *
     * @param vbapKdmat the value for EMDI.X_SAP_SALESDOC_ITEM.VBAP_KDMAT
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setVbapKdmat(String vbapKdmat) {
        this.vbapKdmat = vbapKdmat == null ? null : vbapKdmat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.X_SAP_SALESDOC_ITEM.VBAP_MATNR
     *
     * @return the value of EMDI.X_SAP_SALESDOC_ITEM.VBAP_MATNR
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getVbapMatnr() {
        return vbapMatnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.X_SAP_SALESDOC_ITEM.VBAP_MATNR
     *
     * @param vbapMatnr the value for EMDI.X_SAP_SALESDOC_ITEM.VBAP_MATNR
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setVbapMatnr(String vbapMatnr) {
        this.vbapMatnr = vbapMatnr == null ? null : vbapMatnr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.X_SAP_SALESDOC_ITEM.VBAP_KWMENG
     *
     * @return the value of EMDI.X_SAP_SALESDOC_ITEM.VBAP_KWMENG
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getVbapKwmeng() {
        return vbapKwmeng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.X_SAP_SALESDOC_ITEM.VBAP_KWMENG
     *
     * @param vbapKwmeng the value for EMDI.X_SAP_SALESDOC_ITEM.VBAP_KWMENG
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setVbapKwmeng(BigDecimal vbapKwmeng) {
        this.vbapKwmeng = vbapKwmeng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.X_SAP_SALESDOC_ITEM.VBSTT_ABSTA_BEZ
     *
     * @return the value of EMDI.X_SAP_SALESDOC_ITEM.VBSTT_ABSTA_BEZ
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getVbsttAbstaBez() {
        return vbsttAbstaBez;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.X_SAP_SALESDOC_ITEM.VBSTT_ABSTA_BEZ
     *
     * @param vbsttAbstaBez the value for EMDI.X_SAP_SALESDOC_ITEM.VBSTT_ABSTA_BEZ
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setVbsttAbstaBez(String vbsttAbstaBez) {
        this.vbsttAbstaBez = vbsttAbstaBez == null ? null : vbsttAbstaBez.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.X_SAP_SALESDOC_ITEM.MARA_MFRNR
     *
     * @return the value of EMDI.X_SAP_SALESDOC_ITEM.MARA_MFRNR
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getMaraMfrnr() {
        return maraMfrnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.X_SAP_SALESDOC_ITEM.MARA_MFRNR
     *
     * @param maraMfrnr the value for EMDI.X_SAP_SALESDOC_ITEM.MARA_MFRNR
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setMaraMfrnr(String maraMfrnr) {
        this.maraMfrnr = maraMfrnr == null ? null : maraMfrnr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.X_SAP_SALESDOC_ITEM.ZZ_DATWSTA
     *
     * @return the value of EMDI.X_SAP_SALESDOC_ITEM.ZZ_DATWSTA
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public Date getZzDatwsta() {
        return zzDatwsta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.X_SAP_SALESDOC_ITEM.ZZ_DATWSTA
     *
     * @param zzDatwsta the value for EMDI.X_SAP_SALESDOC_ITEM.ZZ_DATWSTA
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setZzDatwsta(Date zzDatwsta) {
        this.zzDatwsta = zzDatwsta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.X_SAP_SALESDOC_ITEM.LIPSD_G_LFIMG
     *
     * @return the value of EMDI.X_SAP_SALESDOC_ITEM.LIPSD_G_LFIMG
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getLipsdGLfimg() {
        return lipsdGLfimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.X_SAP_SALESDOC_ITEM.LIPSD_G_LFIMG
     *
     * @param lipsdGLfimg the value for EMDI.X_SAP_SALESDOC_ITEM.LIPSD_G_LFIMG
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setLipsdGLfimg(BigDecimal lipsdGLfimg) {
        this.lipsdGLfimg = lipsdGLfimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.X_SAP_SALESDOC_ITEM.VBAP_ZZ_CBLK
     *
     * @return the value of EMDI.X_SAP_SALESDOC_ITEM.VBAP_ZZ_CBLK
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getVbapZzCblk() {
        return vbapZzCblk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.X_SAP_SALESDOC_ITEM.VBAP_ZZ_CBLK
     *
     * @param vbapZzCblk the value for EMDI.X_SAP_SALESDOC_ITEM.VBAP_ZZ_CBLK
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setVbapZzCblk(String vbapZzCblk) {
        this.vbapZzCblk = vbapZzCblk == null ? null : vbapZzCblk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.X_SAP_SALESDOC_ITEM.UPDATED_FLAG
     *
     * @return the value of EMDI.X_SAP_SALESDOC_ITEM.UPDATED_FLAG
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public String getUpdatedFlag() {
        return updatedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.X_SAP_SALESDOC_ITEM.UPDATED_FLAG
     *
     * @param updatedFlag the value for EMDI.X_SAP_SALESDOC_ITEM.UPDATED_FLAG
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setUpdatedFlag(String updatedFlag) {
        this.updatedFlag = updatedFlag == null ? null : updatedFlag.trim();
    }
}