package com.avn.dataload.model.emdi;

import java.math.BigDecimal;

public class Xsubscrstorerel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XSUBSCRSTOREREL.SUBSCRIPTION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal subscriptionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XSUBSCRSTOREREL.STORE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XSUBSCRSTOREREL.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XSUBSCRSTOREREL.SUBSCRIPTION_ID
     *
     * @return the value of EMDI.XSUBSCRSTOREREL.SUBSCRIPTION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getSubscriptionId() {
        return subscriptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XSUBSCRSTOREREL.SUBSCRIPTION_ID
     *
     * @param subscriptionId the value for EMDI.XSUBSCRSTOREREL.SUBSCRIPTION_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setSubscriptionId(BigDecimal subscriptionId) {
        this.subscriptionId = subscriptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XSUBSCRSTOREREL.STORE_ID
     *
     * @return the value of EMDI.XSUBSCRSTOREREL.STORE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XSUBSCRSTOREREL.STORE_ID
     *
     * @param storeId the value for EMDI.XSUBSCRSTOREREL.STORE_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setStoreId(BigDecimal storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XSUBSCRSTOREREL.OPTCOUNTER
     *
     * @return the value of EMDI.XSUBSCRSTOREREL.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XSUBSCRSTOREREL.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.XSUBSCRSTOREREL.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}