package com.avn.dataload.model.emdi;

import java.math.BigDecimal;
import java.util.Date;

public class Xuserpymntretry {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XUSERPYMNTRETRY.XUSERPYMNTRETRY_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal xuserpymntretryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XUSERPYMNTRETRY.USERS_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal usersId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XUSERPYMNTRETRY.FAILURE_COUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal failureCounter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XUSERPYMNTRETRY.CVVINVALID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private Date cvvinvalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMDI.XUSERPYMNTRETRY.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    private BigDecimal optcounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XUSERPYMNTRETRY.XUSERPYMNTRETRY_ID
     *
     * @return the value of EMDI.XUSERPYMNTRETRY.XUSERPYMNTRETRY_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getXuserpymntretryId() {
        return xuserpymntretryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XUSERPYMNTRETRY.XUSERPYMNTRETRY_ID
     *
     * @param xuserpymntretryId the value for EMDI.XUSERPYMNTRETRY.XUSERPYMNTRETRY_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setXuserpymntretryId(BigDecimal xuserpymntretryId) {
        this.xuserpymntretryId = xuserpymntretryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XUSERPYMNTRETRY.USERS_ID
     *
     * @return the value of EMDI.XUSERPYMNTRETRY.USERS_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getUsersId() {
        return usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XUSERPYMNTRETRY.USERS_ID
     *
     * @param usersId the value for EMDI.XUSERPYMNTRETRY.USERS_ID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setUsersId(BigDecimal usersId) {
        this.usersId = usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XUSERPYMNTRETRY.FAILURE_COUNTER
     *
     * @return the value of EMDI.XUSERPYMNTRETRY.FAILURE_COUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getFailureCounter() {
        return failureCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XUSERPYMNTRETRY.FAILURE_COUNTER
     *
     * @param failureCounter the value for EMDI.XUSERPYMNTRETRY.FAILURE_COUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setFailureCounter(BigDecimal failureCounter) {
        this.failureCounter = failureCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XUSERPYMNTRETRY.CVVINVALID
     *
     * @return the value of EMDI.XUSERPYMNTRETRY.CVVINVALID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public Date getCvvinvalid() {
        return cvvinvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XUSERPYMNTRETRY.CVVINVALID
     *
     * @param cvvinvalid the value for EMDI.XUSERPYMNTRETRY.CVVINVALID
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setCvvinvalid(Date cvvinvalid) {
        this.cvvinvalid = cvvinvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMDI.XUSERPYMNTRETRY.OPTCOUNTER
     *
     * @return the value of EMDI.XUSERPYMNTRETRY.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public BigDecimal getOptcounter() {
        return optcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMDI.XUSERPYMNTRETRY.OPTCOUNTER
     *
     * @param optcounter the value for EMDI.XUSERPYMNTRETRY.OPTCOUNTER
     *
     * @mbggenerated Sun Oct 09 16:35:15 CST 2016
     */
    public void setOptcounter(BigDecimal optcounter) {
        this.optcounter = optcounter;
    }
}