-- ----------------------------------------------
-- DDL Statements for indexes
-- ----------------------------------------------

CREATE UNIQUE INDEX "APP"."I0000054" ON "APP"."CALCODE" ("CALUSAGE_ID", "CODE", "STOREENT_ID");

CREATE INDEX "APP"."I0000495" ON "APP"."CALCODE" ("CALMETHOD_ID_APP");

CREATE INDEX "APP"."I0000496" ON "APP"."CALCODE" ("CALMETHOD_ID");

CREATE INDEX "APP"."I0000497" ON "APP"."CALCODE" ("CALMETHOD_ID_QFY");

CREATE INDEX "APP"."I0000498" ON "APP"."CALCODE" ("STOREENT_ID");

CREATE INDEX "APP"."I0001247" ON "APP"."CALCODE" ("TXCDCLASS_ID");

CREATE INDEX "APP"."I0001312" ON "APP"."FILEPROCREL" ("PROCESSFILE_ID");

CREATE UNIQUE INDEX "APP"."I0000137" ON "APP"."ISEDITATT" ("PROFILE_ID", "INTERSPECATTNAME");

CREATE UNIQUE INDEX "APP"."I0001205" ON "APP"."ATTRVAL" ("ATTR_ID", "IDENTIFIER");

CREATE INDEX "APP"."I0001206" ON "APP"."ATTRVAL" ("ATTR_ID", "STOREENT_ID", "VALUSAGE");

CREATE UNIQUE INDEX "APP"."I0001141" ON "APP"."DMACTIVITY" ("NAME", "STOREENT_ID");

CREATE INDEX "APP"."I0001142" ON "APP"."DMACTIVITY" ("STOREENT_ID");

CREATE INDEX "APP"."I0001143" ON "APP"."DMACTIVITY" ("DMCAMPAIGN_ID");

CREATE INDEX "APP"."I0001144" ON "APP"."DMACTIVITY" ("DMACTTYPE_ID");

CREATE INDEX "APP"."I0001145" ON "APP"."DMACTIVITY" ("DMTEMPLATETYPE_ID");

CREATE INDEX "APP"."I0001146" ON "APP"."DMACTIVITY" ("DMEXPTYPE_ID");

CREATE INDEX "APP"."I0001193" ON "APP"."DMACTIVITY" ("STARTDATE");

CREATE UNIQUE INDEX "APP"."I0000262" ON "APP"."UTMERINFO" ("UTMERREF");

CREATE INDEX "APP"."I0000784" ON "APP"."STORECNTR" ("STORE_ID");

CREATE UNIQUE INDEX "APP"."I0000067" ON "APP"."CATGROUP" ("IDENTIFIER", "MEMBER_ID");

CREATE INDEX "APP"."I0000376" ON "APP"."CATGROUP" ("RANK");

CREATE INDEX "APP"."I0000525" ON "APP"."CATGROUP" ("MEMBER_ID");

CREATE UNIQUE INDEX "APP"."I0000101" ON "APP"."FFMCENTER" ("MEMBER_ID", "NAME");

CREATE INDEX "APP"."I0000345" ON "APP"."STORECENT" ("CATENTRY_ID");

CREATE INDEX "APP"."I0000277" ON "APP"."CPPMNACC" ("SHOPPEREMAILID");

CREATE UNIQUE INDEX "APP"."I0000074" ON "APP"."CMBITEMS" ("CBMRFNBR", "CBTRFNBR");

CREATE INDEX "APP"."I0000566" ON "APP"."EMLRPTEVTS" ("EMLPROMO_ID");

CREATE INDEX "APP"."I0000911" ON "APP"."CCOMMENT" ("CUSTOMERID");

CREATE INDEX "APP"."I0000912" ON "APP"."CCOMMENT" ("TARGETID");

CREATE INDEX "APP"."I0000913" ON "APP"."CCOMMENT" ("AUTHDOMAIN");

CREATE INDEX "APP"."I0000914" ON "APP"."CCOMMENT" ("CREATEDBY");

CREATE INDEX "APP"."I0000915" ON "APP"."CCOMMENT" ("LASTUPDATEDBY");

CREATE INDEX "APP"."I0000916" ON "APP"."CCOMMENT" ("LANGUAGE_ID");

CREATE UNIQUE INDEX "APP"."I0000077" ON "APP"."COLLATERAL" ("NAME", "STOREENT_ID");

CREATE INDEX "APP"."I0000312" ON "APP"."COLLATERAL" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000153" ON "APP"."MBRGRPTYPE" ("NAME");

CREATE INDEX "APP"."I0000364" ON "APP"."MANIFEST" ("ORDERS_ID", "ORDRELEASENUM", "MANIFESTSTATUS");

CREATE INDEX "APP"."I0000609" ON "APP"."MANIFEST" ("SHIPMODE_ID");

CREATE UNIQUE INDEX "APP"."I0001422" ON "APP"."SRCHCONFEXT" ("INDEXSCOPE", "INDEXTYPE", "LANGUAGE_ID", "INDEXSUBTYPE");

CREATE INDEX "APP"."I0001423" ON "APP"."SRCHCONFEXT" ("LANGUAGE_ID");

CREATE UNIQUE INDEX "APP"."I0000931" ON "APP"."CMFILEDIR" ("CMFILEDIR_PARENT", "IDENTIFIER");

--CREATE UNIQUE INDEX "APP"."I0001313" ON "APP"."PX_CDPOOL" ("CODE", "STORE_ID");

CREATE INDEX "APP"."I0001314" ON "APP"."PX_CDPOOL" ("STORE_ID");

CREATE UNIQUE INDEX "APP"."I0000142" ON "APP"."JURST" ("CODE", "STOREENT_ID", "SUBCLASS");

CREATE INDEX "APP"."I0000600" ON "APP"."JURST" ("STOREENT_ID");

CREATE INDEX "APP"."I0001200" ON "APP"."DMEXPFAMILY" ("FAMILY_ID");

CREATE UNIQUE INDEX "APP"."I0000152" ON "APP"."MBRGRP" ("OWNER_ID", "MBRGRPNAME");

CREATE INDEX "APP"."I0000392" ON "APP"."PX_USAGE" ("STOREENT_ID", "NAME", "VERSION");

CREATE INDEX "APP"."I0000393" ON "APP"."PX_USAGE" ("GUESTID");

CREATE INDEX "APP"."I0000407" ON "APP"."PX_USAGE" ("USERS_ID");

CREATE INDEX "APP"."I0000408" ON "APP"."PX_USAGE" ("ORDERS_ID");

CREATE INDEX "APP"."I0000409" ON "APP"."PX_USAGE" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0001220" ON "APP"."STLFFMREL" ("STLOC_ID", "FFMCENTER_ID");

CREATE INDEX "APP"."I0001221" ON "APP"."STLFFMREL" ("FFMCENTER_ID");

CREATE INDEX "APP"."I0001222" ON "APP"."STLFFMREL" ("ADDRESS_ID");

CREATE INDEX "APP"."I0001327" ON "APP"."INSRULECATGRP" ("INSRULECATGRP_ID", "INSRULE_ID");

CREATE INDEX "APP"."I0001328" ON "APP"."INSRULECATGRP" ("INSRULE_ID");

CREATE INDEX "APP"."I0001329" ON "APP"."INSRULECATGRP" ("CATGROUP_ID");

CREATE UNIQUE INDEX "APP"."I0000069" ON "APP"."CCCHECK" ("CCTYPE", "CCLENGTH", "CCPREFIX");

CREATE UNIQUE INDEX "APP"."I0000249" ON "APP"."TFTRADENG" ("NAME");

CREATE INDEX "APP"."I0000812" ON "APP"."TFTRADENG" ("STORE_ID");

CREATE INDEX "APP"."I0000813" ON "APP"."TFTRADENG" ("MEMBER_ID");

CREATE UNIQUE INDEX "APP"."I0000237" ON "APP"."STERROR" ("STDY", "STMRFNBR", "STURL", "STCFRNBR", "STCODE", "STLOGID");

CREATE UNIQUE INDEX "APP"."I0000428" ON "APP"."CMSMALLFILE" ("CMFILE_ID", "CONTENT_WORKSPACE");

CREATE INDEX "APP"."I0000699" ON "APP"."PROCMSGVW" ("ORGENTITY_ID");

CREATE UNIQUE INDEX "APP"."I0001156" ON "APP"."DMPAGE" ("NAME", "STOREENT_ID");

CREATE INDEX "APP"."I0001157" ON "APP"."DMPAGE" ("STOREENT_ID");

CREATE INDEX "APP"."I0000214" ON "APP"."RMAIADJCRD" ("RMAITEM_ID");

CREATE INDEX "APP"."I0000746" ON "APP"."RMAIADJCRD" ("ORDADJUST_ID");

CREATE INDEX "APP"."I0000287" ON "APP"."CPPMNCAT" ("CATALOG_ID", "CATGROUP_ID");

CREATE INDEX "APP"."I0000547" ON "APP"."CPPMNCAT" ("CATGROUP_ID");

CREATE INDEX "APP"."I0000324" ON "APP"."BUSPROF" ("REQUISITIONERID");

CREATE INDEX "APP"."I0000486" ON "APP"."BUSPROF" ("ORGUNIT_ID");

CREATE INDEX "APP"."I0000487" ON "APP"."BUSPROF" ("ORG_ID");

CREATE INDEX "APP"."I348118" ON "APP"."USERS" ("PROFILETYPE", "REGISTERTYPE", "USERS_ID");

CREATE INDEX "APP"."I0000969" ON "APP"."USERS" ("DN");

CREATE INDEX "APP"."I0000971" ON "APP"."USERS" ("REGISTERTYPE");

CREATE INDEX "APP"."I0001109" ON "APP"."USERS" ("PERSONALIZATIONID");

CREATE UNIQUE INDEX "APP"."I0000084" ON "APP"."DAEMON" ("HOSTNAME");

CREATE INDEX "APP"."I0000956" ON "APP"."ORDERBLK" ("ORDERS_ID");

CREATE INDEX "APP"."I0000957" ON "APP"."ORDERBLK" ("BLKRSNCODE_ID", "RESOLVED");

CREATE INDEX "APP"."I0000783" ON "APP"."STORECGRP" ("CATGROUP_ID");

CREATE INDEX "APP"."I0000843" ON "APP"."EDPORDER" ("STORE_ID", "ORDER_ID");

CREATE UNIQUE INDEX "APP"."I0000010" ON "APP"."ACRESGRP" ("GRPNAME");

CREATE INDEX "APP"."I0000446" ON "APP"."ACRESGRP" ("MEMBER_ID");

CREATE INDEX "APP"."I0000796" ON "APP"."STORETRANS" ("STORE_ID");

CREATE INDEX "APP"."I0000421" ON "APP"."PX_PROMPROM" ("PX_PROMO_ID_FROM");

CREATE INDEX "APP"."I0000422" ON "APP"."PX_PROMPROM" ("PX_PROMO_ID_TO");

CREATE UNIQUE INDEX "APP"."I0000199" ON "APP"."QTYUNITMAP" ("QTYUNIT_ID", "UOMSTANDARD");

CREATE INDEX "APP"."I0000357" ON "APP"."POLICYTC" ("TERMCOND_ID", "POLICY_ID");

CREATE INDEX "APP"."I0001273" ON "APP"."POLICYTC" ("POLICY_ID");

CREATE UNIQUE INDEX "APP"."I0000227" ON "APP"."SCHORDERS" ("JOB_RN");

CREATE INDEX "APP"."I0000761" ON "APP"."SCHORDERS" ("ORDERS_ID");

CREATE UNIQUE INDEX "APP"."I0000295" ON "APP"."FILEUPLOAD" ("FILEPATH", "VERSION");

CREATE INDEX "APP"."I0000296" ON "APP"."FILEUPLOAD" ("STORE_ID");

CREATE INDEX "APP"."I0000571" ON "APP"."FILEUPLOAD" ("SCCJOBREFNUM");

CREATE INDEX "APP"."I0000572" ON "APP"."FILEUPLOAD" ("MEMBER_ID");

CREATE UNIQUE INDEX "APP"."I0000089" ON "APP"."DBTEMPLATE" ("DBTEMPREF", "DBTEMPFREQ");

CREATE UNIQUE INDEX "APP"."I0001376" ON "APP"."CFPRODUCTSET" ("CATFILTER_ID", "PRODUCTSET_ID");

CREATE INDEX "APP"."I0001377" ON "APP"."CFPRODUCTSET" ("PRODUCTSET_ID");

CREATE INDEX "APP"."I0001395" ON "APP"."CFPRODUCTSET" ("CATFILTER_ID");

CREATE UNIQUE INDEX "APP"."I0001413" ON "APP"."SEOPAGEDEFOVR" ("SEOPAGEDEF_ID", "OBJECTTYPE", "OBJECT_ID");

CREATE INDEX "APP"."I0000536" ON "APP"."CLSFCODEDS" ("CLASIFCODE_ID");

CREATE UNIQUE INDEX "APP"."I0001197" ON "APP"."PX_ELEMENTNVP" ("PX_ELEMENT_ID", "NAME", "VALUE");

CREATE INDEX "APP"."I0000358" ON "APP"."RFQTARGET" ("RFQ_ID");

CREATE UNIQUE INDEX "APP"."I0001203" ON "APP"."ATTR" ("IDENTIFIER", "ATTRDICT_ID");

CREATE INDEX "APP"."I0001204" ON "APP"."ATTR" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000184" ON "APP"."PARTICIPNT" ("MEMBER_ID", "PARTROLE_ID", "TRADING_ID", "TERMCOND_ID");

CREATE INDEX "APP"."I0000678" ON "APP"."PARTICIPNT" ("PARTROLE_ID");

CREATE INDEX "APP"."I0000679" ON "APP"."PARTICIPNT" ("TRADING_ID");

CREATE INDEX "APP"."I0000680" ON "APP"."PARTICIPNT" ("TERMCOND_ID");

CREATE UNIQUE INDEX "APP"."I0000006" ON "APP"."ACPOLICY" ("POLICYNAME", "MEMBER_ID");

CREATE INDEX "APP"."I0000316" ON "APP"."ACPOLICY" ("ACRESGRP_ID");

CREATE INDEX "APP"."I0000317" ON "APP"."ACPOLICY" ("MEMBER_ID");

CREATE INDEX "APP"."I0000318" ON "APP"."ACPOLICY" ("ACRELATION_ID");

CREATE INDEX "APP"."I0000319" ON "APP"."ACPOLICY" ("MBRGRP_ID");

CREATE INDEX "APP"."I0000320" ON "APP"."ACPOLICY" ("ACACTGRP_ID");

CREATE INDEX "APP"."I0000440" ON "APP"."ACPOLICY" ("ACRELGRP_ID");

CREATE INDEX "APP"."I0000448" ON "APP"."ACRESREL" ("ACRESCGRY_ID");

CREATE INDEX "APP"."GRADDR_INDEX2" ON "APP"."GRADDR" ("LASTNAME", "FIRSTNAME", "STATE");

CREATE INDEX "APP"."I0001300" ON "APP"."GRADDR" ("SEARCHKEYLASTNAME");

CREATE INDEX "APP"."I0001301" ON "APP"."GRADDR" ("SEARCHKEYFIRSTNAME");

CREATE UNIQUE INDEX "APP"."I0000052" ON "APP"."BZSVCCFG" ("SERVICENAME", "STOREENT_ID", "BZSRVCFG_ID");

CREATE INDEX "APP"."I0000794" ON "APP"."STOREREL" ("STRELTYP_ID");

CREATE INDEX "APP"."I0000795" ON "APP"."STOREREL" ("RELATEDSTORE_ID");

CREATE INDEX "APP"."I0000253" ON "APP"."TMPRADTL" ("SID");

CREATE INDEX "APP"."I0001254" ON "APP"."CURFMTDESC" ("STOREENT_ID", "SETCCURR", "NUMBRUSG_ID");

CREATE UNIQUE INDEX "APP"."I0000201" ON "APP"."RADETAIL" ("RA_ID", "FFMCENTER_ID", "ITEMSPC_ID", "EXPECTEDDATE");

CREATE INDEX "APP"."I0000202" ON "APP"."RADETAIL" ("RA_ID", "RADETAIL_ID", "EXPECTEDDATE");

CREATE INDEX "APP"."I0000712" ON "APP"."RADETAIL" ("ITEMSPC_ID");

CREATE INDEX "APP"."I0000713" ON "APP"."RADETAIL" ("FFMCENTER_ID");

CREATE UNIQUE INDEX "APP"."I0000209" ON "APP"."RFQRSP" ("NAME", "MAJORVERSION", "MINORVERSION");

CREATE INDEX "APP"."I0000351" ON "APP"."RFQRSP" ("RFQ_ID", "MEMBER_ID");

CREATE INDEX "APP"."I0000352" ON "APP"."RFQRSP" ("NAME");

CREATE INDEX "APP"."I0000727" ON "APP"."RFQRSP" ("MEMBER_ID");

CREATE INDEX "APP"."I0001279" ON "APP"."RFQRSP" ("TFTRADENG_ID");

CREATE INDEX "APP"."I0000616" ON "APP"."MBRGRPUSG" ("MBRGRP_ID");

CREATE INDEX "APP"."I0000450" ON "APP"."ALCHARGE" ("ORDERS_ID");

CREATE INDEX "APP"."I0000710" ON "APP"."RABACKALLO" ("ITEMSPC_ID");

CREATE INDEX "APP"."I0000711" ON "APP"."RABACKALLO" ("RADETAIL_ID");

CREATE UNIQUE INDEX "APP"."I0000135" ON "APP"."INVADJCODE" ("ADJUSTCODE", "STOREENT_ID");

CREATE INDEX "APP"."I0000591" ON "APP"."INVADJCODE" ("STOREENT_ID");

CREATE INDEX "APP"."I0000123" ON "APP"."ICMETAFEAT" ("STOREID");

CREATE INDEX "APP"."I0000124" ON "APP"."ICMETAFEAT" ("ORDERSEQ");

CREATE INDEX "APP"."I0001259" ON "APP"."ICMETAFEAT" ("METAPHORID");

CREATE UNIQUE INDEX "APP"."I0000078" ON "APP"."CONTRACT" ("NAME", "MEMBER_ID", "MAJORVERSION", "MINORVERSION", "ORIGIN");

CREATE INDEX "APP"."I0000539" ON "APP"."CONTRACT" ("MEMBER_ID");

CREATE UNIQUE INDEX "APP"."I0000001" ON "APP"."ACACTGRP" ("GROUPNAME");

CREATE INDEX "APP"."I0000427" ON "APP"."ACACTGRP" ("MEMBER_ID");

CREATE INDEX "APP"."I0000563" ON "APP"."EMLGRPREL" ("MBRGRP_ID");

CREATE UNIQUE INDEX "APP"."I0001302" ON "APP"."DMRANKINGITEM" ("DMELEMENT_ID", "STOREENT_ID", "OBJECT_ID", "GROUP_ID");

CREATE UNIQUE INDEX "APP"."I0000880" ON "APP"."CMFWKSPC" ("IDENTIFIER");

CREATE INDEX "APP"."I0000881" ON "APP"."CMFWKSPC" ("STATUS");

CREATE INDEX "APP"."I0000889" ON "APP"."CMFWKSPC" ("MEMBER_ID");

CREATE UNIQUE INDEX "APP"."I0000095" ON "APP"."DISTARRANG" ("BASEITEM_ID", "MERCHANTSTORE_ID", "WHOLESALESTORE_ID", "STARTDATE", "ENDDATE");

CREATE INDEX "APP"."I0000347" ON "APP"."DISTARRANG" ("DISTARRANG_ID", "MERCHANTSTORE_ID");

CREATE INDEX "APP"."I0000560" ON "APP"."DISTARRANG" ("MERCHANTSTORE_ID");

CREATE INDEX "APP"."I0000561" ON "APP"."DISTARRANG" ("WHOLESALESTORE_ID");

CREATE UNIQUE INDEX "APP"."I0000878" ON "APP"."ATCHRLUS" ("IDENTIFIER");

CREATE INDEX "APP"."I0001334" ON "APP"."INSRULEINSOPT" ("INSRULE_ID");

CREATE INDEX "APP"."I0001335" ON "APP"."INSRULEINSOPT" ("CURRENCY");

CREATE INDEX "APP"."I0001257" ON "APP"."EXCHORDERS" ("RMA_ID");

CREATE INDEX "APP"."I0001158" ON "APP"."DMEMSPOTPAGE" ("DMPAGE_ID");

CREATE UNIQUE INDEX "APP"."I0000973" ON "APP"."MERCHCONFINFO" ("MERCHCONF_ID", "PROPERTY_NAME");

CREATE INDEX "APP"."I0000620" ON "APP"."MGPTRDPSCN" ("MBRGRP_ID");

CREATE UNIQUE INDEX "APP"."I0000146" ON "APP"."LMEVENTMAP" ("LMSETNAME", "STOREENT_ID", "EXTEVENTNAME");

CREATE INDEX "APP"."I0000310" ON "APP"."LMEVENTMAP" ("LMSETNAME", "STOREENT_ID");

CREATE INDEX "APP"."I0000605" ON "APP"."LMEVENTMAP" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000968" ON "APP"."PRCORSN" ("STOREENT_ID", "CODE");

CREATE INDEX "APP"."I0000807" ON "APP"."TCATTR" ("TRADING_ID");

CREATE INDEX "APP"."I0000799" ON "APP"."STRELTYPDS" ("STRELTYP_ID");

CREATE UNIQUE INDEX "APP"."I0000148" ON "APP"."MASSOCCECE" ("STORE_ID", "MASSOCTYPE_ID", "MASSOC_ID", "CATENTRY_ID_FROM", "CATENTRY_ID_TO");

CREATE INDEX "APP"."I0000370" ON "APP"."MASSOCCECE" ("CATENTRY_ID_FROM");

CREATE INDEX "APP"."I0000610" ON "APP"."MASSOCCECE" ("CATENTRY_ID_TO");

CREATE INDEX "APP"."I0001317" ON "APP"."PX_CDUSAGE" ("PX_CDPOOL_ID");

CREATE INDEX "APP"."I0001318" ON "APP"."PX_CDUSAGE" ("OWNER_ID");

CREATE INDEX "APP"."I0001319" ON "APP"."PX_CDUSAGE" ("ORDERS_ID");

CREATE INDEX "APP"."I0001320" ON "APP"."PX_CDUSAGE" ("STATUS");

CREATE UNIQUE INDEX "APP"."I0000055" ON "APP"."CALMETHOD" ("SUBCLASS", "CALUSAGE_ID", "STOREENT_ID", "NAME");

CREATE INDEX "APP"."I0000501" ON "APP"."CALMETHOD" ("STOREENT_ID");

CREATE INDEX "APP"."I0000502" ON "APP"."CALMETHOD" ("CALUSAGE_ID");

CREATE INDEX "APP"."I0000294" ON "APP"."CATGRPREL" ("CATALOG_ID_LINK");

CREATE INDEX "APP"."I0000527" ON "APP"."CATGRPREL" ("CATALOG_ID");

CREATE INDEX "APP"."I0000528" ON "APP"."CATGRPREL" ("CATGROUP_ID_PARENT");

CREATE INDEX "APP"."I0000686" ON "APP"."PAYSUMMARY" ("ACCOUNT_ID");

CREATE INDEX "APP"."I0000687" ON "APP"."PAYSUMMARY" ("POLICY_ID");

CREATE INDEX "APP"."I0000689" ON "APP"."PAYSUMMARY" ("CREDITLINE_ID");

CREATE INDEX "APP"."I0000690" ON "APP"."PAYSUMMARY" ("STOREENT_ID");

CREATE INDEX "APP"."I0001372" ON "APP"."SUBSCRRENEW" ("SUBSCRIPTION_ID");

CREATE UNIQUE INDEX "APP"."I0001384" ON "APP"."SUBSCRIPTION" ("ORDERITEMS_ID", "ORDERS_ID");

CREATE INDEX "APP"."I0001360" ON "APP"."SUBSCRIPTION" ("CATENTRY_ID");

CREATE INDEX "APP"."I0001361" ON "APP"."SUBSCRIPTION" ("ORDERS_ID");

CREATE INDEX "APP"."I0001362" ON "APP"."SUBSCRIPTION" ("STOREENT_ID");

CREATE INDEX "APP"."I0001363" ON "APP"."SUBSCRIPTION" ("MEMBER_ID");

CREATE INDEX "APP"."I0001364" ON "APP"."SUBSCRIPTION" ("SUBSCPTYPE_ID");

CREATE INDEX "APP"."I0001365" ON "APP"."SUBSCRIPTION" ("SUBSCRTEMPLATE_ID");

CREATE INDEX "APP"."I0001404" ON "APP"."SUBSCRIPTION" ("FFMFREQ_UOM");

CREATE INDEX "APP"."I0001405" ON "APP"."SUBSCRIPTION" ("PAYMENTFREQ_UOM");

CREATE INDEX "APP"."I0001406" ON "APP"."SUBSCRIPTION" ("TIMEPERIOD_UOM");

CREATE UNIQUE INDEX "APP"."I0000860" ON "APP"."ATCHREL" ("ATCHOBJTYP_ID", "OBJECT_ID", "ATCHRLUS_ID", "ATCHTGT_ID");

CREATE INDEX "APP"."I0000873" ON "APP"."ATCHREL" ("ATCHOBJTYP_ID");

CREATE INDEX "APP"."I0000874" ON "APP"."ATCHREL" ("ATCHTGT_ID");

CREATE INDEX "APP"."I0000877" ON "APP"."ATCHREL" ("ATCHRLUS_ID");

CREATE INDEX "APP"."I0001207" ON "APP"."ATCHREL" ("BIGINTOBJECT_ID");

CREATE INDEX "APP"."I0001260" ON "APP"."INVRESERVE" ("ITEMSPC_ID", "STORE_ID", "FFMCENTER_ID");

CREATE UNIQUE INDEX "APP"."I0000064" ON "APP"."CATENTRY" ("PARTNUMBER", "MEMBER_ID");

CREATE INDEX "APP"."I0000065" ON "APP"."CATENTRY" ("CATENTRY_ID", "MARKFORDELETE");

CREATE INDEX "APP"."I263121" ON "APP"."CATENTRY" ("ITEMSPC_ID");

CREATE INDEX "APP"."I263122" ON "APP"."CATENTRY" ("BASEITEM_ID");

CREATE INDEX "APP"."I263103" ON "APP"."CATENTRY" ("CATENTRY_ID", "CATENTTYPE_ID");

CREATE INDEX "APP"."I0000305" ON "APP"."CATENTRY" ("BUYABLE", "CATENTRY_ID", "CATENTTYPE_ID");

CREATE INDEX "APP"."I0000375" ON "APP"."CATENTRY" ("RANK");

CREATE INDEX "APP"."I0000518" ON "APP"."CATENTRY" ("CATENTTYPE_ID");

CREATE INDEX "APP"."I0000519" ON "APP"."CATENTRY" ("MEMBER_ID");

CREATE INDEX "APP"."I0000791" ON "APP"."STOREITEM" ("STOREENT_ID");

CREATE INDEX "APP"."I0000047" ON "APP"."BIDPAYMENT" ("TYPE");

CREATE INDEX "APP"."I0000480" ON "APP"."BIDPAYMENT" ("BID_ID");

CREATE INDEX "APP"."I0001246" ON "APP"."BIDPAYMENT" ("AUCPAYINFO_ID");

CREATE UNIQUE INDEX "APP"."I0000132" ON "APP"."IITEMLIST" ("IITEMLIST_ID", "SEQUENCE", "MEMBER_ID");

CREATE UNIQUE INDEX "APP"."I0000133" ON "APP"."IITEMLIST" ("IITEMLIST_ID", "MEMBER_ID");

CREATE INDEX "APP"."I0000587" ON "APP"."IITEMLIST" ("MEMBER_ID");

CREATE INDEX "APP"."I0000251" ON "APP"."TMPCMPLIST" ("SID");

CREATE INDEX "APP"."I0000510" ON "APP"."CALSCALEDS" ("CALSCALE_ID");

CREATE INDEX "APP"."I0000252" ON "APP"."TMPFFCLIST" ("SID");

CREATE INDEX "APP"."I0000655" ON "APP"."ORDERTMPL" ("ORDERS_ID");

CREATE UNIQUE INDEX "APP"."I0000882" ON "APP"."CMFTASKGRP" ("IDENTIFIER");

CREATE INDEX "APP"."I0000883" ON "APP"."CMFTASKGRP" ("STATUS");

CREATE INDEX "APP"."I0000884" ON "APP"."CMFTASKGRP" ("TEMPLATETYPE");

CREATE INDEX "APP"."I0000265" ON "APP"."WCSDICTNRY" ("NAME");

CREATE INDEX "APP"."I0000266" ON "APP"."WCSDICTNRY" ("META");

CREATE UNIQUE INDEX "APP"."I0000197" ON "APP"."PVCSESSION" ("TERMINAL", "SESSIONTYPE");

CREATE INDEX "APP"."I0000708" ON "APP"."PVCSESSION" ("REGISTER_ID");

CREATE INDEX "APP"."I0001396" ON "APP"."SRCHTERMASSOC" ("STOREENT_ID");

CREATE INDEX "APP"."I0001397" ON "APP"."SRCHTERMASSOC" ("LANGUAGE_ID");

CREATE INDEX "APP"."I0001398" ON "APP"."SRCHTERMASSOC" ("SCOPE");

CREATE INDEX "APP"."I0001399" ON "APP"."SRCHTERMASSOC" ("STATUS");

CREATE UNIQUE INDEX "APP"."I0000255" ON "APP"."TRADEPOSCN" ("MEMBER_ID", "NAME");

CREATE INDEX "APP"."I442156" ON "APP"."TRADEPOSCN" ("TRADEPOSCN_ID", "TYPE");

CREATE INDEX "APP"."I0000814" ON "APP"."TRADEPOSCN" ("PRODUCTSET_ID");

CREATE UNIQUE INDEX "APP"."I0001351" ON "APP"."PRCONSTANT" ("IDENTIFIER", "STOREENT_ID");

CREATE INDEX "APP"."I0001352" ON "APP"."PRCONSTANT" ("STOREENT_ID");

CREATE INDEX "APP"."I0001353" ON "APP"."PRCONSTANT" ("TYPE");

CREATE UNIQUE INDEX "APP"."I0000071" ON "APP"."CHARGETYPE" ("STOREENT_ID", "CODE");

CREATE UNIQUE INDEX "APP"."I0000144" ON "APP"."KEYS" ("TABLENAME");

CREATE INDEX "APP"."I0001239" ON "APP"."AUCTSTRREL" ("AUCT_ID");

CREATE UNIQUE INDEX "APP"."I0000102" ON "APP"."FLINSTANCE" ("FLOW_ID", "ENTITY_ID");

CREATE UNIQUE INDEX "APP"."I0000080" ON "APP"."CONTRLRULE" ("RULENAME", "OWNER_ID");

CREATE INDEX "APP"."I0000081" ON "APP"."CONTRLRULE" ("RULETYPE");

CREATE INDEX "APP"."I0000540" ON "APP"."CONTRLRULE" ("ADMIN_ID");

CREATE INDEX "APP"."I0000541" ON "APP"."CONTRLRULE" ("OWNER_ID");

CREATE INDEX "APP"."I0001250" ON "APP"."CONTRLRULE" ("CLASS_ID");

CREATE INDEX "APP"."I0000173" ON "APP"."ORDERITEMS" ("ORDERITEMS_ID", "TIMERELEASED", "TIMESHIPPED", "INVENTORYSTATUS");

CREATE INDEX "APP"."I0000642" ON "APP"."ORDERITEMS" ("SHIPMODE_ID");

CREATE INDEX "APP"."I0000643" ON "APP"."ORDERITEMS" ("FFMCENTER_ID");

CREATE INDEX "APP"."I0000644" ON "APP"."ORDERITEMS" ("OFFER_ID");

CREATE INDEX "APP"."I0000645" ON "APP"."ORDERITEMS" ("CATENTRY_ID");

CREATE INDEX "APP"."I0000646" ON "APP"."ORDERITEMS" ("MEMBER_ID");

CREATE INDEX "APP"."I0000647" ON "APP"."ORDERITEMS" ("ADDRESS_ID");

CREATE INDEX "APP"."I0000648" ON "APP"."ORDERITEMS" ("ITEMSPC_ID");

CREATE INDEX "APP"."I0000649" ON "APP"."ORDERITEMS" ("ALLOCFFMC_ID");

CREATE INDEX "APP"."I172138" ON "APP"."ORDERITEMS" ("ORDERS_ID", "ORDRELEASENUM", "STOREENT_ID", "FFMCENTER_ID");

CREATE INDEX "APP"."I0000360" ON "APP"."ORDERITEMS" ("ORDERITEMS_ID", "ORDRELEASENUM", "ORDERS_ID");

CREATE INDEX "APP"."I0000369" ON "APP"."ORDERITEMS" ("STOREENT_ID");

CREATE INDEX "APP"."I0000639" ON "APP"."ORDERITEMS" ("ALLOCADDRESS_ID");

CREATE INDEX "APP"."I0000640" ON "APP"."ORDERITEMS" ("TRADING_ID");

CREATE INDEX "APP"."I0000641" ON "APP"."ORDERITEMS" ("TERMCOND_ID");

CREATE INDEX "APP"."I0000216" ON "APP"."RMAITEMCMP" ("RMAITEM_ID", "RMAITEMCMP_ID", "SHOULDRECEIVE");

CREATE INDEX "APP"."I838141" ON "APP"."RMAITEMCMP" ("ITEMSPC_ID", "RMAITEM_ID", "INVQUANTITY");

CREATE INDEX "APP"."I0000750" ON "APP"."RMAITEMCMP" ("CATENTRY_ID");

CREATE UNIQUE INDEX "APP"."I0000300" ON "APP"."REFKEYS" ("TABLENAME", "FKTABLE_NAME", "FKCOLUMN_NAME");

CREATE INDEX "APP"."I0001370" ON "APP"."SUBSCRTMPLITEMLIST" ("CATENTRY_ID");

CREATE UNIQUE INDEX "APP"."I0000219" ON "APP"."RTNDSPCODE" ("CODE", "STOREENT_ID");

CREATE INDEX "APP"."I0000752" ON "APP"."RTNDSPCODE" ("STOREENT_ID");

CREATE INDEX "APP"."I0000354" ON "APP"."PATTRVALUE" ("TERMCOND_ID");

CREATE INDEX "APP"."I0000355" ON "APP"."PATTRVALUE" ("RFQPROD_ID");

CREATE INDEX "APP"."I0000356" ON "APP"."PATTRVALUE" ("RFQRSPPROD_ID");

CREATE INDEX "APP"."I0000367" ON "APP"."PATTRVALUE" ("CORRELATIONGROUP");

CREATE INDEX "APP"."I0000682" ON "APP"."PATTRVALUE" ("PATTRIBUTE_ID");

CREATE INDEX "APP"."I0000683" ON "APP"."PATTRVALUE" ("ORDERITEMS_ID");

CREATE INDEX "APP"."I0001270" ON "APP"."PATTRVALUE" ("ATTACHMENT_ID");

CREATE UNIQUE INDEX "APP"."I0000122" ON "APP"."ICMERTREE" ("METAPHORID");

CREATE INDEX "APP"."I0000579" ON "APP"."ICMERTREE" ("STOREID");

CREATE INDEX "APP"."I0000770" ON "APP"."STENCALUSG" ("ACTCC_CALMETHOD_ID");

CREATE INDEX "APP"."I0000771" ON "APP"."STENCALUSG" ("CALUSAGE_ID");

CREATE INDEX "APP"."I0000772" ON "APP"."STENCALUSG" ("CALMETHOD_ID_APP");

CREATE INDEX "APP"."I0000773" ON "APP"."STENCALUSG" ("CALMETHOD_ID_INI");

CREATE INDEX "APP"."I0000774" ON "APP"."STENCALUSG" ("CALMETHOD_ID_FIN");

CREATE INDEX "APP"."I0000775" ON "APP"."STENCALUSG" ("CALMETHOD_ID_SUM");

CREATE INDEX "APP"."I0000776" ON "APP"."STENCALUSG" ("CALCODE_ID");

CREATE INDEX "APP"."I0000777" ON "APP"."STENCALUSG" ("ACTRC_CALMETHOD_ID");

CREATE INDEX "APP"."I0000976" ON "APP"."RMAITEMSERIAL" ("RMAITEM_ID", "RMAITEMCMP_ID");

CREATE INDEX "APP"."I0000977" ON "APP"."RMAITEMSERIAL" ("SERIALNUMBER");

CREATE INDEX "APP"."I0001283" ON "APP"."RMAITEMSERIAL" ("RMAITEMCMP_ID");

CREATE UNIQUE INDEX "APP"."I0000937" ON "APP"."TKLRACTION" ("CODE", "STORE_ID");

CREATE INDEX "APP"."I0000947" ON "APP"."TKLRACTION" ("STORE_ID");

CREATE UNIQUE INDEX "APP"."I0000198" ON "APP"."QTYCONVERT" ("QTYUNIT_ID_TO", "QTYUNIT_ID_FROM");

CREATE INDEX "APP"."I0000576" ON "APP"."FORUM" ("OWNER_ID");

CREATE INDEX "APP"."I0000577" ON "APP"."FORUM" ("MBRGRP_ID");

CREATE UNIQUE INDEX "APP"."I0000236" ON "APP"."STDOMAIN" ("STDY", "STIPAD", "STMRFNBR", "STLOGID", "STCFRNBR");

CREATE INDEX "APP"."I0001261" ON "APP"."MBRVIEWPRF" ("PREFERENCE");

CREATE UNIQUE INDEX "APP"."I0001373" ON "APP"."CATFILTER" ("STOREENT_ID", "IDENTIFIER", "CATALOG_ID");

CREATE INDEX "APP"."I0001374" ON "APP"."CATFILTER" ("STOREENT_ID", "CATALOG_ID");

CREATE INDEX "APP"."I0001375" ON "APP"."CATFILTER" ("CATALOG_ID");

CREATE INDEX "APP"."I0000402" ON "APP"."PX_PROMOPOLICY" ("PX_PROMOTION_ID");

CREATE INDEX "APP"."I0000403" ON "APP"."PX_PROMOPOLICY" ("PX_POLICY_ID");

CREATE INDEX "APP"."I0001195" ON "APP"."DMTRIGSND" ("TIMETOSEND");

CREATE INDEX "APP"."I0000578" ON "APP"."ICMERDESC" ("TREEID");

CREATE UNIQUE INDEX "APP"."I0000164" ON "APP"."NUMBRUSG" ("CODE");

CREATE UNIQUE INDEX "APP"."I0000072" ON "APP"."CLASIFCODE" ("CODE", "DOMAIN");

CREATE UNIQUE INDEX "APP"."I0000075" ON "APP"."CNTRDISPLY" ("CONTRACT_ID", "DEVICEFMT_ID", "PARTROLE_ID");

CREATE UNIQUE INDEX "APP"."I0000088" ON "APP"."DBMEASFM" ("DBMFREF", "DBMFVIEW");

CREATE INDEX "APP"."I0000788" ON "APP"."STOREENTDS" ("STADDRESS_ID_LOC");

CREATE INDEX "APP"."I0000789" ON "APP"."STOREENTDS" ("STADDRESS_ID_CONT");

CREATE INDEX "APP"."I0000790" ON "APP"."STOREENTDS" ("STOREENT_ID");

CREATE INDEX "APP"."I0000168" ON "APP"."OFFERPRICE" ("PRICE", "CURRENCY", "OFFER_ID");

CREATE INDEX "APP"."I0000534" ON "APP"."CHKCMD" ("STOREENT_ID");

CREATE INDEX "APP"."I0000829" ON "APP"."VENDORDESC" ("STADDRESS_ID");

CREATE INDEX "APP"."I0000250" ON "APP"."TMPBOLIST" ("SID");

CREATE UNIQUE INDEX "APP"."I0001139" ON "APP"."DMCAMPAIGN" ("NAME", "STOREENT_ID");

CREATE INDEX "APP"."I0001140" ON "APP"."DMCAMPAIGN" ("STOREENT_ID");

CREATE INDEX "APP"."I0001194" ON "APP"."DMELEMENTNVP" ("NAME", "VALUE");

CREATE UNIQUE INDEX "APP"."I0001326" ON "APP"."INSRULE" ("STOREENT_ID", "NAME");

CREATE INDEX "APP"."I0000334" ON "APP"."ICCONSTRNT" ("FEATUREID");

CREATE INDEX "APP"."I0000335" ON "APP"."ICCONSTRNT" ("CONCEPTID");

CREATE UNIQUE INDEX "APP"."I0000008" ON "APP"."ACRELGRP" ("GRPNAME", "MEMBER_ID");

CREATE INDEX "APP"."I0000442" ON "APP"."ACRELGRP" ("MEMBER_ID");

CREATE UNIQUE INDEX "APP"."I0000425" ON "APP"."WMMMAP" ("MEMBER_UNIQUE_ID");

CREATE INDEX "APP"."I0000785" ON "APP"."STOREDEF" ("CONTRACT_ID");

CREATE INDEX "APP"."I0000786" ON "APP"."STOREDEF" ("SHIPMODE_ID");

CREATE INDEX "APP"."I0000718" ON "APP"."REFUNDMTHD" ("ORDERS_ID");

CREATE INDEX "APP"."I0000719" ON "APP"."REFUNDMTHD" ("TRADING_ID");

CREATE INDEX "APP"."I0000720" ON "APP"."REFUNDMTHD" ("CREDITLINE_ID");

CREATE INDEX "APP"."I0000721" ON "APP"."REFUNDMTHD" ("POLICY_ID");

CREATE INDEX "APP"."I0000722" ON "APP"."REFUNDMTHD" ("PAYSUMMARY_ID");

CREATE INDEX "APP"."I0000723" ON "APP"."REFUNDMTHD" ("ACCOUNT_ID");

CREATE UNIQUE INDEX "APP"."I775148" ON "APP"."PVCDEVSPEC" ("SPECNAME");

CREATE UNIQUE INDEX "APP"."I0001416" ON "APP"."CMPRMYOBJ" ("WORKSPACE", "TASKGRP", "NOUN", "OBJECT_ID", "STOREENT_ID");

CREATE INDEX "APP"."I0001418" ON "APP"."CMPRMYOBJ" ("STATUS", "LASTUPDATE");

CREATE INDEX "APP"."I0001427" ON "APP"."CMPRMYOBJ" ("NOUN", "OBJECT_ID");

CREATE INDEX "APP"."I0001428" ON "APP"."CMPRMYOBJ" ("STOREENT_ID");

CREATE INDEX "APP"."I0001419" ON "APP"."CMPRMYOBJ" ("LASTUPDATE", "NOUN", "STOREENT_ID", "WORKSPACE", "ACTION", "SOURCE");

CREATE UNIQUE INDEX "APP"."I0000246" ON "APP"."TERMCOND" ("TRADING_ID", "SEQUENCE");

CREATE INDEX "APP"."I0000810" ON "APP"."TERMCOND" ("TCSUBTYPE_ID");

CREATE INDEX "APP"."I0001415" ON "APP"."SEOPAGEDEFSUBPARAM" ("STOREENT_ID");

CREATE INDEX "APP"."I0000454" ON "APP"."AUCPAYINFO" ("MEMBER_ID");

CREATE UNIQUE INDEX "APP"."I0000004" ON "APP"."ACCCMDGRP" ("MBRGRP_ID", "INTERFACENAME", "VIEWNAME", "ACCCMDTYPE_ID");

CREATE UNIQUE INDEX "APP"."I0000429" ON "APP"."CMLARGEFILE" ("CMFILE_ID", "CONTENT_WORKSPACE");

CREATE UNIQUE INDEX "APP"."I0000191" ON "APP"."PRODUCTSET" ("NAME", "MEMBER_ID");

CREATE INDEX "APP"."I0000700" ON "APP"."PRODUCTSET" ("MEMBER_ID");

CREATE UNIQUE INDEX "APP"."I0000076" ON "APP"."CNTRNAME" ("NAME", "MEMBER_ID", "ORIGIN");

CREATE INDEX "APP"."I0000537" ON "APP"."CNTRNAME" ("MEMBER_ID");

CREATE INDEX "APP"."I0000499" ON "APP"."CALCODEMGP" ("MBRGRP_ID");

CREATE INDEX "APP"."I9221181" ON "APP"."APRVSTATUS" ("APPROVER_ID", "STATUS", "SUBMITTER_ID", "FLOWTYPE_ID");

CREATE INDEX "APP"."I9221180" ON "APP"."APRVSTATUS" ("SUBMITTER_ID", "APPROVER_ID", "FLOWTYPE_ID", "STATUS");

CREATE INDEX "APP"."I922110" ON "APP"."APRVSTATUS" ("FLOW_ID", "ENTITY_ID");

CREATE INDEX "APP"."I0000451" ON "APP"."APRVSTATUS" ("MBRGRP_ID");

CREATE UNIQUE INDEX "APP"."I0000083" ON "APP"."CURCONVERT" ("FROMCURR", "TOCURR", "STOREENT_ID");

CREATE INDEX "APP"."I0000551" ON "APP"."CURCONVERT" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000235" ON "APP"."STDCNTRY" ("STCNTRY");

CREATE UNIQUE INDEX "APP"."I0000257" ON "APP"."TRDDEPAMT" ("TRADING_ID", "ORDERS_ID", "ORDERITEMS_ID");

CREATE INDEX "APP"."I0000816" ON "APP"."TRDDEPAMT" ("ORDERS_ID");

CREATE INDEX "APP"."I0000817" ON "APP"."TRDDEPAMT" ("ORDERITEMS_ID");

CREATE INDEX "APP"."I0000847" ON "APP"."EDPRELEASE" ("EDPORDER_ID");

CREATE UNIQUE INDEX "APP"."I0000100" ON "APP"."EMSPOT" ("NAME", "STOREENT_ID", "USAGETYPE");

CREATE INDEX "APP"."I0000568" ON "APP"."EMSPOT" ("STOREENT_ID");

CREATE INDEX "APP"."I0000145" ON "APP"."LISTPRICE" ("CURRENCY", "CATENTRY_ID", "LISTPRICE");

CREATE INDEX "APP"."I0000604" ON "APP"."LISTPRICE" ("CATENTRY_ID");

CREATE UNIQUE INDEX "APP"."I0000049" ON "APP"."BZRPENTAT" ("BZRPENT_ID", "NAME");

CREATE INDEX "APP"."I0000423" ON "APP"."PX_TPLTGRP" ("PX_TEMPLATE_ID");

CREATE INDEX "APP"."I0000424" ON "APP"."PX_TPLTGRP" ("PX_GROUP_ID");

CREATE INDEX "APP"."I0000033" ON "APP"."AUCTSTYLE" ("ASTYPE");

CREATE INDEX "APP"."I0000465" ON "APP"."AUCTSTYLE" ("ADMIN_ID");

CREATE INDEX "APP"."I0000466" ON "APP"."AUCTSTYLE" ("RULE_ID");

CREATE UNIQUE INDEX "APP"."I0000420" ON "APP"."PX_TEMPLATE" ("STOREENT_ID", "NAME");

CREATE UNIQUE INDEX "APP"."I0000258" ON "APP"."TXCDCLASS" ("STOREENT_ID", "NAME");

CREATE INDEX "APP"."I0000815" ON "APP"."TRADING" ("TRDTYPE_ID");

CREATE UNIQUE INDEX "APP"."I0000106" ON "APP"."FLOWTYPE" ("IDENTIFIER");

CREATE INDEX "APP"."I0000362" ON "APP"."ORDPICKHST" ("ORDERITEMS_ID", "VERSIONSPC_ID", "QTYPICKED");

CREATE INDEX "APP"."I0000671" ON "APP"."ORDPICKHST" ("RECEIPT_ID");

CREATE INDEX "APP"."I0000672" ON "APP"."ORDPICKHST" ("VERSIONSPC_ID");

CREATE UNIQUE INDEX "APP"."I0000297" ON "APP"."RFQCATEGRY" ("RFQ_ID", "NAME");

CREATE UNIQUE INDEX "APP"."I0000856" ON "APP"."ATCHAST" ("STOREENT_ID", "ATCHTGT_ID", "ATCHASTPATH");

CREATE INDEX "APP"."I0000857" ON "APP"."ATCHAST" ("STOREENT_ID", "DIRECTORYPATH");

CREATE INDEX "APP"."I0000867" ON "APP"."ATCHAST" ("STOREENT_ID");

CREATE INDEX "APP"."I0000868" ON "APP"."ATCHAST" ("ATCHTGT_ID");

CREATE UNIQUE INDEX "APP"."I0000855" ON "APP"."ATCHTGTDSC" ("ATCHTGT_ID", "LANGUAGE_ID");

CREATE INDEX "APP"."I0000865" ON "APP"."ATCHTGTDSC" ("ATCHTGT_ID");

CREATE INDEX "APP"."I0000866" ON "APP"."ATCHTGTDSC" ("LANGUAGE_ID");

CREATE INDEX "APP"."I0001208" ON "APP"."ATCHTGTDSC" ("NAME");

CREATE INDEX "APP"."I0000261" ON "APP"."USRTRAFFIC" ("USRTRAFFIC_ID", "STMP");

CREATE INDEX "APP"."I0000373" ON "APP"."CATTOGRP" ("CATALOG_ID_LINK");

CREATE INDEX "APP"."I0000532" ON "APP"."CATTOGRP" ("CATGROUP_ID");

CREATE UNIQUE INDEX "APP"."I0000885" ON "APP"."CMFTASK" ("IDENTIFIER");

CREATE INDEX "APP"."I0000886" ON "APP"."CMFTASK" ("STATUS");

CREATE INDEX "APP"."I0000887" ON "APP"."CMFTASK" ("TYPE");

CREATE INDEX "APP"."I0000307" ON "APP"."NOTIFY" ("NOTIFICATIONID");

CREATE INDEX "APP"."I0000625" ON "APP"."NOTIFY" ("MSGTYPE_ID");

CREATE INDEX "APP"."I0001411" ON "APP"."SEOPAGEDEFDESC" ("LANGUAGE_ID");

CREATE UNIQUE INDEX "APP"."I0001214" ON "APP"."STLOCDS" ("STLOC_ID", "LANGUAGE_ID");

CREATE INDEX "APP"."I0000844" ON "APP"."EDPPAYINST" ("EDPORDER_ID");

CREATE INDEX "APP"."I0000845" ON "APP"."EDPPAYINST" ("BACKENDPIID");

CREATE UNIQUE INDEX "APP"."I0001379" ON "APP"."CFCATGROUP" ("CATFILTER_ID", "CATGROUP_ID");

CREATE INDEX "APP"."I0001387" ON "APP"."CFCATGROUP" ("CATGROUP_ID");

CREATE INDEX "APP"."I0000804" ON "APP"."TAXCGRYDS" ("TAXCGRY_ID");

CREATE INDEX "APP"."I0000281" ON "APP"."TCPITMAP" ("ORDERITEMS_ID");

CREATE INDEX "APP"."I0000111" ON "APP"."FORUMMSG" ("POSTER_ID");

CREATE INDEX "APP"."I0000112" ON "APP"."FORUMMSG" ("TARGET_ID");

CREATE INDEX "APP"."I0000113" ON "APP"."FORUMMSG" ("MSGSTATUS");

CREATE INDEX "APP"."I0000114" ON "APP"."FORUMMSG" ("VIEWSTATUS");

CREATE INDEX "APP"."I0001258" ON "APP"."FORUMMSG" ("FORUM_ID");

CREATE INDEX "APP"."I0001294" ON "APP"."FORUMMSG" ("PARENTMSG_ID");

CREATE INDEX "APP"."I0001295" ON "APP"."FORUMMSG" ("ROOTMSG_ID");

CREATE UNIQUE INDEX "APP"."I0000050" ON "APP"."BZRPENTSTG" ("BZRPENT_ID", "SEQUENCE");

CREATE UNIQUE INDEX "APP"."I0001215" ON "APP"."GEONODE" ("IDENTIFIER");

CREATE INDEX "APP"."I0001289" ON "APP"."STOREMERCH" ("MERCHANT_ID");

CREATE UNIQUE INDEX "APP"."I0000096" ON "APP"."ECEOUT" ("ECREFNUM");

CREATE UNIQUE INDEX "APP"."I0000097" ON "APP"."ECEOUT" ("ECTYPE", "ECREQNUM");

CREATE INDEX "APP"."I0000562" ON "APP"."ECEOUT" ("STORE_ID");

CREATE INDEX "APP"."I0000512" ON "APP"."CATALOGDSC" ("CATALOG_ID");

CREATE UNIQUE INDEX "APP"."I0000066" ON "APP"."CATGPCALCD" ("STORE_ID", "CATGROUP_ID", "CALCODE_ID", "TRADING_ID");

CREATE INDEX "APP"."I0000520" ON "APP"."CATGPCALCD" ("CALCODE_ID");

CREATE INDEX "APP"."I0000521" ON "APP"."CATGPCALCD" ("CATGROUP_ID");

CREATE INDEX "APP"."I0000522" ON "APP"."CATGPCALCD" ("TRADING_ID");

CREATE INDEX "APP"."I0000441" ON "APP"."ACPOLSUBGP" ("PARENT_ID");

CREATE UNIQUE INDEX "APP"."I0000040" ON "APP"."BASEITEM" ("MEMBER_ID", "PARTNUMBER");

CREATE UNIQUE INDEX "APP"."I0000206" ON "APP"."REPORT" ("RPTRFNBR");

CREATE INDEX "APP"."I0001281" ON "APP"."RMAIDNYRSN" ("RTNDNYRSN_ID");

CREATE UNIQUE INDEX "APP"."I0001343" ON "APP"."PRELETEMPLATE" ("PRELETPLTGRP_ID", "IDENTIFIER", "STOREENT_ID");

CREATE INDEX "APP"."I0001344" ON "APP"."PRELETEMPLATE" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000244" ON "APP"."TAXCGRY" ("NAME", "STOREENT_ID");

CREATE INDEX "APP"."I0000803" ON "APP"."TAXCGRY" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000228" ON "APP"."SHIPMODE" ("STOREENT_ID", "CODE", "CARRIER");

CREATE INDEX "APP"."I0001255" ON "APP"."DKPDCCATENTREL" ("CATENTRY_ID");

CREATE INDEX "APP"."I0000282" ON "APP"."CPPMNPROD" ("CATENTRY_ID");

CREATE UNIQUE INDEX "APP"."I0000017" ON "APP"."ATTACHMENT" ("ATTACHMENTURL");

CREATE INDEX "APP"."I0000290" ON "APP"."ATTACHMENT" ("ATTACHUSG_ID");

CREATE INDEX "APP"."I0000452" ON "APP"."ATTACHMENT" ("MEMBER_ID");

CREATE UNIQUE INDEX "APP"."I0000200" ON "APP"."RA" ("STORE_ID", "VENDOR_ID", "CREATETIME");

CREATE INDEX "APP"."I0001275" ON "APP"."RA" ("VENDOR_ID");

CREATE INDEX "APP"."I0000693" ON "APP"."PKGITEMREL" ("CATENTRY_ID_PARENT");

CREATE INDEX "APP"."I0000694" ON "APP"."PKGITEMREL" ("CATENTRY_ID_PKG");

CREATE INDEX "APP"."I0000161" ON "APP"."MSGMEMREL" ("STATUS");

CREATE INDEX "APP"."I0000162" ON "APP"."MSGMEMREL" ("SENDSTAT");

CREATE INDEX "APP"."I0000623" ON "APP"."MSGMEMREL" ("MEMBER_ID");

CREATE INDEX "APP"."I0000222" ON "APP"."RTNRECEIPT" ("RMAITEMCMP_ID", "RTNRECEIPT_ID", "DATERECEIVED");

CREATE INDEX "APP"."I0000754" ON "APP"."RTNRECEIPT" ("VERSIONSPC_ID");

CREATE INDEX "APP"."I0000755" ON "APP"."RTNRECEIPT" ("RMA_ID");

CREATE INDEX "APP"."I0000299" ON "APP"."CACHEIVL" ("INSERTTIME");

CREATE INDEX "APP"."I0000890" ON "APP"."CMFTGCMT" ("CMFTASKGRP_ID");

CREATE INDEX "APP"."I0000891" ON "APP"."CMFTGCMT" ("MEMBER_ID");

CREATE INDEX "APP"."I0000597" ON "APP"."ITEMFFMCTR" ("FFMCENTER_ID");

CREATE INDEX "APP"."I0000598" ON "APP"."ITEMFFMCTR" ("STORE_ID");

CREATE INDEX "APP"."I0000966" ON "APP"."OICOMPREL" ("ORDERITEMS_ID");

CREATE INDEX "APP"."I0000963" ON "APP"."OICOMPREL" ("ITEMSPC_ID");

CREATE INDEX "APP"."I0000964" ON "APP"."OICOMPREL" ("PARENT_ID");

CREATE INDEX "APP"."I0001101" ON "APP"."OICOMPREL" ("CONFIGURATION_ID", "ORDERITEMS_ID");

CREATE UNIQUE INDEX "APP"."I0001163" ON "APP"."DMEMSPOTDEF" ("EMSPOT_ID", "STOREENT_ID", "CONTENTTYPE", "CONTENT");

CREATE INDEX "APP"."I0001164" ON "APP"."DMEMSPOTDEF" ("STOREENT_ID");

CREATE INDEX "APP"."I0000344" ON "APP"."TAXTYPE" ("SEQUENCE", "TXCDSCHEME_ID", "TAXTYPE_ID");

CREATE INDEX "APP"."I0000483" ON "APP"."BUACCTDET" ("ORDERS_ID");

CREATE UNIQUE INDEX "APP"."I0001349" ON "APP"."PREQUATION" ("IDENTIFIER", "STOREENT_ID");

CREATE INDEX "APP"."I0001350" ON "APP"."PREQUATION" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000118" ON "APP"."ICEXPLFEAT" ("CATGROUP_ID", "COLUMNNAME");

CREATE INDEX "APP"."I0000119" ON "APP"."ICEXPLFEAT" ("COLUMNNAME");

CREATE INDEX "APP"."I0001262" ON "APP"."MERCHANT" ("MEMBER_ID");

CREATE INDEX "APP"."I0000291" ON "APP"."CATGRPPS" ("CATALOG_ID", "CATGROUP_ID", "USAGE");

CREATE INDEX "APP"."I0000292" ON "APP"."CATGRPPS" ("PRODUCTSET_ID", "USAGE");

CREATE INDEX "APP"."I0000526" ON "APP"."CATGRPPS" ("CATGROUP_ID");

CREATE INDEX "APP"."I0000315" ON "APP"."CPGNSTATS" ("MPE_ID");

CREATE INDEX "APP"."I0000691" ON "APP"."PICKBATCH" ("MEMBER_ID");

CREATE INDEX "APP"."I0000692" ON "APP"."PICKBATCH" ("FFMCENTER_ID");

CREATE INDEX "APP"."I0000015" ON "APP"."ADDRESS" ("ADDRBOOK_ID", "ADDRESSTYPE", "ISPRIMARY", "STATUS");

CREATE INDEX "APP"."I0000016" ON "APP"."ADDRESS" ("MEMBER_ID", "STATUS", "SELFADDRESS", "ADDRESSTYPE", "ISPRIMARY");

CREATE INDEX "APP"."I0000346" ON "APP"."ADDRESS" ("LASTNAME");

CREATE UNIQUE INDEX "APP"."I0000092" ON "APP"."DISPENTREL" ("DEVICEFMT_ID", "STOREENT_ID", "CATENTRY_ID", "CATENTTYPE_ID", "MBRGRP_ID", "AUCTIONSTATE", "RANK", "LANGUAGE_ID");

CREATE INDEX "APP"."I0000093" ON "APP"."DISPENTREL" ("AUCTIONSTATE", "MBRGRP_ID", "CATENTRY_ID", "STOREENT_ID");

CREATE INDEX "APP"."I0000094" ON "APP"."DISPENTREL" ("CATENTRY_ID", "CATENTTYPE_ID", "STOREENT_ID", "MBRGRP_ID");

CREATE INDEX "APP"."I0000557" ON "APP"."DISPENTREL" ("CATENTTYPE_ID");

CREATE INDEX "APP"."I0000558" ON "APP"."DISPENTREL" ("MBRGRP_ID");

CREATE INDEX "APP"."I0000559" ON "APP"."DISPENTREL" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000105" ON "APP"."FLOWDOMAIN" ("IDENTIFIER");

CREATE INDEX "APP"."I0000171" ON "APP"."ORDADJUST" ("ORDERS_ID");

CREATE INDEX "APP"."I0000634" ON "APP"."ORDADJUST" ("CALUSAGE_ID");

CREATE INDEX "APP"."I0000635" ON "APP"."ORDADJUST" ("CALCODE_ID");

CREATE INDEX "APP"."I0000636" ON "APP"."ORDBTB" ("ORDERS_ID");

CREATE INDEX "APP"."I0000339" ON "APP"."EMLPROMO" ("STOREENT_ID");

CREATE INDEX "APP"."I0000564" ON "APP"."EMLPROMO" ("EMLMSG_ID");

CREATE INDEX "APP"."I0000565" ON "APP"."EMLPROMO" ("SCCJOBREFNUM");

CREATE INDEX "APP"."I0000792" ON "APP"."STORELANG" ("STOREENT_ID");

CREATE INDEX "APP"."I0000410" ON "APP"."CLCDPROMO" ("PX_PROMOTION_ID");

CREATE INDEX "APP"."I0000411" ON "APP"."CLCDPROMO" ("CALCODE_ID");

CREATE UNIQUE INDEX "APP"."I0000082" ON "APP"."CSEDITATT" ("TRANSPORT_ID", "STORE_ID", "PROFILE_ID", "CONNSPECATTNAME");

CREATE INDEX "APP"."I0001253" ON "APP"."CSEDITATT" ("PROFILE_ID");

CREATE UNIQUE INDEX "APP"."I0000091" ON "APP"."DISPCGPREL" ("DEVICEFMT_ID", "STOREENT_ID", "CATGROUP_ID", "MBRGRP_ID", "RANK", "LANGUAGE_ID");

CREATE INDEX "APP"."I0000554" ON "APP"."DISPCGPREL" ("STOREENT_ID");

CREATE INDEX "APP"."I0000555" ON "APP"."DISPCGPREL" ("CATGROUP_ID");

CREATE INDEX "APP"."I0000556" ON "APP"."DISPCGPREL" ("MBRGRP_ID");

CREATE UNIQUE INDEX "APP"."I0000070" ON "APP"."CERT_X509" ("CTSERNUM", "CTISSORGNM", "CTSBJORGNM", "CTSBJCMNM");

CREATE INDEX "APP"."I0000624" ON "APP"."MSGSTORE" ("STOREENT_ID");

CREATE INDEX "APP"."I0000695" ON "APP"."PLCYACCT" ("PLCYACCLCK_ID");

CREATE INDEX "APP"."I0000696" ON "APP"."PLCYACCT" ("PLCYPASSWD_ID");

CREATE UNIQUE INDEX "APP"."I0001315" ON "APP"."PX_CDPROMO" ("PX_CDPOOL_ID", "PX_PROMOTION_ID");

CREATE INDEX "APP"."I0001316" ON "APP"."PX_CDPROMO" ("PX_PROMOTION_ID");

CREATE INDEX "APP"."I0000549" ON "APP"."CREDITLINE" ("ACCOUNT_ID");

CREATE INDEX "APP"."I0000584" ON "APP"."IITEM" ("CATENTRY_ID");

CREATE INDEX "APP"."I0000585" ON "APP"."IITEM" ("STOREENT_ID");

CREATE INDEX "APP"."I0000586" ON "APP"."IITEM" ("MEMBER_ID");

CREATE INDEX "APP"."I0000650" ON "APP"."ORDERMGP" ("MBRGRP_ID");

CREATE INDEX "APP"."I0000419" ON "APP"."ORDITPROMOCD" ("ORDERITEMS_ID");

CREATE INDEX "APP"."I0000365" ON "APP"."CATENTREL" ("CATENTRY_ID_CHILD", "CATRELTYPE_ID");

CREATE INDEX "APP"."I0000517" ON "APP"."CATENTREL" ("CATENTRY_ID_PARENT");

CREATE UNIQUE INDEX "APP"."I0000194" ON "APP"."PURCHASELT" ("TERMCOND_ID", "TRADEPOSCN_ID", "CATENTRY_ID");

CREATE INDEX "APP"."I0000704" ON "APP"."PURCHASELT" ("TRADEPOSCN_ID");

CREATE INDEX "APP"."I0000705" ON "APP"."PURCHASELT" ("CATENTRY_ID");

CREATE UNIQUE INDEX "APP"."I0000853" ON "APP"."ATCHOBJTYP" ("IDENTIFIER");

CREATE UNIQUE INDEX "APP"."I0000232" ON "APP"."STBRCODES" ("STCODE");

CREATE UNIQUE INDEX "APP"."I0000193" ON "APP"."PROFNVSTRG" ("PROFILE_ID", "PROFILEATTNAME");

CREATE UNIQUE INDEX "APP"."I0000143" ON "APP"."JURSTGROUP" ("CODE", "STOREENT_ID", "SUBCLASS");

CREATE INDEX "APP"."I0000602" ON "APP"."JURSTGROUP" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000120" ON "APP"."ICKNOWLEDG" ("TREEID", "PARENTCONCEPTID", "CLASSNAME", "ORDERSEQUENCE");

CREATE INDEX "APP"."I0000121" ON "APP"."ICKNOWLEDG" ("STOREID");

CREATE INDEX "APP"."I0001296" ON "APP"."ICKNOWLEDG" ("PARENTCONCEPTID");

CREATE INDEX "APP"."I0001392" ON "APP"."SRCHSTAT" ("STOREENT_ID", "LOGDATE");

CREATE INDEX "APP"."I0001391" ON "APP"."SRCHSTAT" ("KEYWORD", "LANGUAGE_ID", "STOREENT_ID", "KEYWORDCOUNT", "LOGDATE", "SEARCHCOUNT", "SUGGESTION");

CREATE INDEX "APP"."I0000326" ON "APP"."MBRATTRVAL" ("MEMBER_ID", "MBRATTR_ID");

CREATE INDEX "APP"."I0000327" ON "APP"."MBRATTRVAL" ("STOREENT_ID");

CREATE INDEX "APP"."I0000614" ON "APP"."MBRATTRVAL" ("MBRATTR_ID");

CREATE INDEX "APP"."I0000924" ON "APP"."PPCPAYTRAN" ("PPCPAYMENT_ID");

CREATE INDEX "APP"."I0000925" ON "APP"."PPCPAYTRAN" ("PPCCREDIT_ID");

CREATE INDEX "APP"."I0001103" ON "APP"."PPCPAYTRAN" ("PPCBATCH_ID");

CREATE UNIQUE INDEX "APP"."I0000002" ON "APP"."ACACTION" ("ACTION");

CREATE UNIQUE INDEX "APP"."I0000274" ON "APP"."EMLCFG" ("STOREENT_ID", "TYPE");

CREATE INDEX "APP"."I0000684" ON "APP"."PAYMTHDSUP" ("STOREENT_ID");

CREATE INDEX "APP"."I0000601" ON "APP"."JURSTGPREL" ("JURSTGROUP_ID");

CREATE UNIQUE INDEX "APP"."I0000187" ON "APP"."PKGATTR" ("CATENTRY_ID", "LANGUAGE_ID", "ATTRIBUTE_ID");

CREATE INDEX "APP"."I0001271" ON "APP"."PKGATTR" ("ATTRIBUTE_ID", "LANGUAGE_ID");

CREATE INDEX "APP"."I0001249" ON "APP"."COLLDESC" ("COLLATERAL_ID");

CREATE INDEX "APP"."I0000254" ON "APP"."TMPRCTLIST" ("SID");

CREATE INDEX "APP"."I0000659" ON "APP"."ORDISTAT" ("ORDSTAT_ID");

CREATE INDEX "APP"."I0000660" ON "APP"."ORDISTAT" ("ORDERITMES_ID");

CREATE INDEX "APP"."I0000661" ON "APP"."ORDISTAT" ("ORDERS_ID");

CREATE UNIQUE INDEX "APP"."I0000170" ON "APP"."ONQUEUE" ("ORRFNBR");

CREATE INDEX "APP"."I0000631" ON "APP"."ONQUEUE" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000041" ON "APP"."BID" ("REFCODE");

CREATE INDEX "APP"."I0000474" ON "APP"."BID" ("OWNER_ID");

CREATE INDEX "APP"."I0000475" ON "APP"."BID" ("STORE_ID");

CREATE INDEX "APP"."I0001243" ON "APP"."BID" ("AUCPAYINFO_ID");

CREATE INDEX "APP"."I0001244" ON "APP"."BID" ("AUCT_ID");

CREATE INDEX "APP"."I0000042" ON "APP"."BID" ("AUTOBID_ID");

CREATE INDEX "APP"."I0000043" ON "APP"."BID" ("BIDQUANT");

CREATE INDEX "APP"."I0000044" ON "APP"."BID" ("BIDPRICE");

CREATE INDEX "APP"."I0000045" ON "APP"."BID" ("BIDSTATUS");

CREATE INDEX "APP"."I0000473" ON "APP"."BID" ("ADMIN_ID");

CREATE INDEX "APP"."I0001367" ON "APP"."SUBSCRTEMPLATE" ("STOREENT_ID");

CREATE INDEX "APP"."I0001368" ON "APP"."SUBSCRTEMPLATE" ("MEMBER_ID");

CREATE INDEX "APP"."I0001369" ON "APP"."SUBSCRTEMPLATE" ("CATENTRY_ID");

CREATE UNIQUE INDEX "APP"."I0000263" ON "APP"."VENDOR" ("STOREENT_ID", "VENDORNAME");

CREATE INDEX "APP"."I0000426" ON "APP"."ACACTACTGP" ("ACACTION_ID");

CREATE INDEX "APP"."I0000533" ON "APP"."CHKARRANG" ("SCHCMD_ID");

CREATE UNIQUE INDEX "APP"."I0001425" ON "APP"."SEOTOKENUSGTYPE" ("TOKENUSGTYPE", "STOREENT_ID");

CREATE INDEX "APP"."I0001426" ON "APP"."SEOTOKENUSGTYPE" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000115" ON "APP"."HMBITEMS" ("HBMRFNBR", "HBTRFNBR", "HBFROMSTMP", "HBTOSTMP");

CREATE UNIQUE INDEX "APP"."I0000195" ON "APP"."PVCDEVMDL" ("DEVMDLNAME", "SESSIONTYPE");

CREATE UNIQUE INDEX "APP"."I0000306" ON "APP"."ACPOLGRP" ("NAME", "MEMBER_ID");

CREATE INDEX "APP"."I0000439" ON "APP"."ACPOLGRP" ("MEMBER_ID");

CREATE INDEX "APP"."I0000136" ON "APP"."INVADJUST" ("INVADJUST_ID", "INVADJCODE_ID", "ADJUSTMENTDATE");

CREATE INDEX "APP"."I0000592" ON "APP"."INVADJUST" ("RECEIPT_ID");

CREATE INDEX "APP"."I0000593" ON "APP"."INVADJUST" ("INVADJCODE_ID");

CREATE UNIQUE INDEX "APP"."I176135" ON "APP"."SCHSTATUS" ("SCSPREFSTART", "SCSJOBNBR");

CREATE INDEX "APP"."I0000762" ON "APP"."SCHSTATUS" ("SCSJOBNBR");

CREATE INDEX "APP"."I274130" ON "APP"."MEMBER" ("MEMBER_ID", "TYPE");

CREATE UNIQUE INDEX "APP"."I0000048" ON "APP"."BUADDR" ("BACODE", "BABURFNBR", "BATYPE");

CREATE INDEX "APP"."I0000484" ON "APP"."BUADDR" ("BABURFNBR");

CREATE INDEX "APP"."I0000802" ON "APP"."SUBORDTAX" ("TAXCGRY_ID");

CREATE UNIQUE INDEX "APP"."I0001105" ON "APP"."USERPWDHST" ("USERS_ID", "PASSWORDCREATION");

CREATE INDEX "APP"."I0000758" ON "APP"."SCHCMD" ("STOREENT_ID");

CREATE INDEX "APP"."I0000180" ON "APP"."ORDRELEASE" ("STATUS", "ORDERS_ID", "ORDRELEASENUM", "PICKBATCH_ID");

CREATE INDEX "APP"."I803140" ON "APP"."ORDRELEASE" ("PICKBATCH_ID");

CREATE INDEX "APP"."I0000836" ON "APP"."ORDRELEASE" ("FFMCENTER_ID");

CREATE INDEX "APP"."I0000837" ON "APP"."ORDRELEASE" ("SHIPMODE_ID");

CREATE INDEX "APP"."I0000838" ON "APP"."ORDRELEASE" ("ADDRESS_ID");

CREATE INDEX "APP"."I0000839" ON "APP"."ORDRELEASE" ("MEMBER_ID");

CREATE INDEX "APP"."I0000840" ON "APP"."ORDRELEASE" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000260" ON "APP"."USERREG" ("LOGONID");

CREATE INDEX "APP"."I716117" ON "APP"."USERREG" ("LOGONID", "USERS_ID");

CREATE INDEX "APP"."I0000330" ON "APP"."USERREG" ("PLCYACCT_ID");

CREATE INDEX "APP"."I0000340" ON "APP"."STATEPROV" ("LANGUAGE_ID", "NAME");

CREATE INDEX "APP"."I0000341" ON "APP"."STATEPROV" ("LANGUAGE_ID", "NAME", "COUNTRYABBR");

CREATE INDEX "APP"."I0000507" ON "APP"."CALRULEMGP" ("CALRULE_ID");

CREATE INDEX "APP"."I0000476" ON "APP"."BIDLOG" ("STORE_ID");

CREATE INDEX "APP"."I0000477" ON "APP"."BIDLOG" ("ADMIN_ID");

CREATE INDEX "APP"."I0000478" ON "APP"."BIDLOG" ("OWNER_ID");

CREATE INDEX "APP"."I0001245" ON "APP"."BIDLOG" ("AUCPAYINFO_ID");

CREATE INDEX "APP"."I0000948" ON "APP"."TICKLER" ("RESPONSIBLEMEMBER", "STORE_ID", "STATUS", "NEXTTICKLEDATE");

CREATE INDEX "APP"."I0000938" ON "APP"."TICKLER" ("STORE_ID");

CREATE INDEX "APP"."I0000939" ON "APP"."TICKLER" ("TKLRREASON_ID");

CREATE INDEX "APP"."I0000940" ON "APP"."TICKLER" ("LANGUAGE_ID");

CREATE INDEX "APP"."I0000941" ON "APP"."TICKLER" ("CREATEDBY_ID");

CREATE INDEX "APP"."I0000942" ON "APP"."TICKLER" ("LOCKEDBY_ID");

CREATE INDEX "APP"."I0000953" ON "APP"."TICKLER" ("RESPONSIBLEROLE", "STORE_ID", "STATUS");

CREATE INDEX "APP"."I0000954" ON "APP"."TICKLER" ("RESPONSIBLEROLE");

CREATE INDEX "APP"."I0000978" ON "APP"."TICKLER" ("STATUS", "NEXTTICKLEDATE");

CREATE UNIQUE INDEX "APP"."I0000211" ON "APP"."RFQRSPTCRL" ("RFQ_ID", "RFQRSP_ID", "RFQTC_ID", "RFQRSPTC_ID");

CREATE UNIQUE INDEX "APP"."I0000212" ON "APP"."RFQRSPTCRL" ("RFQTC_ID", "RFQRSPTC_ID");

CREATE INDEX "APP"."I0000735" ON "APP"."RFQRSPTCRL" ("RFQRSPTC_ID");

CREATE INDEX "APP"."I0000736" ON "APP"."RFQRSPTCRL" ("RFQRSP_ID");

CREATE UNIQUE INDEX "APP"."I0000062" ON "APP"."CATENCALCD" ("STORE_ID", "CATENTRY_ID", "CALCODE_ID", "TRADING_ID");

CREATE INDEX "APP"."I0000514" ON "APP"."CATENCALCD" ("CALCODE_ID");

CREATE INDEX "APP"."I0000515" ON "APP"."CATENCALCD" ("CATENTRY_ID");

CREATE INDEX "APP"."I0000516" ON "APP"."CATENCALCD" ("TRADING_ID");

CREATE UNIQUE INDEX "APP"."I0000068" ON "APP"."CATGRPATTR" ("CATGROUP_ID", "LANGUAGE_ID", "NAME");

CREATE INDEX "APP"."I168207" ON "APP"."CPENDORDER" ("MEMBER_ID");

CREATE INDEX "APP"."I0000542" ON "APP"."CPENDORDER" ("STOREENT_ID");

CREATE INDEX "APP"."I0001303" ON "APP"."DMRANKINGSTAT" ("STOREENT_ID", "DMELEMENT_ID", "GROUP_ID", "TIMECREATED");

CREATE INDEX "APP"."I0000926" ON "APP"."PPCEXTDATA" ("PPCPAYINST_ID");

CREATE INDEX "APP"."I0000927" ON "APP"."PPCEXTDATA" ("PPCPAYTRAN_ID");

CREATE INDEX "APP"."I0000962" ON "APP"."PPCEXTDATA" ("SEARCHVALUE");

CREATE INDEX "APP"."I0001106" ON "APP"."PPCEXTDATA" ("PPCBATCH_ID");

CREATE INDEX "APP"."I0000662" ON "APP"."ORDITAX" ("TAXCGRY_ID");

CREATE UNIQUE INDEX "APP"."I0000019" ON "APP"."ATTRIBUTE" ("CATENTRY_ID", "LANGUAGE_ID", "NAME");

CREATE INDEX "APP"."I0000298" ON "APP"."ATTRIBUTE" ("GROUPNAME", "SEQUENCE");

CREATE UNIQUE INDEX "APP"."I0000103" ON "APP"."FLOW" ("FLOWTYPE_ID", "IDENTIFIER");

CREATE UNIQUE INDEX "APP"."I0001102" ON "APP"."SITE" ("COMPNAME");

CREATE INDEX "APP"."I0001290" ON "APP"."STORLANGDS" ("LANGUAGE_ID_DESC", "STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000181" ON "APP"."ORGCODE" ("CODETYPE", "CODE");

CREATE UNIQUE INDEX "APP"."I0000182" ON "APP"."ORGCODE" ("ORGENTITY_ID", "CODETYPE");

CREATE INDEX "APP"."I0000918" ON "APP"."PPCPAYINST" ("ORDER_ID", "MARKFORDELETE");

CREATE INDEX "APP"."I0000919" ON "APP"."PPCPAYINST" ("RMA_ID", "MARKFORDELETE");

CREATE INDEX "APP"."I0000449" ON "APP"."ACRSCGDES" ("ACRESCGRY_ID");

CREATE INDEX "APP"."I0000906" ON "APP"."DKADJMNT" ("KIT_ID");

CREATE INDEX "APP"."I0000907" ON "APP"."DKADJMNT" ("CATENTRY_ID");

CREATE INDEX "APP"."I0000849" ON "APP"."EDPREFINST" ("EDPRMA_ID");

CREATE INDEX "APP"."I0000500" ON "APP"."CALCODTXEX" ("TAXCGRY_ID");

CREATE INDEX "APP"."I0000383" ON "APP"."EMLSTRPLCY" ("STOREENT_ID");

CREATE INDEX "APP"."I0001308" ON "APP"."UPLOADFILE" ("UPLOADTYPE", "STORE_ID", "OBJECTID");

CREATE INDEX "APP"."I0001309" ON "APP"."UPLOADFILE" ("MEMBER_ID");

CREATE INDEX "APP"."I0001310" ON "APP"."UPLOADFILE" ("STORE_ID");

CREATE INDEX "APP"."I0000841" ON "APP"."CTXDATA" ("ACTIVITY_ID");

CREATE UNIQUE INDEX "APP"."I1244114" ON "APP"."SCHACTIVE" ("SCSPREFSTART", "SCSJOBNBR");

CREATE INDEX "APP"."I0000757" ON "APP"."SCHACTIVE" ("SCSJOBNBR");

CREATE INDEX "APP"."I0001107" ON "APP"."PPCBATCH" ("MERCHCONF_ID");

CREATE INDEX "APP"."I0001108" ON "APP"."PPCBATCH" ("STATE");

CREATE INDEX "APP"."I0000553" ON "APP"."CURLIST" ("STOREENT_ID");

CREATE INDEX "APP"."I0000377" ON "APP"."EMLCAMPREL" ("CAMPAIGN_ID");

CREATE UNIQUE INDEX "APP"."I0000239" ON "APP"."STORECGRY" ("NAME");

CREATE INDEX "APP"."I0000117" ON "APP"."ICEXPLDESC" ("NAME");

CREATE UNIQUE INDEX "APP"."I0000388" ON "APP"."PX_PROMOTION" ("STOREENT_ID", "NAME", "VERSION", "STATUS", "REVISION");

CREATE INDEX "APP"."I0000398" ON "APP"."PX_PROMOTION" ("PX_GROUP_ID");

CREATE INDEX "APP"."I0000399" ON "APP"."PX_PROMOTION" ("CAMPAIGN_ID");

CREATE INDEX "APP"."I0000400" ON "APP"."PX_PROMOTION" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000021" ON "APP"."ATTRVALUE" ("ATTRIBUTE_ID", "CATENTRY_ID", "STRINGVALUE", "LANGUAGE_ID", "INTEGERVALUE", "FLOATVALUE");

CREATE UNIQUE INDEX "APP"."I0000020" ON "APP"."ATTRVALUE" ("ATTRIBUTE_ID", "CATENTRY_ID", "LANGUAGE_ID", "NAME");

CREATE INDEX "APP"."I194153" ON "APP"."ATTRVALUE" ("ATTRTYPE_ID", "CATENTRY_ID", "LANGUAGE_ID", "SEQUENCE");

CREATE INDEX "APP"."I0000453" ON "APP"."ATTRVALUE" ("CATENTRY_ID");

CREATE INDEX "APP"."I0001235" ON "APP"."ATTRVALUE" ("ATTACHMENT_ID");

CREATE INDEX "APP"."I0001236" ON "APP"."ATTRVALUE" ("ATTRIBUTE_ID", "LANGUAGE_ID");

CREATE INDEX "APP"."GRR_CONSTRAINT3" ON "APP"."GRRGSTRNT" ("GIFTREGISTRY_ID", "ADDRESS_ID");

CREATE UNIQUE INDEX "APP"."I0000063" ON "APP"."CATENTATTR" ("CATENTRY_ID", "LANGUAGE_ID", "NAME");

CREATE INDEX "APP"."I0001274" ON "APP"."QTYFMTDESC" ("STOREENT_ID", "QTYUNIT_ID", "NUMBRUSG_ID");

CREATE INDEX "APP"."I0001332" ON "APP"."INSRULEPAYMTHD" ("INSRULE_ID", "PAYMTHD");

CREATE INDEX "APP"."I0001104" ON "APP"."BUSEVENT" ("CHECKED");

CREATE INDEX "APP"."I0000846" ON "APP"."EDPATMPAY" ("EDPPAYINST_ID");

CREATE UNIQUE INDEX "APP"."I0000256" ON "APP"."TRANSPORT" ("NAME");

CREATE INDEX "APP"."I0001502" ON "APP"."EXPLOG" ("SESSIONID", "STOREENT_ID");

CREATE INDEX "APP"."I0001292" ON "APP"."TRDATTACH" ("ATTACHMENT_ID");

CREATE UNIQUE INDEX "APP"."I0001340" ON "APP"."PRICERULE" ("IDENTIFIER", "STOREENT_ID");

CREATE INDEX "APP"."I0001341" ON "APP"."PRICERULE" ("STOREENT_ID");

CREATE INDEX "APP"."I0001342" ON "APP"."PRICERULE" ("TYPE");

CREATE UNIQUE INDEX "APP"."I0000385" ON "APP"."PX_DYNATTR" ("TYPENAME", "ATTRNAME");

CREATE INDEX "APP"."I0001155" ON "APP"."DMEMSPOTSTATS" ("EMSPOT_ID");

CREATE UNIQUE INDEX "APP"."I0000387" ON "APP"."PX_POLICY" ("STOREENT_ID", "NAME");

CREATE INDEX "APP"."I0000395" ON "APP"."PX_POLICY" ("STOREENT_ID");

CREATE INDEX "APP"."I0000436" ON "APP"."ACORGPOL" ("MEMBER_ID");

CREATE UNIQUE INDEX "APP"."I0001500" ON "APP"."EXPERIMENT" ("NAME", "STOREENT_ID");

CREATE INDEX "APP"."I0001501" ON "APP"."EXPERIMENT" ("STOREENT_ID", "STATUS");

CREATE INDEX "APP"."I0000821" ON "APP"."TRDREFAMT" ("TRADING_ID");

CREATE INDEX "APP"."I0000822" ON "APP"."TRDREFAMT" ("RMA_ID");

CREATE INDEX "APP"."I0000823" ON "APP"."TRDREFAMT" ("ORDERS_ID");

CREATE INDEX "APP"."I0000338" ON "APP"."RFQRSPEVAL" ("RFQRSPPROD_ID");

CREATE INDEX "APP"."I0000728" ON "APP"."RFQRSPEVAL" ("RFQRSP_ID");

CREATE INDEX "APP"."I0000729" ON "APP"."RFQRSPEVAL" ("RFQ_ID");

CREATE INDEX "APP"."I0000275" ON "APP"."MBRROLE" ("MEMBER_ID", "ORGENTITY_ID");

CREATE INDEX "APP"."I0000329" ON "APP"."MBRROLE" ("ORGENTITY_ID", "ROLE_ID");

CREATE INDEX "APP"."I0000617" ON "APP"."MBRROLE" ("ROLE_ID");

CREATE INDEX "APP"."I0000529" ON "APP"."CATGRPTPC" ("TRADEPOSCN_ID");

CREATE INDEX "APP"."I0000530" ON "APP"."CATGRPTPC" ("STORE_ID");

CREATE INDEX "APP"."I0000531" ON "APP"."CATGRPTPC" ("CATGROUP_ID");

CREATE UNIQUE INDEX "APP"."I0001409" ON "APP"."SEOPAGEDEF" ("PAGENAME", "STOREENT_ID");

CREATE INDEX "APP"."I0001410" ON "APP"."SEOPAGEDEF" ("STOREENT_ID");

CREATE INDEX "APP"."I0000632" ON "APP"."ORCOMMENT" ("ORDERS_ID");

CREATE INDEX "APP"."I0001264" ON "APP"."ORCOMMENT" ("ORDCHGRSN_ID");

CREATE INDEX "APP"."I0001265" ON "APP"."ORCOMMENT" ("SERVICEREP_ID");

CREATE INDEX "APP"."I0000490" ON "APP"."BUYSUPMAP" ("BUYORGUNIT_ID");

CREATE INDEX "APP"."I0000491" ON "APP"."BUYSUPMAP" ("CATALOG_ID");

CREATE INDEX "APP"."I0000492" ON "APP"."BUYSUPMAP" ("CONTRACT_ID");

CREATE INDEX "APP"."I0000493" ON "APP"."BUYSUPMAP" ("MBRGRP_ID");

CREATE INDEX "APP"."I0000349" ON "APP"."RFQPROD" ("RFQ_ID", "CATENTRY_ID");

CREATE INDEX "APP"."I0000350" ON "APP"."RFQPROD" ("RFQ_ID");

CREATE INDEX "APP"."I0000372" ON "APP"."RFQPROD" ("RFQ_ID", "NEGOTIATIONTYPE");

CREATE INDEX "APP"."I0000726" ON "APP"."RFQPROD" ("CATENTRY_ID");

CREATE INDEX "APP"."I0001278" ON "APP"."RFQPROD" ("RFQCATEGRY_ID");

CREATE INDEX "APP"."I0000674" ON "APP"."ORDSHIPHST" ("RECEIPT_ID");

CREATE INDEX "APP"."I0000675" ON "APP"."ORDSHIPHST" ("VERSIONSPC_ID");

CREATE INDEX "APP"."I0001382" ON "APP"."CFCONDVAL" ("CFCOND_ID");

CREATE INDEX "APP"."I0001383" ON "APP"."CFCONDVAL" ("ATTRVAL_ID");

CREATE INDEX "APP"."I0001394" ON "APP"."CFCONDVAL" ("LANGUAGE_ID");

CREATE INDEX "APP"."I0000286" ON "APP"."TORCPMAP" ("CPWALLET_ID");

CREATE UNIQUE INDEX "APP"."I0001322" ON "APP"."WALLET" ("STOREENT_ID", "MEMBER_ID", "NAME");

CREATE INDEX "APP"."I0001323" ON "APP"."WALLET" ("MEMBER_ID");

CREATE INDEX "APP"."I0000848" ON "APP"."EDPRMA" ("STORE_ID", "RMA_ID");

CREATE UNIQUE INDEX "APP"."I0001429" ON "APP"."SEOURL" ("TOKENVALUE", "TOKENNAME", "SEOURL_ID");

CREATE UNIQUE INDEX "APP"."I0000245" ON "APP"."TAXJCRULE" ("CALRULE_ID", "FFMCENTER_ID", "JURSTGROUP_ID");

CREATE INDEX "APP"."I0000805" ON "APP"."TAXJCRULE" ("JURSTGROUP_ID");

CREATE INDEX "APP"."I0000806" ON "APP"."TAXJCRULE" ("FFMCENTER_ID");

CREATE INDEX "APP"."I0000809" ON "APP"."TDPSCNCNTR" ("TRADEPOSCN_ID");

CREATE INDEX "APP"."I0001400" ON "APP"."SRCHTERM" ("TERM");

CREATE INDEX "APP"."I0001401" ON "APP"."SRCHTERM" ("TYPE");

CREATE INDEX "APP"."I0001402" ON "APP"."SRCHTERM" ("SRCHTERMASSOC_ID");

CREATE INDEX "APP"."I0000633" ON "APP"."ORDADJTXEX" ("TAXCGRY_ID");

CREATE UNIQUE INDEX "APP"."I0000003" ON "APP"."ACATTR" ("ATTRNAME");

CREATE UNIQUE INDEX "APP"."I0000059" ON "APP"."CALSCALE" ("CALUSAGE_ID", "CODE", "STOREENT_ID");

CREATE INDEX "APP"."I0000508" ON "APP"."CALSCALE" ("CALMETHOD_ID");

CREATE INDEX "APP"."I0000509" ON "APP"."CALSCALE" ("STOREENT_ID");

CREATE INDEX "APP"."I0000552" ON "APP"."CURCVLIST" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0001147" ON "APP"."DMELETEMPLATE" ("DMELEMENTTYPE_ID", "NAME", "STOREENT_ID");

CREATE INDEX "APP"."I0001148" ON "APP"."DMELETEMPLATE" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000230" ON "APP"."SHPJCRULE" ("FFMCENTER_ID", "SHIPMODE_ID", "JURSTGROUP_ID", "CALRULE_ID");

CREATE INDEX "APP"."I0000767" ON "APP"."SHPJCRULE" ("SHIPMODE_ID");

CREATE INDEX "APP"."I0000768" ON "APP"."SHPJCRULE" ("JURSTGROUP_ID");

CREATE INDEX "APP"."I0000769" ON "APP"."SHPJCRULE" ("CALRULE_ID");

CREATE INDEX "APP"."I0000313" ON "APP"."INTVSCHED" ("EMSPOT_ID");

CREATE INDEX "APP"."I0000314" ON "APP"."INTVSCHED" ("INITIATIVE_ID");

CREATE INDEX "APP"."I0000590" ON "APP"."INTVSCHED" ("STOREENT_ID");

CREATE INDEX "APP"."I0001348" ON "APP"."PRELEMENTATTR" ("NAME", "VALUE");

CREATE UNIQUE INDEX "APP"."I0001133" ON "APP"."ATTRDICT" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000854" ON "APP"."ATCHTGT" ("STOREENT_ID", "MEMBER_ID", "IDENTIFIER");

CREATE INDEX "APP"."I0000862" ON "APP"."ATCHTGT" ("STOREENT_ID");

CREATE INDEX "APP"."I0000863" ON "APP"."ATCHTGT" ("MEMBER_ID");

CREATE INDEX "APP"."I0000864" ON "APP"."ATCHTGT" ("ATTACHUSG_ID");

CREATE UNIQUE INDEX "APP"."I0000221" ON "APP"."RTNREASON" ("CODE", "STOREENT_ID");

CREATE INDEX "APP"."I0000753" ON "APP"."RTNREASON" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0001226" ON "APP"."INVCNF" ("IDENTIFIER");

CREATE INDEX "APP"."I0000342" ON "APP"."COUNTRY" ("LANGUAGE_ID", "NAME");

CREATE INDEX "APP"."I0000343" ON "APP"."COUNTRY" ("NAME");

CREATE INDEX "APP"."I0000494" ON "APP"."BUYSUPSEC" ("SUPORG_ID");

CREATE UNIQUE INDEX "APP"."I0001209" ON "APP"."STLOC" ("IDENTIFIER");

CREATE INDEX "APP"."I0001210" ON "APP"."STLOC" ("LATITUDE", "LONGITUDE");

CREATE INDEX "APP"."I0001211" ON "APP"."STLOC" ("GEONODE_ID");

CREATE INDEX "APP"."I0000213" ON "APP"."RMA" ("RMA_ID", "RMADATE");

CREATE INDEX "APP"."I836116" ON "APP"."RMA" ("RMA_ID", "STATUS");

CREATE INDEX "APP"."I0000737" ON "APP"."RMA" ("TRADING_ID");

CREATE INDEX "APP"."I0000738" ON "APP"."RMA" ("POLICY_ID");

CREATE INDEX "APP"."I0000739" ON "APP"."RMA" ("ORGENTITY_ID");

CREATE INDEX "APP"."I0000740" ON "APP"."RMA" ("FFMCENTER_ID");

CREATE INDEX "APP"."I0000741" ON "APP"."RMA" ("MEMBER_ID");

CREATE INDEX "APP"."I0000742" ON "APP"."RMA" ("STORE_ID");

CREATE INDEX "APP"."I0000443" ON "APP"."ACRESACT" ("ACACTION_ID");

CREATE INDEX "APP"."I0000800" ON "APP"."SUBORDADJ" ("ORDADJUST_ID");

CREATE UNIQUE INDEX "APP"."I0000898" ON "APP"."SHIPINFO" ("ORDERS_ID", "SHIPMODE_ID", "ADDRESS_ID");

CREATE INDEX "APP"."I0000899" ON "APP"."SHIPINFO" ("ADDRESS_ID");

CREATE INDEX "APP"."I0000900" ON "APP"."SHIPINFO" ("POLICY_ID");

CREATE INDEX "APP"."I0000902" ON "APP"."SHIPINFO" ("SHIPMODE_ID");

CREATE INDEX "APP"."I0000909" ON "APP"."SHDCACRM" ("JOBID");

CREATE INDEX "APP"."I0001287" ON "APP"."SHDCACRM" ("SCHED_ID");

CREATE INDEX "APP"."I0000603" ON "APP"."LANGPAIR" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000288" ON "APP"."EMLMSG" ("STOREENT_ID", "NAME");

CREATE UNIQUE INDEX "APP"."I0001386" ON "APP"."PREQENTRYTYPE" ("IDENTIFIER");

CREATE INDEX "APP"."I0000958" ON "APP"."CALADJUST" ("ORDERS_ID", "CALUSAGE_ID", "SHIPMODE_ID");

CREATE INDEX "APP"."I0000959" ON "APP"."CALADJUST" ("SHIPMODE_ID");

CREATE INDEX "APP"."I0000960" ON "APP"."CALADJUST" ("SERVICEREP_ID");

CREATE INDEX "APP"."I0000961" ON "APP"."CALADJUST" ("CALUSAGE_ID");

CREATE INDEX "APP"."I0000615" ON "APP"."MBRGRPMBR" ("MBRGRP_ID");

CREATE UNIQUE INDEX "APP"."I0000151" ON "APP"."MBRATTR" ("NAME");

CREATE INDEX "APP"."I0000523" ON "APP"."CATGPENREL" ("CATALOG_ID");

CREATE INDEX "APP"."I0000524" ON "APP"."CATGPENREL" ("CATENTRY_ID");

CREATE UNIQUE INDEX "APP"."I0000289" ON "APP"."CPPMN" ("CPPMNNAME", "STOREENT_ID");

CREATE INDEX "APP"."I0000302" ON "APP"."CPPMN" ("ENDDATE");

CREATE INDEX "APP"."I0000546" ON "APP"."CPPMN" ("STOREENT_ID");

CREATE INDEX "APP"."I0001251" ON "APP"."CPPMN" ("INITIATIVE_ID");

CREATE UNIQUE INDEX "APP"."I0000160" ON "APP"."MOPICONFIG" ("PAY_INFO_NAME");

CREATE INDEX "APP"."I0000621" ON "APP"."MOPICONFIG" ("STORE_ID");

CREATE INDEX "APP"."I0000481" ON "APP"."BKORDALLOC" ("ITEMSPC_ID");

CREATE UNIQUE INDEX "APP"."I0000098" ON "APP"."ECETMPT" ("ECDOCTYP", "ECDOCVER", "ECRECTYP", "ECRECVER");

CREATE INDEX "APP"."I0000743" ON "APP"."RMAAUTHLOG" ("RMA_ID");

CREATE INDEX "APP"."I0001407" ON "APP"."DKOFFERADJMNT" ("KIT_ID");

CREATE INDEX "APP"."I0001408" ON "APP"."DKOFFERADJMNT" ("CATENTRY_ID");

CREATE INDEX "APP"."I0000965" ON "APP"."REPCUSTREL" ("CUST_ID");

CREATE UNIQUE INDEX "APP"."I0000185" ON "APP"."PATTRIBUTE" ("NAME");

CREATE UNIQUE INDEX "APP"."I0000204" ON "APP"."RECEIPT" ("VERSIONSPC_ID", "FFMCENTER_ID", "STORE_ID", "CREATETIME");

CREATE INDEX "APP"."I0000205" ON "APP"."RECEIPT" ("RECEIPT_ID", "RADETAIL_ID", "RECEIPTDATE");

CREATE INDEX "APP"."I0000715" ON "APP"."RECEIPT" ("RADETAIL_ID");

CREATE INDEX "APP"."I0000716" ON "APP"."RECEIPT" ("FFMCENTER_ID");

CREATE INDEX "APP"."I0000717" ON "APP"."RECEIPT" ("STORE_ID");

CREATE INDEX "APP"."I0001276" ON "APP"."RECEIPT" ("VENDOR_ID");

CREATE UNIQUE INDEX "APP"."I0000060" ON "APP"."CAMPAIGN" ("NAME", "STOREENT_ID");

CREATE INDEX "APP"."I0000511" ON "APP"."CAMPAIGN" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000140" ON "APP"."ITEMVERSN" ("BASEITEM_ID", "EXPIRATIONDATE");

CREATE UNIQUE INDEX "APP"."I0000141" ON "APP"."ITEMVERSN" ("BASEITEM_ID", "VERSIONNAME");

CREATE INDEX "APP"."I0000782" ON "APP"."STORECAT" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000273" ON "APP"."QUEUE" ("STORE_ID", "NAME");

CREATE INDEX "APP"."I0000272" ON "APP"."APPLY_MEMBER" ("SEGMENTATION_ID", "SEGMENT_INDEX", "SCORE");

CREATE UNIQUE INDEX "APP"."I0000165" ON "APP"."OFFER" ("CATENTRY_ID", "IDENTIFIER", "TRADEPOSCN_ID");

CREATE INDEX "APP"."I0000167" ON "APP"."OFFER" ("CATENTRY_ID", "PUBLISHED", "TRADEPOSCN_ID");

CREATE INDEX "APP"."I0000626" ON "APP"."OFFER" ("TRADEPOSCN_ID");

CREATE INDEX "APP"."I0000663" ON "APP"."ORDITRD" ("TRADING_ID");

CREATE INDEX "APP"."I0000215" ON "APP"."RMAITEM" ("RMA_ID", "RMAITEM_ID");

CREATE INDEX "APP"."I837116" ON "APP"."RMAITEM" ("ORDERITEMS_ID", "RMAITEM_ID", "STATUS", "RMA_ID");

CREATE INDEX "APP"."I0000747" ON "APP"."RMAITEM" ("ITEMSPC_ID");

CREATE INDEX "APP"."I0000748" ON "APP"."RMAITEM" ("MEMBER_ID");

CREATE INDEX "APP"."I0000749" ON "APP"."RMAITEM" ("CATENTRY_ID");

CREATE INDEX "APP"."I0001282" ON "APP"."RMAITEM" ("RTNREASON_ID");

CREATE UNIQUE INDEX "APP"."I0000013" ON "APP"."ADDRBOOK" ("ADDRBOOK_ID", "MEMBER_ID");

CREATE INDEX "APP"."I0000014" ON "APP"."ADDRBOOK" ("MEMBER_ID");

CREATE INDEX "APP"."I0000835" ON "APP"."CMMETADATA" ("CMCONTAINER_ID", "CMRESMGR_ID", "BOKEY1", "BOKEY2", "BOKEY3", "BOKEY4");

CREATE UNIQUE INDEX "APP"."I0000241" ON "APP"."SUBKEYS" ("TABLENAME");

CREATE INDEX "APP"."I0001219" ON "APP"."PX_PROMOAUTH" ("ADMINSTVENAME");

CREATE UNIQUE INDEX "APP"."I0000104" ON "APP"."FLOWADMIN" ("FLOW_ID", "ORGENTITY_ID");

CREATE INDEX "APP"."I0000573" ON "APP"."FLOWADMIN" ("ORGENTITY_ID");

CREATE INDEX "APP"."I0000574" ON "APP"."FLOWADMIN" ("STOREENT_ID");

CREATE INDEX "APP"."I0001414" ON "APP"."SEOREDIRECT" ("SEOURLKWD_ID_NEW");

CREATE INDEX "APP"."I0001424" ON "APP"."SEOREDIRECT" ("SEOURLKWD_ID_ORIG");

CREATE INDEX "APP"."I0001233" ON "APP"."DMMBRGRPPZN" ("PERSONALIZATIONID");

CREATE INDEX "APP"."I0000763" ON "APP"."SHBTB" ("SBBURFNBR");

CREATE INDEX "APP"."I0000418" ON "APP"."ORDPROMOCD" ("ORDERS_ID");

CREATE INDEX "APP"."I0000396" ON "APP"."PX_GRPPOLICY" ("PX_GROUP_ID");

CREATE INDEX "APP"."I0000397" ON "APP"."PX_GRPPOLICY" ("PX_POLICY_ID");

CREATE INDEX "APP"."I0000685" ON "APP"."PAYSTATUS" ("STORE_ID");

CREATE INDEX "APP"."I0000130" ON "APP"."ICTPRICES" ("IPSGNBR");

CREATE INDEX "APP"."I0000131" ON "APP"."ICTPRICES" ("PPPRC");

CREATE INDEX "APP"."I0000583" ON "APP"."ICTPRICES" ("CATENTRY_ID");

CREATE INDEX "APP"."I0000438" ON "APP"."ACPOLGPPOL" ("ACPOLGRP_ID");

CREATE UNIQUE INDEX "APP"."I0000932" ON "APP"."DKOFFER" ("TRADEPOSCN_ID", "KIT_ID", "CATENTRY_ID", "CURRENCY", "IDENTIFIER");

CREATE INDEX "APP"."I0000903" ON "APP"."DKOFFER" ("KIT_ID");

CREATE INDEX "APP"."I0000904" ON "APP"."DKOFFER" ("CATENTRY_ID");

CREATE INDEX "APP"."I0000905" ON "APP"."DKOFFER" ("CURRENCY");

CREATE INDEX "APP"."I0000970" ON "APP"."ORGENTITY" ("DN");

CREATE INDEX "APP"."I0000470" ON "APP"."AUTOBIDLOG" ("ADMIN_ID");

CREATE INDEX "APP"."I0000471" ON "APP"."AUTOBIDLOG" ("OWNER_ID");

CREATE INDEX "APP"."I0000472" ON "APP"."AUTOBIDLOG" ("STORE_ID");

CREATE INDEX "APP"."I0001242" ON "APP"."AUTOBIDLOG" ("AUCPAYINFO_ID");

CREATE UNIQUE INDEX "APP"."I0000057" ON "APP"."CALRLOOKUP" ("CALRANGE_ID", "SETCCURR");

CREATE UNIQUE INDEX "APP"."I0000833" ON "APP"."ESMAPOBJ" ("ESMAPTYP_ID", "OBJECT_ID");

CREATE UNIQUE INDEX "APP"."I0000192" ON "APP"."PROFILE" ("STORE_ID", "TRANSPORT_ID", "MSGTYPE_ID");

CREATE INDEX "APP"."I0000701" ON "APP"."PROFILE" ("MSGTYPE_ID");

CREATE INDEX "APP"."I0000596" ON "APP"."INVOICE" ("ORDERS_ID");

CREATE UNIQUE INDEX "APP"."I0000125" ON "APP"."ICMETAPHOR" ("METAPHORNAME", "CATEGORYID", "STOREID");

CREATE INDEX "APP"."I0000127" ON "APP"."ICMETAPHOR" ("STOREID");

CREATE INDEX "APP"."I0000580" ON "APP"."ICMETAPHOR" ("CATEGORYID");

CREATE INDEX "APP"."I0000581" ON "APP"."ICMETAPHOR" ("TREEID");

CREATE UNIQUE INDEX "APP"."I0001366" ON "APP"."SUBSCRSUSPEND" ("SUBSCRIPTION_ID", "SUSPENDSTARTDATE");

CREATE INDEX "APP"."I0000778" ON "APP"."STORE" ("FFMCENTER_ID");

CREATE INDEX "APP"."I0000779" ON "APP"."STORE" ("STORECGRY_ID");

CREATE INDEX "APP"."I0000780" ON "APP"."STORE" ("RTNFFMCTR_ID");

CREATE INDEX "APP"."I0000781" ON "APP"."STORE" ("CRTDBYCNTR_ID");

CREATE INDEX "APP"."I0001288" ON "APP"."STORE" ("STOREGRP_ID");

CREATE UNIQUE INDEX "APP"."I0000859" ON "APP"."ATCHASTLG" ("ATCHAST_ID", "LANGUAGE_ID");

CREATE INDEX "APP"."I0000871" ON "APP"."ATCHASTLG" ("ATCHAST_ID");

CREATE INDEX "APP"."I0000872" ON "APP"."ATCHASTLG" ("LANGUAGE_ID");

CREATE INDEX "APP"."I0001330" ON "APP"."INSRULECATENT" ("INSRULE_ID", "CATENTRY_ID");

CREATE INDEX "APP"."I0001331" ON "APP"."INSRULECATENT" ("CATENTRY_ID");

CREATE UNIQUE INDEX "APP"."I0000087" ON "APP"."DBMEAS" ("DBMREF", "DBMMFREF", "DBMVIEW");

CREATE INDEX "APP"."I0000353" ON "APP"."RFQRSPPROD" ("RFQRSP_ID", "RFQPROD_ID");

CREATE INDEX "APP"."I0000733" ON "APP"."RFQRSPPROD" ("RFQPROD_ID");

CREATE INDEX "APP"."I0000734" ON "APP"."RFQRSPPROD" ("CATENTRY_ID");

CREATE INDEX "APP"."I0001325" ON "APP"."WIREL" ("WALLETITEM_ID_CHD");

CREATE UNIQUE INDEX "APP"."I0000147" ON "APP"."LMSERVER" ("HOSTNAME", "PORT", "LMENGINENAME");

CREATE INDEX "APP"."I0000311" ON "APP"."LMSERVER" ("LMENGINETYPE", "STOREENT_ID");

CREATE INDEX "APP"."I0000606" ON "APP"."LMSERVER" ("STOREENT_ID");

CREATE INDEX "APP"."I0000331" ON "APP"."ICFEATPROP" ("METAPHORID", "FEATUREID");

CREATE UNIQUE INDEX "APP"."GRE_INDEX1" ON "APP"."GREVNTTYPE" ("EVENTTYPENAME", "STOREID");

CREATE UNIQUE INDEX "APP"."I0000967" ON "APP"."ROLEASNPRM" ("ASSIGNING_ROLE_ID", "ORGENTITY_ID", "ASSIGNABLE_ROLE_ID");

CREATE INDEX "APP"."I0001284" ON "APP"."ROLEASNPRM" ("ORGENTITY_ID");

CREATE INDEX "APP"."I0000797" ON "APP"."STORITMFFC" ("FFMCENTER_ID");

CREATE INDEX "APP"."I0000798" ON "APP"."STORITMFFC" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000109" ON "APP"."FLSTATEGP" ("IDENTIFIER", "FLOWTYPE_ID");

CREATE UNIQUE INDEX "APP"."I0000217" ON "APP"."ROLE" ("NAME");

CREATE INDEX "APP"."I0000658" ON "APP"."ORDIOFFER" ("OFFER_ID");

CREATE INDEX "APP"."I0001198" ON "APP"."DMEXPLOG" ("STOREENT_ID", "PERSONALIZATIONID", "CREATED");

CREATE INDEX "APP"."I0001199" ON "APP"."DMEXPLOG" ("STOREENT_ID", "EXPERIMENT_ID", "TESTELEMENT_ID", "CREATED");

CREATE UNIQUE INDEX "APP"."I0000174" ON "APP"."ORDERMSG" ("OMRECNAME", "OMORNBR", "OMRECSEQ");

CREATE UNIQUE INDEX "APP"."I0000175" ON "APP"."ORDERMSG" ("OMREFNUM");

CREATE INDEX "APP"."I0000651" ON "APP"."ORDERMSG" ("OMORNBR");

CREATE INDEX "APP"."I0001234" ON "APP"."ACCCUSTEXC" ("ACCCMDGRP_ID");

CREATE UNIQUE INDEX "APP"."I0000116" ON "APP"."ICDATAREG" ("CLASSNAME");

CREATE UNIQUE INDEX "APP"."I758147" ON "APP"."PVCBINDING" ("PVCSESSION_ID", "USERS_ID", "CREATED");

CREATE INDEX "APP"."I0000706" ON "APP"."PVCBINDING" ("USERS_ID");

CREATE INDEX "APP"."I0000278" ON "APP"."ORDQUOTREL" ("CHILD_ID");

CREATE INDEX "APP"."I0000308" ON "APP"."ORDQUOTREL" ("PARENT_ID", "RELTYPE", "CHILDSTORE_ID", "CHILD_ID");

CREATE INDEX "APP"."I0000309" ON "APP"."ORDQUOTREL" ("CHILDSTORE_ID", "CHILD_ID", "RELTYPE", "PARENT_ID");

CREATE INDEX "APP"."I0000673" ON "APP"."ORDQUOTREL" ("TRADING_ID");

CREATE UNIQUE INDEX "APP"."I761149" ON "APP"."USERPVCDEV" ("PVCSESSION_ID", "USERS_ID");

CREATE INDEX "APP"."I0000824" ON "APP"."USERPVCDEV" ("USERS_ID");

CREATE UNIQUE INDEX "APP"."I0000234" ON "APP"."STCONF" ("STREFNBR", "STHOSTNAME");

CREATE UNIQUE INDEX "APP"."I0000226" ON "APP"."SCHCONFIG" ("SCCJOBREFNUM", "SCCSEQUENCE");

CREATE INDEX "APP"."I0000321" ON "APP"."SCHCONFIG" ("SCCPATHINFO");

CREATE INDEX "APP"."I0000322" ON "APP"."SCHCONFIG" ("SCCHOST");

CREATE INDEX "APP"."I0000323" ON "APP"."SCHCONFIG" ("SCCAPPTYPE");

CREATE INDEX "APP"."I0000759" ON "APP"."SCHCONFIG" ("MEMBER_ID");

CREATE INDEX "APP"."I0000760" ON "APP"."SCHCONFIG" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000267" ON "APP"."STRELTYP" ("NAME");

CREATE UNIQUE INDEX "APP"."I0001217" ON "APP"."GEOTREE" ("CHILD_GEONODE_ID", "PARENT_GEONODE_ID");

CREATE INDEX "APP"."I0001218" ON "APP"."GEOTREE" ("PARENT_GEONODE_ID");

CREATE UNIQUE INDEX "APP"."I0000832" ON "APP"."ESMAPTYP" ("NAME");

CREATE UNIQUE INDEX "APP"."I0000134" ON "APP"."INITIATIVE" ("NAME", "STOREENT_ID");

CREATE INDEX "APP"."I0000588" ON "APP"."INITIATIVE" ("STOREENT_ID");

CREATE INDEX "APP"."I0000589" ON "APP"."INITIATIVE" ("CAMPAIGN_ID");

CREATE INDEX "APP"."I0000888" ON "APP"."CMFTSKMBREL" ("MEMBER_ID");

CREATE INDEX "APP"."I0000917" ON "APP"."DKPDCOFFERREL" ("OFFER_ID");

CREATE UNIQUE INDEX "APP"."I0000414" ON "APP"."DKPDCCOMPLIST" ("DKPREDEFCONF_ID", "CATENTRY_ID");

CREATE INDEX "APP"."I0000908" ON "APP"."DKPDCCOMPLIST" ("QTYUNIT_ID");

CREATE INDEX "APP"."I0000413" ON "APP"."DKPDCCOMPLIST" ("DKPDCREL_ID");

CREATE INDEX "APP"."I0001256" ON "APP"."DKPDCCOMPLIST" ("CATENTRY_ID");

CREATE UNIQUE INDEX "APP"."I0001137" ON "APP"."ATTRDICTGRPREL" ("ATTRDICTGRP_CHILD");

CREATE UNIQUE INDEX "APP"."I0000011" ON "APP"."ACRESMEMRL" ("MEMBER_ID", "RESOURCEID", "ACRELATION_ID", "ACRESCGRY_ID");

CREATE INDEX "APP"."I0000012" ON "APP"."ACRESMEMRL" ("RESOURCEID", "ACRELATION_ID", "ACRESCGRY_ID");

CREATE INDEX "APP"."I0000447" ON "APP"."ACRESMEMRL" ("ACRESCGRY_ID");

CREATE UNIQUE INDEX "APP"."I0000051" ON "APP"."BZSRVCFG" ("SERVERNAME");

CREATE INDEX "APP"."I0000656" ON "APP"."ORDICALCD" ("ORDERITEMS_ID");

CREATE INDEX "APP"."I0000657" ON "APP"."ORDICALCD" ("CALCODE_ID");

CREATE INDEX "APP"."I0000283" ON "APP"."CPWALLET" ("USERS_ID", "STATE");

CREATE INDEX "APP"."I0000284" ON "APP"."CPWALLET" ("CPPMN_ID", "USERS_ID");

CREATE INDEX "APP"."I0000179" ON "APP"."ORDPAYINFO" ("ORDERS_ID");

CREATE UNIQUE INDEX "APP"."I0000328" ON "APP"."MBRREL" ("DESCENDANT_ID", "SEQUENCE");

CREATE INDEX "APP"."I0000336" ON "APP"."MBRREL" ("ANCESTOR_ID", "SEQUENCE");

CREATE UNIQUE INDEX "APP"."I0000972" ON "APP"."MERCHCONF" ("MERCHANT_ID", "PAYMENTSYSTEM", "PAYCONFGRP");

CREATE INDEX "APP"."I0000744" ON "APP"."RMACHARGE" ("RMAITEM_ID");

CREATE INDEX "APP"."I0000745" ON "APP"."RMACHARGE" ("RMA_ID");

CREATE INDEX "APP"."I0001280" ON "APP"."RMACHARGE" ("CHARGETYPE_ID");

CREATE UNIQUE INDEX "APP"."I0001230" ON "APP"."MGPCONDELE" ("NAME", "MBRGRP_ID");

CREATE INDEX "APP"."I0001231" ON "APP"."MGPCONDELE" ("MBRGRP_ID");

CREATE UNIQUE INDEX "APP"."I0000022" ON "APP"."AUCTION" ("REFCODE");

CREATE INDEX "APP"."I0000023" ON "APP"."AUCTION" ("ENDTIME");

CREATE INDEX "APP"."I0000024" ON "APP"."AUCTION" ("REFPRICE");

CREATE INDEX "APP"."I0000025" ON "APP"."AUCTION" ("STATE");

CREATE INDEX "APP"."I0000455" ON "APP"."AUCTION" ("BIDRULE_ID");

CREATE INDEX "APP"."I0000456" ON "APP"."AUCTION" ("ADMIN_ID");

CREATE INDEX "APP"."I0000457" ON "APP"."AUCTION" ("OWNER_ID");

CREATE INDEX "APP"."I0000458" ON "APP"."AUCTION" ("FFMCENTER_ID");

CREATE INDEX "APP"."I0000459" ON "APP"."AUCTION" ("CATENTRY_ID");

CREATE INDEX "APP"."I0000460" ON "APP"."AUCTION" ("MBRGRP_ID");

CREATE INDEX "APP"."I0001237" ON "APP"."AUCTION" ("AUCPAYINFO_ID");

CREATE INDEX "APP"."I0000026" ON "APP"."AUCTION" ("AUTYPE");

CREATE INDEX "APP"."I0000027" ON "APP"."AUCTION" ("AUSTATUS");

CREATE INDEX "APP"."I0000028" ON "APP"."AUCTION" ("LOCKFLAG");

CREATE INDEX "APP"."I0000029" ON "APP"."AUCTION" ("UPDATETIME");

CREATE INDEX "APP"."I0000030" ON "APP"."AUCTION" ("LASTBKTIME");

CREATE INDEX "APP"."I0000031" ON "APP"."AUCTION" ("STARTTIME");

CREATE UNIQUE INDEX "APP"."I0000110" ON "APP"."FLTRANSITN" ("FLOW_ID", "EVENTIDENTIFIER", "SOURCESTATE_ID", "TARGETSTATE_ID");

CREATE INDEX "APP"."I0001232" ON "APP"."MGPCONDELENVP" ("MGPCONDELE_ID");

CREATE INDEX "APP"."I0001311" ON "APP"."PROCESSFILE" ("MEMBER_ID");

CREATE INDEX "APP"."I0000485" ON "APP"."BUCONT" ("BCBURFNBR");

CREATE UNIQUE INDEX "APP"."I0001159" ON "APP"."DMEMSPOTORD" ("CONTENTTYPE", "ORDERINGNAME");

CREATE INDEX "APP"."I0000276" ON "APP"."CPEMAILMAP" ("SHOPPEREMAILID");

CREATE INDEX "APP"."I0000764" ON "APP"."SHPARJURGP" ("JURSTGROUP_ID");

CREATE UNIQUE INDEX "APP"."I0001393" ON "APP"."CMFEEDLOG" ("FEED_ID", "STOREENT_ID", "FEEDRECORD_ID");

CREATE INDEX "APP"."I0001390" ON "APP"."CMFEEDLOG" ("FEED_ID", "STOREENT_ID");

CREATE INDEX "APP"."I0001333" ON "APP"."INSRULECOND" ("INSRULE_ID");

CREATE INDEX "APP"."I0000676" ON "APP"."ORDTAX" ("TAXCGRY_ID");

CREATE INDEX "APP"."I0000629" ON "APP"."ONLOG" ("STOREENT_ID");

CREATE INDEX "APP"."I0000630" ON "APP"."ONLOG" ("ORRFNBR");

CREATE UNIQUE INDEX "APP"."I0000172" ON "APP"."ORDCHNLTYP" ("NAME");

CREATE INDEX "APP"."I0000482" ON "APP"."BROADCAST" ("STOREENT_ID");

CREATE INDEX "APP"."I0000545" ON "APP"."CPOFFER" ("USERS_ID");

CREATE INDEX "APP"."I0000594" ON "APP"."INVENTORY" ("FFMCENTER_ID");

CREATE INDEX "APP"."I0000595" ON "APP"."INVENTORY" ("STORE_ID");

CREATE INDEX "APP"."I0000751" ON "APP"."RMATAX" ("TAXCGRY_ID");

CREATE UNIQUE INDEX "APP"."I0000086" ON "APP"."DBDTFREQ" ("DBDTREF");

CREATE UNIQUE INDEX "APP"."I0000936" ON "APP"."TKLACTHIST" ("TICKLER_ID", "ACTIONDATE");

CREATE INDEX "APP"."I0000944" ON "APP"."TKLACTHIST" ("TKLRACTION_ID");

CREATE INDEX "APP"."I0000945" ON "APP"."TKLACTHIST" ("LANGUAGE_ID");

CREATE INDEX "APP"."I0000946" ON "APP"."TKLACTHIST" ("CREATEDBY_ID");

CREATE INDEX "APP"."I0000220" ON "APP"."RTNRCPTDSP" ("RTNRECEIPT_ID", "RTNRCPTDSP_ID");

CREATE INDEX "APP"."I0001285" ON "APP"."RTNRCPTDSP" ("RTNDSPCODE_ID");

CREATE INDEX "APP"."I0001286" ON "APP"."RTNRCPTDSP" ("RTNREASON_ID");

CREATE INDEX "APP"."I0000513" ON "APP"."CATCNTR" ("CATALOG_ID");

CREATE INDEX "APP"."I0001357" ON "APP"."STORETPC" ("TRADEPOSCN_ID");

CREATE INDEX "APP"."I0001388" ON "APP"."STORETPC" ("STTPCUSG_ID");

CREATE UNIQUE INDEX "APP"."I0000238" ON "APP"."STFLNAME" ("STDY", "STFILENAME", "STCFRNBR", "STMRFNBR", "STPRNBR", "STCGNBR", "STCMDNAME", "STLOGID");

CREATE UNIQUE INDEX "APP"."I0000190" ON "APP"."PROCPROTCL" ("PROTOCOLNAME", "VERSION");

CREATE UNIQUE INDEX "APP"."I0000099" ON "APP"."ECTPTITM" ("ECSEQNO", "ECRFNBR");

CREATE INDEX "APP"."I0000550" ON "APP"."CRULESCALE" ("CALSCALE_ID");

CREATE UNIQUE INDEX "APP"."I0000085" ON "APP"."DBDELIVERY" ("DBMENBR");

CREATE UNIQUE INDEX "APP"."I0001378" ON "APP"."CFCONDGRP" ("CFCATGROUP_ID", "IDENTIFIER");

CREATE UNIQUE INDEX "APP"."I0000259" ON "APP"."TXCDSCHEME" ("VENDOR", "SOFTWARE");

CREATE INDEX "APP"."I0000852" ON "APP"."EDPRELHIST" ("ORDER_ID", "RELEASE_ID", "STORE_ID");

CREATE UNIQUE INDEX "APP"."I0000879" ON "APP"."ATCHRLUSDS" ("ATCHRLUS_ID", "LANGUAGE_ID");

CREATE UNIQUE INDEX "APP"."I0000007" ON "APP"."ACRELATION" ("RELATIONNAME");

CREATE UNIQUE INDEX "APP"."I0001223" ON "APP"."INVAVL" ("CATENTRY_ID", "STORE_ID", "STLOC_ID");

CREATE INDEX "APP"."I0001224" ON "APP"."INVAVL" ("STORE_ID");

CREATE INDEX "APP"."I0001225" ON "APP"."INVAVL" ("STLOC_ID");

CREATE UNIQUE INDEX "APP"."I0000229" ON "APP"."SHPARRANGE" ("FFMCENTER_ID", "SHIPMODE_ID", "STORE_ID", "STARTDATE", "ENDDATE");

CREATE INDEX "APP"."I0000765" ON "APP"."SHPARRANGE" ("SHIPMODE_ID");

CREATE INDEX "APP"."I0000766" ON "APP"."SHPARRANGE" ("STORE_ID");

CREATE UNIQUE INDEX "APP"."I0000223" ON "APP"."RULECLSREG" ("RULETYPE", "OWNER_ID");

CREATE UNIQUE INDEX "APP"."I0000224" ON "APP"."RULECLSREG" ("NAME", "OWNER_ID");

CREATE INDEX "APP"."I0000756" ON "APP"."RULECLSREG" ("OWNER_ID");

CREATE INDEX "APP"."I0000808" ON "APP"."TCSUBTYPE" ("TCTYPE_ID");

CREATE INDEX "APP"."I0000851" ON "APP"."EDPATMREF" ("EDPREFINST_ID");

CREATE UNIQUE INDEX "APP"."I0000163" ON "APP"."MSGTYPES" ("NAME");

CREATE INDEX "APP"."I0000479" ON "APP"."BIDORDRREL" ("BID_ID");

CREATE UNIQUE INDEX "APP"."I0001345" ON "APP"."PRELEMENT" ("IDENTIFIER", "PRICERULE_ID");

CREATE INDEX "APP"."I0001346" ON "APP"."PRELEMENT" ("PRELETEMPLATE_ID", "PRICERULE_ID");

CREATE INDEX "APP"."I0001347" ON "APP"."PRELEMENT" ("PRICERULE_ID");

CREATE INDEX "APP"."I0000793" ON "APP"."STOREMBRGP" ("STORE_ID");

CREATE INDEX "APP"."I0000543" ON "APP"."DKPDCREL" ("DKPREDEFCONF_ID");

CREATE INDEX "APP"."I0000544" ON "APP"."DKPDCREL" ("CATENTRY_ID");

CREATE INDEX "APP"."I0000412" ON "APP"."DKPDCREL" ("PARENT_ID");

CREATE INDEX "APP"."I0000368" ON "APP"."ORDSTAT" ("ORDERS_ID");

CREATE UNIQUE INDEX "APP"."I0000138" ON "APP"."ITEMSPC" ("PARTNUMBER", "MEMBER_ID");

CREATE INDEX "APP"."I0000139" ON "APP"."ITEMSPC" ("BASEITEM_ID", "ITEMSPC_ID");

CREATE INDEX "APP"."I800140" ON "APP"."ITEMSPC" ("DISCONTINUED");

CREATE INDEX "APP"."I0000361" ON "APP"."ITEMSPC" ("ITEMSPC_ID", "BASEITEM_ID", "PARTNUMBER");

CREATE INDEX "APP"."I0000599" ON "APP"."ITEMSPC" ("MEMBER_ID");

CREATE INDEX "APP"."I0001152" ON "APP"."DMTRIGLSTN" ("NAME", "STOREENT_ID");

CREATE INDEX "APP"."I0001153" ON "APP"."DMTRIGLSTN" ("DMACTIVITY_ID");

CREATE INDEX "APP"."I0001154" ON "APP"."DMTRIGLSTN" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0001417" ON "APP"."SEOURLKEYWORD" ("URLKEYWORD", "STOREENT_ID");

CREATE INDEX "APP"."I0001420" ON "APP"."SEOURLKEYWORD" ("SEOURL_ID");

CREATE INDEX "APP"."I0001421" ON "APP"."SEOURLKEYWORD" ("STOREENT_ID");

CREATE INDEX "APP"."I0001430" ON "APP"."SEOURLKEYWORD" ("LANGUAGE_ID");

CREATE INDEX "APP"."I0001433" ON "APP"."SEOURLKEYWORD" ("MOBILEURLKEYWORD", "STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0001135" ON "APP"."ATTRDICTGRP" ("IDENTIFIER", "ATTRDICT_ID");

CREATE INDEX "APP"."I0001187" ON "APP"."ATTRDICTGRP" ("STOREENT_ID");

CREATE INDEX "APP"."I0001188" ON "APP"."ATTRDICTGRP" ("ATTRDICT_ID");

CREATE UNIQUE INDEX "APP"."I0000005" ON "APP"."ACCOUNT" ("NAME", "MEMBER_ID");

CREATE INDEX "APP"."I0000434" ON "APP"."ACCOUNT" ("MEMBER_ID");

CREATE INDEX "APP"."I0000435" ON "APP"."ACCOUNT" ("STORE_ID");

CREATE UNIQUE INDEX "APP"."I0000107" ON "APP"."FLSTATEDCT" ("IDENTIFIER", "FLOWTYPE_ID");

CREATE UNIQUE INDEX "APP"."I0000108" ON "APP"."FLSTATEDCT" ("STATENAME", "FLOWTYPE_ID");

CREATE INDEX "APP"."I0000575" ON "APP"."FLSTATEDCT" ("FLSTATEGP_ID");

CREATE INDEX "APP"."I0000702" ON "APP"."PRSETCEREL" ("CATENTRY_ID");

CREATE UNIQUE INDEX "APP"."I0000247" ON "APP"."TFALGOREG" ("NAME");

CREATE INDEX "APP"."I0000811" ON "APP"."TFALGOREG" ("MEMBER_ID");

CREATE INDEX "APP"."I0001266" ON "APP"."ORDCHGRSN" ("STOREENT_ID");

CREATE INDEX "APP"."I0000285" ON "APP"."ORCPMAP" ("CPWALLET_ID");

CREATE INDEX "APP"."I0000445" ON "APP"."ACRESGPRES" ("ACRESCGRY_ID");

CREATE INDEX "APP"."I0001359" ON "APP"."PREQENTRY" ("PREQUATION_ID");

CREATE INDEX "APP"."I0001385" ON "APP"."PREQENTRY" ("PREQENTRYTYPE_ID");

CREATE UNIQUE INDEX "APP"."I0000061" ON "APP"."CATALOG" ("MEMBER_ID", "IDENTIFIER");

CREATE INDEX "APP"."I0000664" ON "APP"."ORDPAYMTHD" ("CREDITLINE_ID");

CREATE INDEX "APP"."I0000665" ON "APP"."ORDPAYMTHD" ("TRADING_ID");

CREATE INDEX "APP"."I0000666" ON "APP"."ORDPAYMTHD" ("BUYERPO_ID");

CREATE INDEX "APP"."I0000667" ON "APP"."ORDPAYMTHD" ("PAYSUMMARY_ID");

CREATE INDEX "APP"."I0000668" ON "APP"."ORDPAYMTHD" ("POLICY_ID");

CREATE INDEX "APP"."I0000669" ON "APP"."ORDPAYMTHD" ("RMA_ID");

CREATE INDEX "APP"."I0000670" ON "APP"."ORDPAYMTHD" ("ACCOUNT_ID");

CREATE UNIQUE INDEX "APP"."I0000188" ON "APP"."PKGATTRVAL" ("CATENTRY_ID", "LANGUAGE_ID", "ATTRVALUE_ID");

CREATE INDEX "APP"."I0001272" ON "APP"."PKGATTRVAL" ("ATTRVALUE_ID", "LANGUAGE_ID");

CREATE UNIQUE INDEX "APP"."I0000128" ON "APP"."ICROOTCAT" ("ROOTCATEGORYID", "PFREQ");

CREATE INDEX "APP"."I0000129" ON "APP"."ICROOTCAT" ("LASTMODIFIED");

CREATE INDEX "APP"."I0000582" ON "APP"."ICROOTCAT" ("CATGROUP_ID");

CREATE UNIQUE INDEX "APP"."I0001412" ON "APP"."OICONFIG" ("ORDERITEMS_ID");

CREATE UNIQUE INDEX "APP"."I0001212" ON "APP"."STLOCATTR" ("STLOC_ID", "NAME", "LANGUAGE_ID");

CREATE INDEX "APP"."I0001213" ON "APP"."STLOCATTR" ("VALUE");

CREATE INDEX "APP"."I0001431" ON "APP"."CMEXTDATA" ("CMPRMYOBJ_ID");

CREATE INDEX "APP"."I0001432" ON "APP"."CMEXTDATA" ("ATTRIBUTENAME", "ATTRIBUTEVALUE", "CMPRMYOBJ_ID");

CREATE INDEX "APP"."I0000698" ON "APP"."PROCBUYPRF" ("ORGENTITY_ID");

CREATE INDEX "APP"."I0000333" ON "APP"."ICCNCPTLNK" ("METAPHORID");

CREATE UNIQUE INDEX "APP"."I0000386" ON "APP"."PX_GROUP" ("STOREENT_ID", "GRPNAME");

CREATE INDEX "APP"."I0000394" ON "APP"."PX_GROUP" ("STOREENT_ID");

CREATE INDEX "APP"."I0001297" ON "APP"."PX_RWDOPTION" ("PX_PROMOTION_ID");

CREATE INDEX "APP"."I0001298" ON "APP"."PX_RWDOPTION" ("ORDERS_ID");

CREATE INDEX "APP"."I0000176" ON "APP"."ORDERS" ("MEMBER_ID", "STATUS", "STOREENT_ID");

CREATE INDEX "APP"."I173124" ON "APP"."ORDERS" ("TIMEPLACED");

CREATE INDEX "APP"."I0000652" ON "APP"."ORDERS" ("ADDRESS_ID");

CREATE INDEX "APP"."I0000653" ON "APP"."ORDERS" ("ORGENTITY_ID");

CREATE INDEX "APP"."I0000654" ON "APP"."ORDERS" ("STOREENT_ID");

CREATE INDEX "APP"."I0000892" ON "APP"."ORDERS" ("EDITOR_ID");

CREATE INDEX "APP"."I0000933" ON "APP"."ORDERS" ("SOURCEID");

CREATE INDEX "APP"."I0001267" ON "APP"."ORDERS" ("BUYERPO_ID");

CREATE INDEX "APP"."I0000242" ON "APP"."SUBORDERS" ("TOTALPRODUCT");

CREATE INDEX "APP"."I0000243" ON "APP"."SUBORDERS" ("ORDERS_ID");

CREATE INDEX "APP"."I0000801" ON "APP"."SUBORDERS" ("ADDRESS_ID");

CREATE INDEX "APP"."I0000831" ON "APP"."CTXMGMT" ("CALLER_ID");

CREATE INDEX "APP"."I0000895" ON "APP"."CTXMGMT" ("STORE_ID");

CREATE INDEX "APP"."I0000896" ON "APP"."CTXMGMT" ("RUNAS_ID");

CREATE INDEX "APP"."I0001299" ON "APP"."CTXMGMT" ("LASTACCESSTIME");

CREATE UNIQUE INDEX "APP"."I0000034" ON "APP"."AUTOBID" ("REFCODE");

CREATE INDEX "APP"."I0000468" ON "APP"."AUTOBID" ("ADMIN_ID");

CREATE INDEX "APP"."I0000469" ON "APP"."AUTOBID" ("OWNER_ID");

CREATE INDEX "APP"."I0001240" ON "APP"."AUTOBID" ("AUCT_ID");

CREATE INDEX "APP"."I0001241" ON "APP"."AUTOBID" ("AUCPAYINFO_ID");

CREATE INDEX "APP"."I0000035" ON "APP"."AUTOBID" ("BID_ID");

CREATE INDEX "APP"."I0000036" ON "APP"."AUTOBID" ("ABQUANT");

CREATE INDEX "APP"."I0000037" ON "APP"."AUTOBID" ("MAXBIDLIMIT");

CREATE INDEX "APP"."I0000038" ON "APP"."AUTOBID" ("ABSTATUS");

CREATE INDEX "APP"."I0000467" ON "APP"."AUTOBID" ("STORE_ID");

CREATE INDEX "APP"."I0000850" ON "APP"."EDPPAYHIST" ("ORDER_ID", "STORE_ID");

CREATE INDEX "APP"."I0000910" ON "APP"."EDPPAYHIST" ("EDPPAYINST_ID");

CREATE UNIQUE INDEX "APP"."GIFTITEM_UINDEX1" ON "APP"."GRGFTITM" ("GIFTREGISTRY_ID", "PARTNUMBER", "PARTAUXKEY");

CREATE INDEX "APP"."GIFTITEM_INDEX2" ON "APP"."GRGFTITM" ("GIFTREGISTRY_ID", "PARTNUMBER");

CREATE INDEX "APP"."I0000920" ON "APP"."PPCPAYMENT" ("PPCPAYINST_ID");

CREATE UNIQUE INDEX "APP"."I0000207" ON "APP"."RFQ" ("NAME", "MAJORVERSION", "MINORVERSION");

CREATE INDEX "APP"."I0000348" ON "APP"."RFQ" ("STATE");

CREATE INDEX "APP"."I0000724" ON "APP"."RFQ" ("STORE_ID");

CREATE INDEX "APP"."I0000725" ON "APP"."RFQ" ("MEMBER_ID");

CREATE INDEX "APP"."I0001277" ON "APP"."RFQ" ("TFTRADENG_ID");

CREATE INDEX "APP"."I0000570" ON "APP"."FFMCENTDS" ("STADDRESS_ID");

CREATE INDEX "APP"."I0000703" ON "APP"."PSETADJMNT" ("PRODUCTSET_ID");

CREATE UNIQUE INDEX "APP"."I0001201" ON "APP"."PX_ELEMENT" ("PX_PROMOTION_ID", "NAME");

CREATE UNIQUE INDEX "APP"."I0000231" ON "APP"."STADDRESS" ("MEMBER_ID", "NICKNAME");

CREATE INDEX "APP"."I0000461" ON "APP"."AUCTIONLOG" ("ADMIN_ID");

CREATE INDEX "APP"."I0000462" ON "APP"."AUCTIONLOG" ("FFMCENTER_ID");

CREATE INDEX "APP"."I0000463" ON "APP"."AUCTIONLOG" ("OWNER_ID");

CREATE INDEX "APP"."I0000464" ON "APP"."AUCTIONLOG" ("MBRGRP_ID");

CREATE INDEX "APP"."I0001238" ON "APP"."AUCTIONLOG" ("AUCPAYINFO_ID");

CREATE INDEX "APP"."I0000681" ON "APP"."PATTRPROD" ("CATENTRY_ID");

CREATE INDEX "APP"."I0000488" ON "APP"."BUYERPO" ("ACCOUNT_ID");

CREATE INDEX "APP"."I0000489" ON "APP"."BUYERPO" ("BUYERPOTYP_ID");

CREATE INDEX "APP"."I0000818" ON "APP"."TRDPURAMT" ("TRADING_ID");

CREATE INDEX "APP"."I0000819" ON "APP"."TRDPURAMT" ("ORDERS_ID");

CREATE INDEX "APP"."I0000820" ON "APP"."TRDPURAMT" ("ORDERITEMS_ID");

CREATE INDEX "APP"."I0000374" ON "APP"."BUSAUDIT" ("SESSION_ID", "SEQUENCE");

CREATE UNIQUE INDEX "APP"."I0000248" ON "APP"."TFEXTENG" ("TFTRADENG_ID", "STAGENUM", "ROUNDNUM");

CREATE INDEX "APP"."I0001291" ON "APP"."TFEXTENG" ("TFALGOREG_ID");

CREATE UNIQUE INDEX "APP"."I0000189" ON "APP"."POLICY" ("POLICYNAME", "POLICYTYPE_ID", "STOREENT_ID");

CREATE INDEX "APP"."I0000337" ON "APP"."POLICY" ("POLICYTYPE_ID", "STOREENT_ID");

CREATE INDEX "APP"."I0000697" ON "APP"."POLICY" ("STOREENT_ID");

CREATE INDEX "APP"."I0000280" ON "APP"."CPITMAP" ("ORDERITEMS_ID");

CREATE INDEX "APP"."I0000974" ON "APP"."ORDITEMCONF" ("ORDERITEMS_ID", "OICOMPLIST_ID");

CREATE INDEX "APP"."I0000975" ON "APP"."ORDITEMCONF" ("SERIALNUMBER");

CREATE INDEX "APP"."I0001268" ON "APP"."ORDITEMCONF" ("OICOMPLIST_ID");

CREATE INDEX "APP"."I0001269" ON "APP"."ORDITEMCONF" ("MANIFEST_ID");

CREATE INDEX "APP"."I0000567" ON "APP"."EMLUSRRECV" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000218" ON "APP"."RTNDNYRSN" ("STOREENT_ID", "CODE");

CREATE UNIQUE INDEX "APP"."I0000861" ON "APP"."ATCHRELDSC" ("ATCHREL_ID", "LANGUAGE_ID");

CREATE INDEX "APP"."I0000875" ON "APP"."ATCHRELDSC" ("ATCHREL_ID");

CREATE INDEX "APP"."I0000876" ON "APP"."ATCHRELDSC" ("LANGUAGE_ID");

CREATE INDEX "APP"."I0000709" ON "APP"."QUEUECSR" ("CSR_ID");

CREATE INDEX "APP"."I0001371" ON "APP"."SUBSCRSCHJOBS" ("SUBSCRIPTION_ID");

CREATE INDEX "APP"."I0000922" ON "APP"."PPCCREDIT" ("PPCPAYINST_ID");

CREATE INDEX "APP"."I0000923" ON "APP"."PPCCREDIT" ("PPCPAYMENT_ID");

CREATE UNIQUE INDEX "APP"."I0000935" ON "APP"."TKLRREASON" ("CODE", "STORE_ID");

CREATE INDEX "APP"."I0000943" ON "APP"."TKLRREASON" ("STORE_ID");

CREATE INDEX "APP"."I0000955" ON "APP"."TKLRREASON" ("ASSIGNTOROLE");

CREATE INDEX "APP"."I0001202" ON "APP"."CATENTRYATTR" ("CATENTRY_ID", "USAGE");

CREATE INDEX "APP"."I0001358" ON "APP"."CATENTSUBS" ("SUBSCPTYPE_ID");

CREATE UNIQUE INDEX "APP"."I0001216" ON "APP"."GEONDDS" ("GEONODE_ID", "LANGUAGE_ID");

CREATE UNIQUE INDEX "APP"."I0000149" ON "APP"."MASSOCGPGP" ("STORE_ID", "MASSOCTYPE_ID", "MASSOC_ID", "CATGROUP_ID_FROM", "CATGROUP_ID_TO");

CREATE INDEX "APP"."I0000611" ON "APP"."MASSOCGPGP" ("CATGROUP_ID_FROM");

CREATE INDEX "APP"."I0000612" ON "APP"."MASSOCGPGP" ("CATGROUP_ID_TO");

CREATE INDEX "APP"."I0000304" ON "APP"."CATENTDESC" ("LANGUAGE_ID", "CATENTRY_ID", "NAME", "PUBLISHED");

CREATE INDEX "APP"."I0001196" ON "APP"."CATENTDESC" ("NAME", "LANGUAGE_ID", "PUBLISHED");

CREATE INDEX "APP"."I0001248" ON "APP"."CATENTDESC" ("CATENTRY_ID");

CREATE INDEX "APP"."I0000637" ON "APP"."ORDCALCD" ("CALCODE_ID");

CREATE INDEX "APP"."I0000638" ON "APP"."ORDCALCD" ("ORDERS_ID");

CREATE UNIQUE INDEX "APP"."I0000058" ON "APP"."CALRULE" ("CALCODE_ID", "IDENTIFIER");

CREATE INDEX "APP"."I0000504" ON "APP"."CALRULE" ("TAXCGRY_ID");

CREATE INDEX "APP"."I0000505" ON "APP"."CALRULE" ("CALMETHOD_ID");

CREATE INDEX "APP"."I0000506" ON "APP"."CALRULE" ("CALMETHOD_ID_QFY");

CREATE UNIQUE INDEX "APP"."I0000897" ON "APP"."CMFILE" ("CMFILEPATH");

CREATE INDEX "APP"."I0000934" ON "APP"."CMFILE" ("CMFILEDIR_ID");

CREATE INDEX "APP"."I0000432" ON "APP"."ACCMBRGRP" ("MBRGRP_ID");

CREATE INDEX "APP"."I0000433" ON "APP"."ACCMBRGRP" ("OWNER_ID");

CREATE UNIQUE INDEX "APP"."I0000090" ON "APP"."DBVIEW" ("DBVWREF");

CREATE INDEX "APP"."I0000444" ON "APP"."ACRESATREL" ("ACRESCGRY_ID");

CREATE INDEX "APP"."I0001324" ON "APP"."WALLETITEM" ("WALLET_ID", "TYPE", "NAME", "CREATIONDATE");

CREATE UNIQUE INDEX "APP"."I0000196" ON "APP"."PVCMDLSPEC" ("MODEL_ID", "SPEC_ID", "STOREENT_ID");

CREATE INDEX "APP"."I0000707" ON "APP"."PVCMDLSPEC" ("STOREENT_ID");

CREATE INDEX "APP"."I0000535" ON "APP"."CIITEMLIST" ("MEMBER_ID");

CREATE UNIQUE INDEX "APP"."I0000240" ON "APP"."STOREENT" ("IDENTIFIER", "MEMBER_ID");

CREATE INDEX "APP"."I0000787" ON "APP"."STOREENT" ("MEMBER_ID");

CREATE UNIQUE INDEX "APP"."I0001165" ON "APP"."PX_PROMOCD" ("PX_PROMOTION_ID", "CODE");

CREATE INDEX "APP"."I0001166" ON "APP"."PX_PROMOCD" ("CODE");

CREATE INDEX "APP"."I0000154" ON "APP"."MEMBRAUCT" ("RELATIONTYPE");

CREATE INDEX "APP"."I0000155" ON "APP"."MEMBRAUCT" ("STATUS");

CREATE INDEX "APP"."I0000618" ON "APP"."MEMBRAUCT" ("MEMBER_ID");

CREATE UNIQUE INDEX "APP"."I0000150" ON "APP"."MBINFO" ("MBMERFNBR", "MBBURFNBR", "MBSGRFNBR");

CREATE INDEX "APP"."I0000613" ON "APP"."MBINFO" ("MBBURFNBR");

CREATE UNIQUE INDEX "APP"."I0000186" ON "APP"."PAYMTHD" ("PROFILENAME");

CREATE INDEX "APP"."I0000156" ON "APP"."MESSAGE" ("MSGTYPE");

CREATE INDEX "APP"."I0000157" ON "APP"."MESSAGE" ("DELAY");

CREATE INDEX "APP"."I0000158" ON "APP"."MESSAGE" ("BASE");

CREATE INDEX "APP"."I0000159" ON "APP"."MESSAGE" ("TARGET_ID");

CREATE INDEX "APP"."I0000619" ON "APP"."MESSAGE" ("MEMBER_ID");

CREATE UNIQUE INDEX "APP"."I0000056" ON "APP"."CALRANGE" ("CALSCALE_ID", "RANGESTART");

CREATE INDEX "APP"."I0000503" ON "APP"."CALRANGE" ("CALMETHOD_ID");

CREATE UNIQUE INDEX "APP"."I0000203" ON "APP"."RCPTAVAIL" ("DISTARRANG_ID", "RECEIPT_ID");

CREATE INDEX "APP"."I0000714" ON "APP"."RCPTAVAIL" ("RECEIPT_ID");

CREATE INDEX "APP"."I0000359" ON "APP"."RFQRSPPARL" ("RFQPATTRVALUE_ID");

CREATE INDEX "APP"."I0000730" ON "APP"."RFQRSPPARL" ("RFQ_ID");

CREATE INDEX "APP"."I0000731" ON "APP"."RFQRSPPARL" ("RFQRSP_ID");

CREATE INDEX "APP"."I0000732" ON "APP"."RFQRSPPARL" ("RFQRSPPATTRVAL_ID");

CREATE INDEX "APP"."I0000548" ON "APP"."CPPMNDISC" ("CALCODE_ID");

CREATE INDEX "APP"."I0001252" ON "APP"."CPPMNDISC" ("CPPMN_ID");

CREATE UNIQUE INDEX "APP"."I0000183" ON "APP"."OUTPUTQ" ("NAME");

CREATE UNIQUE INDEX "APP"."I0000177" ON "APP"."ORDIADJUST" ("ORDADJUST_ID", "ORDERITEMS_ID");

CREATE INDEX "APP"."I0000178" ON "APP"."ORDIADJUST" ("ORDERITEMS_ID");

CREATE INDEX "APP"."I0000378" ON "APP"."EMLBOUNCED" ("USERS_ID");

CREATE INDEX "APP"."I0000379" ON "APP"."EMLBOUNCED" ("EMLPROMO_ID");

CREATE INDEX "APP"."I0000380" ON "APP"."EMLBOUNCED" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."GR_INDEX1" ON "APP"."GRGFTREG" ("EXTERNALID");

CREATE INDEX "APP"."GRG_CONSTRAINT1" ON "APP"."GRGFTREG" ("STOREID");

CREATE INDEX "APP"."I0000301" ON "APP"."OICOMPLIST" ("ORDERITEMS_ID");

CREATE INDEX "APP"."I0000371" ON "APP"."OICOMPLIST" ("RFQPROD_ID");

CREATE INDEX "APP"."I0000627" ON "APP"."OICOMPLIST" ("CATENTRY_ID");

CREATE INDEX "APP"."I0000628" ON "APP"."OICOMPLIST" ("ITEMSPC_ID");

CREATE INDEX "APP"."I0001100" ON "APP"."OICOMPLIST" ("ORDERITEMS_ID", "CONFIGURATIONID");

CREATE INDEX "APP"."I0001263" ON "APP"."OICOMPLIST" ("OICOMPREL_ID");

CREATE UNIQUE INDEX "APP"."I0001354" ON "APP"."ORDERREL" ("PARENTORDER_ID", "CHILDORDER_ID");

CREATE UNIQUE INDEX "APP"."I0001355" ON "APP"."ORDERREL" ("PARENTORDERITEM_ID", "CHILDORDER_ID");

CREATE INDEX "APP"."I0001356" ON "APP"."ORDERREL" ("CHILDORDER_ID");

CREATE INDEX "APP"."I0000389" ON "APP"."PX_COUPON" ("STOREENT_ID", "NAME", "VERSION");

CREATE INDEX "APP"."I0000390" ON "APP"."PX_COUPON" ("ORDERS_ID", "USERS_ID");

CREATE INDEX "APP"."I0000391" ON "APP"."PX_COUPON" ("ORDERS_ID", "GUESTID");

CREATE INDEX "APP"."I0000404" ON "APP"."PX_COUPON" ("STOREENT_ID");

CREATE INDEX "APP"."I0000405" ON "APP"."PX_COUPON" ("USERS_ID");

CREATE INDEX "APP"."I0000406" ON "APP"."PX_COUPON" ("ORDERS_ID");

CREATE INDEX "APP"."I0000332" ON "APP"."HISTONVP" ("HISTOID", "HISTOTYPE");

CREATE UNIQUE INDEX "APP"."I0001403" ON "APP"."SRCHATTR" ("INDEXSCOPE", "INDEXTYPE", "IDENTIFIER");

CREATE UNIQUE INDEX "APP"."I0000834" ON "APP"."CMWSSCHEMA" ("WORKSPACE", "ALLOCATED");

CREATE INDEX "APP"."I0000607" ON "APP"."LPOPURAMT" ("BUYERPO_ID");

CREATE INDEX "APP"."I0000608" ON "APP"."LPOPURAMT" ("ORDERS_ID");

CREATE UNIQUE INDEX "APP"."I0001227" ON "APP"."INVCNFREL" ("CATENTRY_ID", "STORE_ID", "STLOC_ID");

CREATE INDEX "APP"."I0001228" ON "APP"."INVCNFREL" ("STORE_ID");

CREATE INDEX "APP"."I0001229" ON "APP"."INVCNFREL" ("STLOC_ID");

CREATE UNIQUE INDEX "APP"."I0001160" ON "APP"."DMEMSPOTCMD" ("CONTENTTYPE", "STOREENT_ID", "EMSPOT_ID");

CREATE INDEX "APP"."I0001161" ON "APP"."DMEMSPOTCMD" ("EMSPOT_ID");

CREATE INDEX "APP"."I0001162" ON "APP"."DMEMSPOTCMD" ("DMEMSPOTORD_ID");

CREATE UNIQUE INDEX "APP"."I0000233" ON "APP"."STBRWSER" ("STDY", "STBROWSER", "STCFRNBR");

CREATE UNIQUE INDEX "APP"."I0000009" ON "APP"."ACRESCGRY" ("RESCLASSNAME");

CREATE INDEX "APP"."I0000538" ON "APP"."COLLABWS" ("ACCOUNT_ID");

CREATE INDEX "APP"."I0000437" ON "APP"."ACPLGPSUBS" ("ACPOLGRP_ID");

CREATE UNIQUE INDEX "APP"."I0001149" ON "APP"."DMELEMENT" ("NAME", "DMACTIVITY_ID");

CREATE INDEX "APP"."I0001150" ON "APP"."DMELEMENT" ("DMELETEMPLATE_ID", "DMACTIVITY_ID");

CREATE INDEX "APP"."I0001151" ON "APP"."DMELEMENT" ("DMACTIVITY_ID");

CREATE INDEX "APP"."I0001136" ON "APP"."ATTRDICTGRPDESC" ("NAME", "LANGUAGE_ID");

CREATE INDEX "APP"."I0000622" ON "APP"."MSGARCHIVE" ("STOREENT_ID");

CREATE UNIQUE INDEX "APP"."I0000264" ON "APP"."VERSIONSPC" ("ITEMSPC_ID", "ITEMVERSN_ID");

CREATE UNIQUE INDEX "APP"."I0000363" ON "APP"."VERSIONSPC" ("VERSIONSPC_ID", "ITEMSPC_ID");

CREATE INDEX "APP"."I0001293" ON "APP"."VERSIONSPC" ("ITEMVERSN_ID");

CREATE INDEX "APP"."I0001380" ON "APP"."CFCOND" ("CFCONDGRP_ID");

CREATE INDEX "APP"."I0001381" ON "APP"."CFCOND" ("ATTR_ID");

CREATE UNIQUE INDEX "APP"."I0000303" ON "APP"."SHPMODCLCD" ("STORE_ID", "CALCODE_ID", "SHIPMODE_ID", "TRADING_ID");

CREATE INDEX "APP"."I0000270" ON "APP"."SHPMODCLCD" ("SHIPMODE_ID");

CREATE INDEX "APP"."I0000271" ON "APP"."SHPMODCLCD" ("STORE_ID");

CREATE INDEX "APP"."I0000268" ON "APP"."SHPMODCLCD" ("TRADING_ID");

CREATE INDEX "APP"."I0000269" ON "APP"."SHPMODCLCD" ("CALCODE_ID");