----CREATE DERBY_*
---CATENTRYATTR:1,403,451
DROP TABLE DERBY_CATENTRYATTR;
CREATE TABLE DERBY_CATENTRYATTR (
        CATENTRY_ID NUMBER NOT NULL,
        ATTR_ID NUMBER NOT NULL,
        ATTRVAL_ID NUMBER NOT NULL,
        USAGE VARCHAR(1) NOT NULL,
        SEQUENCE NUMBER,
        FIELD1 NUMBER,
        FIELD2 NUMBER,
        FIELD3 VARCHAR(254),
        OPTCOUNTER NUMBER NOT NULL
    );
COMMIT;
INSERT INTO DERBY_CATENTRYATTR SELECT CATENTRY_ID,ATTR_ID,ATTRVAL_ID,USAGE,SEQUENCE,FIELD1,FIELD2,FIELD3,OPTCOUNTER FROM CATENTRYATTR
WHERE CATENTRY_ID IN (select CATENTRY_ID from CATGPENREL where catgroup_id in (select catgroup_id_child from catgrprel where catgroup_id_parent in (select catgroup_id from catgrpdesc where name in ('Amplifiers','Kits and Tools'))));
COMMIT;
---OFFER:851,233
DROP TABLE DERBY_OFFER;
CREATE TABLE DERBY_OFFER (
        OFFER_ID NUMBER NOT NULL,
        STARTDATE TIMESTAMP,
        TRADEPOSCN_ID NUMBER NOT NULL,
        CATENTRY_ID NUMBER NOT NULL,
        ENDDATE TIMESTAMP,
        PRECEDENCE NUMBER NOT NULL,
        PUBLISHED NUMBER NOT NULL,
        LASTUPDATE TIMESTAMP,
        MINIMUMQUANTITY NUMBER,
        QTYUNIT_ID VARCHAR(16),
        MAXIMUMQUANTITY NUMBER,
        FIELD1 VARCHAR(30),
        FIELD2 VARCHAR(1),
        FLAGS NUMBER NOT NULL,
        IDENTIFIER NUMBER,
        OID VARCHAR(64),
        OPTCOUNTER NUMBER
    );
COMMIT;
INSERT INTO DERBY_OFFER SELECT OFFER_ID,STARTDATE,TRADEPOSCN_ID,CATENTRY_ID,ENDDATE,PRECEDENCE,PUBLISHED,LASTUPDATE,MINIMUMQUANTITY,QTYUNIT_ID,MAXIMUMQUANTITY,FIELD1,FIELD2,FLAGS,IDENTIFIER,OID,OPTCOUNTER FROM OFFER 
WHERE PUBLISHED=1 AND CATENTRY_ID IN (select CATENTRY_ID from CATGPENREL where catgroup_id in (select catgroup_id_child from catgrprel where catgroup_id_parent in (select catgroup_id from catgrpdesc where name in ('Amplifiers','Kits and Tools'))));
COMMIT; 
--OFFERPRICE:847,382
DROP TABLE DERBY_OFFERPRICE;
CREATE TABLE DERBY_OFFERPRICE (
        OFFER_ID NUMBER NOT NULL,
        CURRENCY VARCHAR(3) NOT NULL,
        PRICE NUMBER(20 , 5) NOT NULL,
        COMPAREPRICE NUMBER(20 , 5),
        OPTCOUNTER NUMBER
    );
COMMIT;
INSERT INTO DERBY_OFFERPRICE SELECT OFFER_ID,CURRENCY,PRICE,COMPAREPRICE,OPTCOUNTER FROM OFFERPRICE 
WHERE OFFER_ID IN (SELECT OFFER_ID FROM DERBY_OFFER);
COMMIT;
--OFFERDESC:
DROP TABLE DERBY_OFFERDESC;
CREATE TABLE DERBY_OFFERDESC (
        OFFER_ID NUMBER NOT NULL,
        LANGUAGE_ID NUMBER NOT NULL,
        DESCRIPTION VARCHAR(254),
        OPTCOUNTER NUMBER
    );
INSERT INTO DERBY_OFFERDESC SELECT OFFER_ID,LANGUAGE_ID,DESCRIPTION,OPTCOUNTER FROM OFFERDESC 
WHERE OFFER_ID IN (SELECT OFFER_ID FROM DERBY_OFFER);
COMMIT;