----CREATE DERBY_*
---CATENTRY:306,948
DROP DERBY_CATENTRY;
CREATE TABLE DERBY_CATENTRY (
		CATENTRY_ID NUMBER NOT NULL,
		MEMBER_ID NUMBER NOT NULL,
		ITEMSPC_ID NUMBER,
		CATENTTYPE_ID VARCHAR(16) NOT NULL,
		PARTNUMBER VARCHAR(64) NOT NULL,
		MFPARTNUMBER VARCHAR(64),
		MFNAME VARCHAR(64),
		MARKFORDELETE NUMBER NOT NULL,
		URL VARCHAR(254),
		FIELD1 NUMBER,
		FIELD2 NUMBER,
		LASTUPDATE TIMESTAMP,
		FIELD3 NUMBER(20 , 5),
		ONSPECIAL NUMBER,
		ONAUCTION NUMBER,
		FIELD4 VARCHAR(254),
		FIELD5 VARCHAR(254),
		BUYABLE NUMBER,
		OID VARCHAR(64),
		BASEITEM_ID NUMBER,
		STATE VARCHAR(1),
		STARTDATE TIMESTAMP,
		ENDDATE TIMESTAMP,
		RANK NUMBER,
		OPTCOUNTER NUMBER,
		AVAILABILITYDATE TIMESTAMP,
		LASTORDERDATE TIMESTAMP,
		ENDOFSERVICEDATE TIMESTAMP,
		DISCONTINUEDATE TIMESTAMP
	);
COMMIT;
INSERT INTO DERBY_CATENTRY SELECT CATENTRY_ID,MEMBER_ID,ITEMSPC_ID,CATENTTYPE_ID,PARTNUMBER,MFPARTNUMBER,MFNAME,MARKFORDELETE,URL,FIELD1,FIELD2,LASTUPDATE,FIELD3,ONSPECIAL,ONAUCTION,FIELD4,FIELD5,BUYABLE,OID,BASEITEM_ID,STATE,STARTDATE,ENDDATE,RANK,OPTCOUNTER,AVAILABILITYDATE,LASTORDERDATE,ENDOFSERVICEDATE,DISCONTINUEDATE 
FROM CATENTRY WHERE CATENTRY_ID IN (select CATENTRY_ID from CATGPENREL where catgroup_id in (select catgroup_id_child from catgrprel where catgroup_id_parent in (select catgroup_id from catgrpdesc where name in ('Amplifiers','Kits and Tools'))));
COMMIT;
---CATENTRYATTR:1,403,451
DROP TABLE DERBY_CATENTRYATTR;
CREATE TABLE DERBY_CATENTRYATTR (
        CATENTRY_ID NUMBER NOT NULL,
        ATTR_ID NUMBER NOT NULL,
        ATTRVAL_ID NUMBER NOT NULL,
        USAGE VARCHAR(1) NOT NULL,
        SEQUENCE NUMBER,
        FIELD1 NUMBER,
        FIELD2 NUMBER,
        FIELD3 VARCHAR(254),
        OPTCOUNTER NUMBER NOT NULL
    );
COMMIT;
INSERT INTO DERBY_CATENTRYATTR SELECT CATENTRY_ID,ATTR_ID,ATTRVAL_ID,USAGE,SEQUENCE,FIELD1,FIELD2,FIELD3,OPTCOUNTER FROM CATENTRYATTR
WHERE CATENTRY_ID IN (SELECT CATENTRY_ID FROM DERBY_CATENTRY);
COMMIT;
---OFFER:851,233
DROP TABLE DERBY_OFFER;
CREATE TABLE DERBY_OFFER (
        OFFER_ID NUMBER NOT NULL,
        STARTDATE TIMESTAMP,
        TRADEPOSCN_ID NUMBER NOT NULL,
        CATENTRY_ID NUMBER NOT NULL,
        ENDDATE TIMESTAMP,
        PRECEDENCE NUMBER NOT NULL,
        PUBLISHED NUMBER NOT NULL,
        LASTUPDATE TIMESTAMP,
        MINIMUMQUANTITY NUMBER,
        QTYUNIT_ID VARCHAR(16),
        MAXIMUMQUANTITY NUMBER,
        FIELD1 VARCHAR(30),
        FIELD2 VARCHAR(1),
        FLAGS NUMBER NOT NULL,
        IDENTIFIER NUMBER,
        OID VARCHAR(64),
        OPTCOUNTER NUMBER
    );
COMMIT;
INSERT INTO DERBY_OFFER SELECT OFFER_ID,STARTDATE,TRADEPOSCN_ID,CATENTRY_ID,ENDDATE,PRECEDENCE,PUBLISHED,LASTUPDATE,MINIMUMQUANTITY,QTYUNIT_ID,MAXIMUMQUANTITY,FIELD1,FIELD2,FLAGS,IDENTIFIER,OID,OPTCOUNTER FROM OFFER 
WHERE PUBLISHED=1 AND CATENTRY_ID IN (SELECT CATENTRY_ID FROM DERBY_CATENTRY);
COMMIT; 
---OFFERPRICE:847,382
DROP TABLE DERBY_OFFERPRICE;
CREATE TABLE DERBY_OFFERPRICE (
        OFFER_ID NUMBER NOT NULL,
        CURRENCY VARCHAR(3) NOT NULL,
        PRICE NUMBER(20 , 5) NOT NULL,
        COMPAREPRICE NUMBER(20 , 5),
        OPTCOUNTER NUMBER
    );
COMMIT;
INSERT INTO DERBY_OFFERPRICE SELECT OFFER_ID,CURRENCY,PRICE,COMPAREPRICE,OPTCOUNTER FROM OFFERPRICE 
WHERE OFFER_ID IN (SELECT OFFER_ID FROM DERBY_OFFER);
COMMIT;
--OFFERDESC:712,673
DROP TABLE DERBY_OFFERDESC;
CREATE TABLE DERBY_OFFERDESC (
        OFFER_ID NUMBER NOT NULL,
        LANGUAGE_ID NUMBER NOT NULL,
        DESCRIPTION VARCHAR(254),
        OPTCOUNTER NUMBER
    );
INSERT INTO DERBY_OFFERDESC SELECT OFFER_ID,LANGUAGE_ID,DESCRIPTION,OPTCOUNTER FROM OFFERDESC 
WHERE OFFER_ID IN (SELECT OFFER_ID FROM DERBY_OFFER);
COMMIT;
---ATTRVAL:56,126
DROP TABLE DERBY_ATTRVAL;
CREATE TABLE DERBY_ATTRVAL (
		ATTRVAL_ID NUMBER NOT NULL,
		ATTR_ID NUMBER NOT NULL,
		IDENTIFIER VARCHAR(254),
		VALUSAGE NUMBER,
		STOREENT_ID NUMBER NOT NULL,
		FIELD1 NUMBER,
		FIELD2 NUMBER,
		FIELD3 VARCHAR(254),
		OPTCOUNTER NUMBER NOT NULL
	);
INSERT INTO DERBY_ATTRVAL SELECT ATTRVAL_ID,ATTR_ID,IDENTIFIER,VALUSAGE,STOREENT_ID,FIELD1,FIELD2,FIELD3,OPTCOUNTER FROM ATTRVAL 
WHERE ATTRVAL_ID IN (SELECT ATTRVAL_ID FROM DERBY_CATENTRYATTR) AND STOREENT_ID <> 0 ORDER BY ATTR_ID;
COMMIT;
---ATTRVALDESC:56,126
DROP TABLE DERBY_ATTRVALDESC;
CREATE TABLE DERBY_ATTRVALDESC (
		ATTRVAL_ID NUMBER NOT NULL,
		LANGUAGE_ID NUMBER NOT NULL,
		ATTR_ID NUMBER NOT NULL,
		VALUE VARCHAR(254),
		VALUSAGE NUMBER,
		SEQUENCE NUMBER,
		STRINGVALUE VARCHAR(2000),
		INTEGERVALUE NUMBER,
		FLOATVALUE NUMBER,
		QTYUNIT_ID VARCHAR(16),
		IMAGE1 VARCHAR(254),
		IMAGE2 VARCHAR(254),
		FIELD1 NUMBER,
		FIELD2 VARCHAR(254),
		FIELD3 VARCHAR(254),
		OPTCOUNTER NUMBER NOT NULL
	);
COMMIT;
INSERT INTO DERBY_ATTRVALDESC SELECT ATTRVAL_ID,LANGUAGE_ID,ATTR_ID,VALUE,VALUSAGE,SEQUENCE,STRINGVALUE,INTEGERVALUE,FLOATVALUE,QTYUNIT_ID,IMAGE1,IMAGE2,FIELD1,FIELD2,FIELD3,OPTCOUNTER 
FROM ATTRVALDESC WHERE ATTRVAL_ID IN (SELECT ATTRVAL_ID FROM DERBY_ATTRVAL);
COMMIT;
---PRSETCEREL:892,932
DROP TABLE DERBY_PRSETCEREL;
CREATE TABLE DERBY_PRSETCEREL (
		PRODUCTSET_ID NUMBER NOT NULL,
		CATENTRY_ID NUMBER NOT NULL,
		OPTCOUNTER NUMBER
	);
COMMIT;
INSERT INTO DERBY_PRSETCEREL SELECT PRODUCTSET_ID,CATENTRY_ID,OPTCOUNTER FROM PRSETCEREL 
WHERE CATENTRY_ID IN (SELECT CATENTRY_ID FROM DERBY_CATENTRY);
COMMIT;
---CATENTDESC:400,064
DROP TABLE DERBY_CATENTDESC;
CREATE TABLE DERBY_CATENTDESC (
		CATENTRY_ID NUMBER NOT NULL,
		LANGUAGE_ID NUMBER NOT NULL,
		NAME VARCHAR(128),
		SHORTDESCRIPTION VARCHAR(350),
		LONGDESCRIPTION VARCHAR(4000),
		THUMBNAIL VARCHAR(254),
		AUXDESCRIPTION1 VARCHAR(4000),
		FULLIMAGE VARCHAR(254),
		AUXDESCRIPTION2 VARCHAR(4000),
		XMLDETAIL VARCHAR(4000),
		AVAILABLE NUMBER NOT NULL,
		PUBLISHED NUMBER NOT NULL,
		AVAILABILITYDATE TIMESTAMP,
		KEYWORD VARCHAR(254),
		OPTCOUNTER NUMBER
	);
COMMIT;
INSERT INTO DERBY_CATENTDESC SELECT CATENTRY_ID,LANGUAGE_ID,NAME,SHORTDESCRIPTION,LONGDESCRIPTION,THUMBNAIL,AUXDESCRIPTION1,FULLIMAGE,AUXDESCRIPTION2,XMLDETAIL,AVAILABLE,PUBLISHED,AVAILABILITYDATE,KEYWORD,OPTCOUNTER 
FROM CATENTDESC WHERE CATENTRY_ID IN (SELECT CATENTRY_ID FROM DERBY_CATENTRY);
COMMIT;
---STORECENT:306,948
DROP TABLE DERBY_STORECENT;
CREATE TABLE DERBY_STORECENT (
		STOREENT_ID NUMBER NOT NULL,
		CATENTRY_ID NUMBER NOT NULL,
		OPTCOUNTER NUMBER
	);
COMMIT;
INSERT INTO DERBY_STORECENT SELECT STOREENT_ID,CATENTRY_ID,OPTCOUNTER FROM STORECENT 
WHERE CATENTRY_ID IN (SELECT CATENTRY_ID FROM DERBY_CATENTRY);
COMMIT;
---CATENTSHIP:306,948
DROP TABLE DERBY_CATENTSHIP;
CREATE TABLE DERBY_CATENTSHIP (
		CATENTRY_ID NUMBER NOT NULL,
		WEIGHT NUMBER,
		WEIGHTMEASURE VARCHAR(16),
		LENGTH NUMBER,
		WIDTH NUMBER,
		HEIGHT NUMBER,
		SIZEMEASURE VARCHAR(16),
		NOMINALQUANTITY NUMBER NOT NULL,
		QUANTITYMULTIPLE NUMBER NOT NULL,
		QUANTITYMEASURE VARCHAR(16) NOT NULL,
		OPTCOUNTER NUMBER
	);
COMMIT;
INSERT INTO DERBY_CATENTSHIP SELECT CATENTRY_ID,WEIGHT,WEIGHTMEASURE,LENGTH,WIDTH,HEIGHT,SIZEMEASURE,NOMINALQUANTITY,QUANTITYMULTIPLE,QUANTITYMEASURE,OPTCOUNTER FROM CATENTSHIP 
WHERE CATENTRY_ID IN (SELECT CATENTRY_ID FROM DERBY_CATENTRY);
COMMIT;
